### ISSUE TITLE
[Help] setVar('body', $view, 'raw')

### ISSUE THREAD

**Issue by BI7PRK** [bcit-ci/CodeIgniter4#1000]
I created a account on forums, but i donnt know why cannt post thread. i have a problem:

### Layout file: ###

```HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>test-{title}</title>
  <style> 
    {styles}
  </style>  
  </head>
  <body>
      <div class="container-fluid">
        {body}
      </div>
    <script>
     {footscript}
    </script>    
  </body>
</html>
```

### View code: ###
```HTML
<div class="wrap">
<ul>
				<?php foreach ($append as $item): ?>
				<li><?=$item['id'] .'='.$item['name']  ?></li>
				<?php endforeach;?>
			</ul>
</div>
```
### Controller code: ###
```PHP
$append = ['append' => [
	['id' => 1, 'name' => 'fsa' ],
	['id' => 2, 'name' => 'fasdf2' ],
	['id' => 3, 'name' => 'fsda3' ]

]];
$bodyview = view('welcome', $append);


$tpldata = [
	'title'=> 'page title', 
	'styles' =>'.div{ font-size:1.1em; }', 
	'footscript' =>'//var b = 1;', 
	'envir' => ENVIRONMENT 
];

$parser = \Config\Services::parser();

echo $parser->setData($tpldata)
	-> setVar('body', $bodyview, 'raw')
	-> render('layout/default');
```

------------------------------------
### But... page body is: ####
![default](https://user-images.githubusercontent.com/24989210/39233883-3cb5acee-48a4-11e8-8399-6ed7f8bb2e66.png)

**Comment by lonnieezell** [comment]
When a person first signs up on the forums, they have to get their first couple of posts approved to help us combat spam. I went to the forums to approve your post and answer there, but I don't see any posts that need approving. What happens when you try to post there?

**Comment by BI7PRK** [comment]
my account has been verified by email. but I don't see the button/links to post in the forum.

**Comment by jim-parry** [comment]
Inside any of the subforums, on the far right of the pagination toolbar, there is a "Start new topic" button.
