### ISSUE TITLE
Php serv CLI stopped working

### ISSUE THREAD

**Issue by deathart** [bcit-ci/CodeIgniter4#1006]
Good morning,

Here I've always had a problem with the `php serv` command that made me crash my command line

To avoid this problem I did it manually with this command : 

```php
php -S 127.0.0.1:8080 -t public/ ../rewrite.php
```

But since the RM https://github.com/bcit-ci/CodeIgniter4/pull/996

The `php spark serve` command still does the same thing to me, except that I have no idea to avoid this problem

And the only problem is I can't find a way to get an error output

I'm on windows 10 with php 7.1.13

Sorry about my English I use a translator

Translated with www.DeepL.com/Translator

**Comment by natanfelles** [comment]
Hi, I'm missing a Windows machine at the moment.

Could you give an `var_dump($rewrite);exit;` on this [line](https://github.com/bcit-ci/CodeIgniter4/pull/996/files#diff-4d86a61fc6d098b569324b15cdd186a9R35), run the `spark serve`, and check if the rewrite.php filepath is valid?

**Comment by deathart** [comment]
Yes filepath is valide

**Comment by deathart** [comment]
In fact I just commented on my op_cache extension and I am no longer a problem, so when you enable opcache on php 7.1.13 with windows 10 there is a problem

**Comment by deathart** [comment]
https://github.com/composer/composer/issues/6106

**Comment by lonnieezell** [comment]
Good find! Thanks for the update.
