### ISSUE TITLE
CSRF Error

### ISSUE THREAD

**Issue by dannywebdev** [bcit-ci/CodeIgniter4#1012]
When the csrf token expires and the form is sent, it throws an error. I guess I should go back to the previous page.

**Comment by puschie286** [comment]
No - that would regenerate the csrf token and provide no protection!
But there should be an easy way of implement your own token expiration handling. In my company we have done this already - so i‘m going to make a PR for this tomorrow.

The recommend way of handling csrf token expiration is to show the empty form with a notice above and to not regenerate the token until the user reload the page manually

**Comment by puschie286** [comment]
we just add a public function to the Security class and override this function in our customSecurity class
currently we return null after this function, but im not sure if this is the best solution ( it stops regenerate the token ).

Security::CSRFVerify:190
```
if ( ! isset($_POST[$this->CSRFTokenName], $_COOKIE[$this->CSRFCookieName]) || $_POST[$this->CSRFTokenName] !== $_COOKIE[$this->CSRFCookieName] )
{
	$this->CSRFError( $request );
	return null;
}
```
