### ISSUE TITLE
Missing method in db result

### ISSUE THREAD

**Issue by smotrikov** [bcit-ci/CodeIgniter4#1022]
Hi , if i use getCustomRowObject() , for example :
`$query = $this->db->query("SELECT 1 as `user_id`,'123@123.ru' as `email` , 'asdasd' as `password` ");
 return $query->getCustomRowObject(0,'App\Entities\User'); `
I get an error : 
`Call to undefined method CodeIgniter\\Database\\MySQLi\\Result::customResultObject()`
customResultObject() is missing in this files :
\system\Database\BaseResult.php and \system\Database\ResultInterface.php

**Comment by jim-parry** [comment]
You are doing something wrong.
Line 65 of system/Database/ResultInterface.php has the signature for customResultObject.
Line 149 in BaseResult starts its implementation.
Are you using the latest CI4 build?

**Comment by jim-parry** [comment]
I see you have posted a thread for this on the forum, which is probably the best place to resolve things. If it turns out to be a bug, then an issue can be raised.

**Comment by Paradinight** [comment]
@jim-parry 
Error Line: https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Database/BaseResult.php#L338

change
isset($this->customResultObject[$className]) || $this->customResultObject($className);

to

isset($this->customResultObject[$className]) || $this->getCustomResultObject($className);

**Comment by jim-parry** [comment]
ah - I couldn't see that even while staring at it :-/
Thanks - will fix ASAP!

**Comment by smotrikov** [comment]
Thanks @jim-parry ) . Thank to @Paradinight  for clarifying )
