### ISSUE TITLE
Class '\CodeIgniter\Database\postgre\Connection' not found

### ISSUE THREAD

**Issue by ngangchill** [bcit-ci/CodeIgniter4#1038]
im trying to connect postgress database but failed.

## Controller:
    $db = \Config\Database::connect();
    $query = $db->table('articles')->get();
    $article = $query->getResult();
   var_dump($article);

## Database Config:
    .'DSN'          => 'postgres://zkcisbrxxxxxxxxxxxxxxxxxxxxxxxd7d@ec2-44-83.compute-1.amazonaws.com:5432/d80mb0dfcjke9j',
		'hostname'     => 'xxxxxxxxxx.compute-1.amazonaws.com',
		'username'     => 'xxxxxxxxxx',
		'password'     => 'bf112fa4501647xxxxxxxxxxxxx06d7d49ebba4735e8063e4db83aa1d7d',
		'database'     => 'db0xxxxxxxxdfcjke9j',
		'DBDriver'     => 'postgre',
     ........ 'port'         => 5432
    .
![ci4png](https://user-images.githubusercontent.com/4242225/40283181-e07d7360-5c9b-11e8-92cf-a2920763cc4a.png)

**Comment by gabpnr** [comment]
Hi,
'DBDriver' => '**P**ostgre'

**Comment by jim-parry** [comment]
Support questions should be askled on our forum, thanks. We use github for bugs & work packages.
Either way, the answer was provided above.
