### ISSUE TITLE
$Email->initialize($config) not work!

### ISSUE THREAD

**Issue by 35598253** [bcit-ci/CodeIgniter4#1042]
https://bcit-ci.github.io/CodeIgniter4/libraries/email.html

**Setting Email Preferences**

$email = \Config\Services::email();
$config['protocol'] = 'sendmail';
$config['mailPath'] = '/usr/sbin/sendmail';
$config['charset']  = 'iso-8859-1';
$config['wordWrap'] = true;

$email->initialize($config);

OR
$email = new \CodeIgniter\Email\Email($config);

print_r($email);
the email config  not change

**Comment by gabpnr** [comment]
initialise() does not support arrays as indicated in the documentation. 
@lonnieezell it should or just an error in the documentation?

@35598253 you can use initialse() with an instance of \Config\Email : 
```
$config = new \Config\Email;
$config->protocol = 'sendmail';
$config->mailPath = '/usr/sbin/sendmail';

$email = new \CodeIgniter\Email\Email($config); 
// or $email->initialize($config); if it is already loaded
```

**Comment by samsonasik** [comment]
since parameter docblock uses `array`, I think we can add cast to object or create a `\Config\Email` instance from array I think, e.g.: 

```php
use Config\Email as ConfigEmail;
// ...
	/**
	 * Initialize preferences
	 *
	 * @param ConfigEmail|array $config
	 *
	 * @return Email
	 */
	public function initialize($config)
	{
		$this->clear();
                
               if (is_array($config)) { 
                    // uses cast 
                   $config = (object) $config;
                    
                    // or create a \Config\Email instance with its properties 
                    $configEmail = new ConfigEmail();
                    foreach ($config as $key => $value) {
                         $configEmail->$key = $value;
                    }
                    $config = $configEmail;
                }
                
                // ...
       }
```

**Comment by lonnieezell** [comment]
You guys are correct. It should support either an array or a Config\Email instance. I think @samsonasik solution is fine. Anyone want to submit a PR?

**Comment by lonnieezell** [comment]
Dang - you beat me to it. I just did another fix for it that is a little more elegant. Will be up shortly.
