### ISSUE TITLE
Session saving

### ISSUE THREAD

**Issue by Przem4S** [bcit-ci/CodeIgniter4#1045]
Hello,
I had problem with session saving, after any refresh session_id was regenerated and.. data lost.
I try FileHandler and DatabaseHandler for saveing session - on both that same problem.
What I do wrong?

```
$this->session = \Config\Services::session();

if(!session_id() || session_id() === '')
{
$this->session->start();
}

var_dump(session_id());
```

**Comment by Przem4S** [comment]
I find in Session somethink why that do this:

`! preg_match('#\A' . $this->sidRegexp . '\z#', $_COOKIE[$this->sessionCookieName]`

/system/Session/Session.php - Line ~205

**Comment by InsiteFX** [comment]
This should be asked in the CodeIgniter Forums and not here, this is for bugs reporting.

**Comment by Przem4S** [comment]
Yes, but this is issue/bug - by this line (in second post) my session was restarts every page reload.

**Comment by lonnieezell** [comment]
First - no need to check session_id() first. Just start the session. 

Second - until it's confirmed it's a bug, this does belong in the forums. I've successfully used the session driver during testing, as have others that have built sites on CI4. Also - scan through the other reports on the forums, as that's sure to get you some help. This driver is nearly identical to the CI3 one, so most of those posts should apply. 

At this point, we don't know that it's a bug. It's entirely likely it's a misconfiguration error. Please ask for help on the forums, as that's what they're there for. And there are many others there that can help you other than the small handful of people that watch the bug reports here.
