### ISSUE TITLE
Toolbar - memory usage

### ISSUE THREAD

**Issue by Przem4S** [bcit-ci/CodeIgniter4#1049]
Memory usage display as 'minus', like on screenshot:
![memory](https://user-images.githubusercontent.com/37654401/40538157-2afbc5b8-6011-11e8-939c-c2903d903bda.PNG)

Debian Linux - Jessie.
PHP 7.1.17.

**Comment by samsonasik** [comment]
I can see the 'minus' as well, php 7.2.2

**Comment by puschie286** [comment]
same problem with apache on ubuntu
with apache on windows it looks right

**Comment by samsonasik** [comment]
tried latest develop and it seems already fixed.

**Comment by lonnieezell** [comment]
@samsonasik Strange. I don't think we've changed anything that should have affected that. Are you still on the same version of PHP / OS you were previously?

**Comment by samsonasik** [comment]
@lonnieezell oh, it seems the issue still there. First refresh, it got the minus: 

![screen shot 2018-07-09 at 7 32 43 pm](https://user-images.githubusercontent.com/459648/42450638-0ddb130a-83af-11e8-9442-21c304752186.png)

Next refresh, the minus gone:

![screen shot 2018-07-09 at 7 32 52 pm](https://user-images.githubusercontent.com/459648/42450648-17166d66-83af-11e8-9890-a8fc2830075e.png)

Step to reproduce:
- php spark serve
- open http://localhost:8080 got minus
- refresh, display correctly.

When it was happen, I use php 7.2.2, now updated to php 7.2.7 in MacOS Sierra.
