### ISSUE TITLE
Router 404

### ISSUE THREAD

**Issue by deathart** [bcit-ci/CodeIgniter4#1050]
Good morning,

Following a commit ( https://github.com/bcit-ci/CodeIgniter4/pull/1047 - https://github.com/bcit-ci/CodeIgniter4/commit/b0975ec5dba9aad0b9076b1621ae917c8779fa33#diff-d2374d65fd714c18dbee9f5adaa8dd6c) 

I have a problem,

Because of the line https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Router/Router.php#L364

When the url is http://127.0.0.1/ I have a 404 error and when I comment this line, I am no more problem

I am under docker (otherwise Xubuntu)

Thank you in advance, and thank you again for the work you do.

Translated with www.DeepL.com/Translator

**Comment by InsiteFX** [comment]
Looks like a space after the /

**Comment by lonnieezell** [comment]
@deathart What does your routes file look like?
