### ISSUE TITLE
class Locale not found when using I18n/Time on xampp localhost

### ISSUE THREAD

**Issue by godguide1** [bcit-ci/CodeIgniter4#1059]
I am trying to add days to a time parsed date by doing

    <?php namespace App\Libraries;
  
        use CodeIgniter\Libraries;
        use CodeIgniter\I18n\Time;

        class Book
        {
              public function getTime()
              {
                   $time = Time::parse('June 1, 2018', 'Australia/Sydney');
                   $time = $time->addDays(7);
                   return $time;
              }
         }

In attempt to getTime() am having class Locale not found Error; Please what do i need to set or tweak to get this working. Thanks.

**Comment by InsiteFX** [comment]
This should be posted in the CI 4 Forums!

$myTime = new Time('now');

**Comment by jim-parry** [comment]
Agreed - questions like this should be raised on our [forum](https://forum.codeigniter.com/index.php).
