### ISSUE TITLE
Entity _options dates

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1061]
When I am trying to add $_options = ['cast' => []]; to one of my class which contains entity  and additionally  I don't wanna  define  dates configuration...  CI is returning an exception and made me to define it (dates cfg for entity):
`Type:        ErrorException
Message:     Undefined index: dates
Filename:    /home/zdamy/site/system/Entity.php
Line Number: 176
`
(I am a huge fan of writing CLI application but I am sure the same is happening during normal requests).

**Comment by nowackipawel** [comment]
I know what is causing this error but you should prevent it if in the documentation there is the example like this:


class User extends Entity
{
    protected $id;
    protected $name;        // Represents a full name now
    protected $email;
    protected $password;
    protected $created_at;
    protected $updated_at;

    protected $_options = [
        'datamap' => [
            'full_name' => 'name'
        ]
    ];
}

/sorry there is no way to format code in this form from mobile device.

**Comment by lonnieezell** [comment]
Just changing the docs is the way to go here :)
