### ISSUE TITLE
HTTP\ResponseTest Language Problem

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#1069]
1) CodeIgniter\HTTP\ResponseTest::testRequiresMessageWithUnknownStatusCode
Failed asserting that exception message 'HTTP.unknownStatusCode' contains 'Unknown HTTP status code provided with no message'.

./phpunit tests/system/HTTP/

fix;
	public function testRequiresMessageWithUnknownStatusCode()
	{
		$response = new Response(new App());

		$this->expectException(HTTPException::class);
		$this->expectExceptionMessage(lang('HTTP.unknownStatusCode', [115]));
		$response->setStatusCode(115);
	}

**Comment by jim-parry** [comment]
Good catch, thanks. I will fix that with my next sweep of the HTTP testing.

**Comment by byazrail** [comment]
No problem, happy coding :)
