### ISSUE TITLE
New Config helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#1071]
Inspired by https://github.com/bcit-ci/CodeIgniter4/pull/1070:

- new `CodeIgniter\Config\Config` class with one public static method: `get()`. This takes a class name and returns an instance of the class. 
- By default it returns a shared instance, but a new instance can be returned by setting the second parameter to `false`, just like the Services class.
- If the config name is fully qualified (`Config\App`) it will simply try to instantiate/cache and return.
- If the config name does not include the namespace (`App`), it will attempt to discover the class similar to way [the Services class does](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Config/BaseService.php#L179), though don't discover and preload all of them, just as requested.
- new helper method, `config()` that is just a slightly nicer way of calling `CodeIgniter\Config\Config::get()`.

**Comment by puschie286** [comment]
first implementation done
should cover all requested aspects
-> documentation missing

i just copy the getClassname function from BaseService, maybe we should move this function to the filelocator ?

another thing is, we should store instances only by class name to avoid storing two instances for name and namspace + name

**Comment by lonnieezell** [comment]
Sorry for the delay - was on vacation. 

> i just copy the getClassname function from BaseService, maybe we should move this function to the filelocator ?

Good idea.

> another thing is, we should store instances only by class name to avoid storing two instances for name and namespace + name 

sounds good

**Comment by puschie286** [comment]
np, me too^^
changes pushed -> next point would be to replace config creation with sharedInstance requests
PS : "The method getClassname() has a Cyclomatic Complexity of 19. The configured cyclomatic complexity threshold is 10" is this settings correct ?

**Comment by lonnieezell** [comment]
That service hasn't been tweaked to our specific requirements yet. It's just something we're trying out. We don't request changes or block diffs based on that report, so nothing to worry about. 

I'll take a look at the PR later today. Thanks.
