### ISSUE TITLE
Codeigniter/Model - Select Database Table Fields

### ISSUE THREAD

**Issue by Tada5hi** [bcit-ci/CodeIgniter4#1072]
I like the Idea of protected/allowed Database Table Fields for insertion and updating data sets. 
But i miss the opportunity, to specify the fields i want to receive from the database table request/query in the extended Model Classes and the Model Class itself.

Furthermore it would be also great for @lonnieezell  [Forum App](https://github.com/lonnieezell/simple-forums) , to set specific fields for Relationship Tables and the own Table which should be selected/received.

**Comment by puschie286** [comment]
would be a nice improvement - also increase table compatibility while development

**Comment by InsiteFX** [comment]
These type of questions should be asked in the CodeIgniter 4 Forums not here.

**Comment by jim-parry** [comment]
Agreed. This sounds like a feature request, and should be raised onthe forum. We use github for tracking bugs and approved work packages.

**Comment by Tada5hi** [comment]
Yo are right, but the model logic needs to be overwritten in some parts, to support the oppurtunity to select only specific fields, otherwise the Model is kinda useless.
For example expect i want to receive all users or a specific user, i would receive all fields. The password field and other fields included, which you dont want to output to other users. Otherwise you have to filter the result data before displaying it to the user. In addition you load data from the database which is not required.

**Comment by lonnieezell** [comment]
First - You can chain Query Builder commands with the model commands, so you should be able to do: 

```
$users = $userModel->select('name, email')->find($id);
```

Second - you should probably filter the data before displaying it to the user anyway, as a security thing. 

Third - don't expect any type of relationships to happen in the models in the core. We've said from day one that an ORM would not be part of the core.
