### ISSUE TITLE
validation  error

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#1077]
```
$validation->setRules([
        'mobile' => 'required|regex_match[/^13[0-9]{1}[0-9]{8}$|15[0189]{1}[0-9]{8}$|189[0-9]{8}$/]'
    ]
);
```

run error
```
ErrorException
preg_match(): No ending delimiter '/' found
```

**Comment by jim-parry** [comment]
This sounds like a support issue, which should be raised on our forum.
We use github for bug tracking and work packages.
If you are indeed suggesting this is a bug, then a better bug description would be appropriate.

**Comment by jinmarcus** [comment]
'rules' => 'required|min_length[2]|max_length[20]|regex_match[/^(01[2689]|09)[0-9]{8}$/]'
in regex_match
If the ' | ' symbol is contained, it will be truncated
