### ISSUE TITLE
Redis Handler Fails

### ISSUE THREAD

**Issue by rumentab** [bcit-ci/CodeIgniter4#1079]
The RedisHandler Fails.
Needs to be changed the use CriticalError statement and the configs merge in the constructor.

line 38: use CodeIgniter\Exceptions\CriticalError;
line 80: $this->config = array_merge($this->config, $config['redis']);

**Comment by lonnieezell** [comment]
"It fails" is not enough detail for us to debug :) 

What code are you using, and what error, if any, is it giving? 

Is this for Cache or Session?

**Comment by lonnieezell** [comment]
Thanks for the detailed response! I've implemented the changes.
