### ISSUE TITLE
Can't use validate with regex_match[]

### ISSUE THREAD

**Issue by HieuPT7** [bcit-ci/CodeIgniter4#1084]
Hi
I use pattern = "/^(01[2689]|09)[0-9]{8}$/" , regex phone number of Viet Nam but it not work

https://bcit-ci.github.io/CodeIgniter4/libraries/validation.html
My Code

```
$validate->setRules([
            'phone' => [
                'label'  => 'Phone Number',
                'rules'  => 'regex_match[/^(01[2689]|09)[0-9]{8}$/]'
            ]
        ]);

```
Thanks !!

**Comment by lonnieezell** [comment]
Did it crash, or just not give the results you intended? If it crashed, what error did it throw? 

Can you provide a phone number (fake preferred) that it should match?

**Comment by 784238ddda92fee476352f3ccaa6cca2** [comment]
An error occured by the character ] in regex pattern.

i tested print_r($pattern) in function regex_match on file  system/Validation/FormatRules.php then it not match with input pattern.

Phone number: https://github.com/datnq/Vietnamese-mobile-carrier

Thanks

**Comment by jinmarcus** [comment]
'rules' => 'required|min_length[2]|max_length[20]|regex_match[/^(01[2689]|09)[0-9]{8}$/]'
in regex_match  
If the ' | ' symbol is contained, it will be truncated

**Comment by jinmarcus** [comment]
I think it should be designed this way
[
            'phone' => [
                'label'  => 'Phone Number',
                'rules'  => [
                    required => true,
                    regex_match => '/^(01[2689]|09)[0-9]{8}$/'
                ]
            ]
]

This is more reasonable

@lonnieezell

**Comment by lonnieezell** [comment]
@jinmarcus did this work in CI3? Trying to figure out if I broke something in the conversion.

**Comment by andreif23** [comment]
@lonnieezell it didn't. i just tested it
