### ISSUE TITLE
safe_mailto - not working 

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1102]
Calling:
`<?php print safe_mailto('email@email.com','title'); ?>`
produces:

`<script type="text/javascript">//<![CDATA[var l=new Array();l[0] = '>';l[1] = 'a';l[2] = '/';l[3] = '<';l[4] = '|101';l[5] = '|108';l[6] = '|116';l[7] = '|105';l[8] = '|116';l[9] = '>';l[10] = '"';l[11] = '|109';l[12] = '|111';l[13] = '|99';l[14] = '|46';l[15] = '|108';l[16] = '|105';l[17] = '|97';l[18] = '|109';l[19] = '|101';l[20] = '|64';l[21] = '|108';l[22] = '|105';l[23] = '|97';l[24] = '|109';l[25] = '|101';l[26] = ':';l[27] = 'o';l[28] = 't';l[29] = 'l';l[30] = 'i';l[31] = 'a';l[32] = 'm';l[33] = '"';l[34] = '=';l[35] = 'f';l[36] = 'e';l[37] = 'r';l[38] = 'h';l[39] = ' ';l[40] = 'a';l[41] = '<';for (var i = l.length-1; i >= 0; i=i-1) {if (l[i].substring(0, 1) === '|') document.write("&#"+unescape(l[i].substring(1))+";");else document.write(unescape(l[i]));}//]]></script>`

I guess it should not be encapsulated in <![CDATA[  ]]>. Am I right?

**Comment by lonnieezell** [comment]
Do you mean not escaped? That would be true.

**Comment by nowackipawel** [comment]
I am not sure why it is not working on chrome with CDATA section. Open https://jsfiddle.net/u5by4aLm/7/ using Chrome. I guess it could be related to doctype.
![download 22](https://user-images.githubusercontent.com/8414802/42801633-8e6a38ec-89a0-11e8-9624-d43ec1dde367.png)


Please correct me if I am wrong but CDATA is required for delivering XHTML compatibility... which is not as popular as few years ago anymore. Anyway, even if I changed doctype to XHTML on jsfiddle nothing changed.

**Comment by lonnieezell** [comment]
You're right. I just tested it also and nothing appears. Hmm. And unfortunately this is just a port from CI3 and I have no clue yet how it works lol. I'll reference the original and see if I can figure out what's going on. If nothing else I have found a tutorial on a pretty good looking variation of it.

**Comment by lonnieezell** [comment]
Actually - I just tried it by removing the CDATA and comment stuff and it works fine in Chrome. I'll do a little research but I think removing that is the way to go. Seems like that was an IE7 fix IIRC.
