### ISSUE TITLE
set_cookie - not working

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter4#1103]
File: System/Helpers/cookie_helper.php
function set_cookie($name, string $value = '', string $expire = '', string $domain = '', string $path = '/', string $prefix = '', bool $secure = false, bool $httpOnly = false)
	{
		// The following line shows as a syntax error in NetBeans IDE
		//(\Config\Services::response())->setcookie
		$response = \Config\Services::response();
		$response->setcookie($name, $value, $expire, $domain, $path, $prefix, $secure, $httpOnly);
		// Add
		$response->sendCookies(); // public
	}

File:/System/HTTP/Response.php
public function setCookie( .....) {
		.....
		$this->cookies[] = [
			'name'     => $prefix.$name,
			'value'    => $value,
			'expires'  => $expire,
			'path'     => $path,
			'domain'   => $domain,
			'secure'   => $secure,
			'httponly' => $httponly,
		];

		return $this; // GO sendCookies()
}

 @lonnieezell

**Comment by dayrui** [comment]
Cookie , No save action

**Comment by lonnieezell** [comment]
cookies are set [later in the process](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/HTTP/Response.php#L647).

Can you provide info so I can recreate the problem, with sample code? Saying "it doesn't work" isn't really helpful :)

**Comment by dayrui** [comment]
<?php namespace App\Controllers;

use CodeIgniter\Controller;

class Save extends Controller
{
	public function index()
	{

		helper('cookie');

        set_cookie('userid', '123', 99999);

        exit(json_encode(['code' => 1, 'msg' => 'success']))
	}

	//--------------------------------------------------------------------

}
@lonnieezell

**Comment by dayrui** [comment]
`<?php namespace App\Controllers;

use CodeIgniter\Controller;

class Home extends Controller
{
	public function index()
	{

		helper('cookie');

        set_cookie('userid', '123', 99999);

        exit(json_encode(['code' => 1, 'msg' => 'success']))
	}

	//--------------------------------------------------------------------

}
`

**Comment by dayrui** [comment]
`<?php namespace App\Controllers;

use CodeIgniter\Controller;

class Save extends Controller
{
	public function index()
	{

		helper('cookie');

        set_cookie('userid', '123', 99999);

        exit(json_encode(['code' => 1, 'msg' => 'success']))
	}

	//--------------------------------------------------------------------

}
`

**Comment by lonnieezell** [comment]
The problem is that you're exiting the script before it has a chance to finish. Instead of existing, check out [Setting the Output](https://bcit-ci.github.io/CodeIgniter4/libraries/response.html#setting-the-output) in the manual. 

Basically, do this instead: 

```
$this->response->setJson(['code' => 1, 'msg' => 'success']);
```

**Comment by dayrui** [comment]
Thanks very much

**Comment by byazrail** [comment]
@lonnieezell system/HTTP/Response.php;
setJSON two return parameter.

	public function setJSON($body)
	{
		$this->body = $this->formatBody($body, 'json');
		return $this;
		return $this;
	}

**Comment by lonnieezell** [comment]
Well - doesn't hurt anything :) Good catch. I'll take care of it, thanks.
