### ISSUE TITLE
Debug Bar Routes params bug

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#1104]
Hi,
Sample url : auth/messages/detail/123123

<img width="1074" alt="screen shot 2018-07-18 at 17 41 14" src="https://user-images.githubusercontent.com/5870455/42888931-f23b595c-8ab1-11e8-94bc-ed3e99a42ada.png">
<img width="489" alt="screen shot 2018-07-18 at 17 42 11" src="https://user-images.githubusercontent.com/5870455/42888950-fbb22b46-8ab1-11e8-8cec-8af3201ad380.png">

**Comment by puschie286** [comment]
the problem here is the sub-sub replacement in Parser::parsePair ( which always escapes ) and Parser::parse ( which only escape single values )

-> working on a fix
