### ISSUE TITLE
[TESTS] Session tests for php 7.2

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#1106]
Tests are throwing the following error in multiple places, and should not be: 

> ErrorException: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

**Comment by lonnieezell** [comment]
@jim-parry I believe I found the 2 locations where it's doing this: 

1. the DotEnv tests is writing to the env/putenv/etc and that seems to be causing it
2. the SessionTest files are starting the session. 

Since these are things that we definitely need to test, I'm not sure how best to tackle this. Too bad it's not just a warning, so we could turn warnings off...

**Comment by jim-parry** [comment]
Ok. I will see what I can do refactoring these, perhaps to use VFSStream (the first) and to destroy any session as part of teardown (second one).

**Comment by jim-parry** [comment]
Session testing was already on my list to revisit :)

**Comment by samsonasik** [comment]
I think `session_write_close()` when `session_status() == PHP_SESSION_ACTIVE` can be used for it like I did at zend-session https://github.com/zendframework/zend-session/pull/107

**Comment by lonnieezell** [comment]
Ooo - good thought. We'll try that shortly. Thanks @samsonasik
