### ISSUE TITLE
#1109 breaks route setup/uri parsing

### ISSUE THREAD

**Issue by puschie286** [bcit-ci/CodeIgniter4#1114]
hey, i guess something went wrong with this PR #1109 -> it result in no route will be found
specific: IncommingRequest.php:695-698

im not sure what this change should do (@jim-parry ) but without extracting the URI part the system is unable to find any route -> PageNotFoundException

URI before 695 : /WorkDirectory/PHPPlayground/CodeIgniter4/public/Home
URI after 700 : /WorkDirectory/PHPPlayground/CodeIgniter4/public/Home
excepted : /Home

BaseURL : 192.168.100.111/WorkDirectory/PHPPlayground/CodeIgniter4/public/
$_SERVER[SCRIPT_NAME] : /WorkDirectory/PHPPlayground/CodeIgniter4/public/index.php

**Comment by jim-parry** [comment]
Hmm - it looks like I missed or mis-specified one of the unit tests in tests/system/HTTP/IncomeRequestDetectingTest, or that we need additional test methods.
Could you take a peek and see what looks out of whack (expected resutls for a given URI)?

It looks like I specified SCRIPT_NAME as just /index,php, which is not in the BaseURL you mention above.

**Comment by puschie286** [comment]
still not working - could you explain what your last part is trying to do ?
i dont get why the last check is necessary.
-> you dont handle the fail of your last elseif

i use `else $uri = (string) substr($uri, strlen(dirname($_SERVER['SCRIPT_NAME'])));` after your statement which fixed it for me, but im not sure what is does exactly^^
