### ISSUE TITLE
[FilesCollection] Allow getFiles with dot syntax

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#112]
We can currently check if a file exists using dot syntax to dig into arrays, but need to implement this feature for `getFile()` also.

Enhancement Checklist:
- [ ] Component(s) modified
- [ ] Unit testing updated
- [ ] User guide updated
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by davidgv88** [comment]
In progress! https://github.com/davidgv88/CodeIgniter4/commit/2985c7d3f2e1dadbb1b6237f83ff1d3afd673cbd

**Comment by davidgv88** [comment]
#357
