### ISSUE TITLE
Routing wrong default value

### ISSUE THREAD

**Issue by HieuPT7** [bcit-ci/CodeIgniter4#1139]
Hi.
In [https://bcit-ci.github.io/CodeIgniter4/general/routing.html](https://bcit-ci.github.io/CodeIgniter4/general/routing.html) 
I use in router

`$routes->add('blog/joe', 'Blogs::users/34');` but this show 404 page.
Can you recheck it.
Thanks

**Comment by byazrail** [comment]
Duplicate #352

**Comment by lonnieezell** [comment]
We've got a number of tests on it. In order to see if it's a bug, I need to know how your controller file is setup. Can you provide code please?

**Comment by HieuPT7** [comment]
In file controller
```

<?php namespace Modules\Blog\Controllers\Admin;

use App\Controllers\AdminBaseController;

class BlogController extends AdminBaseController
{
    public function detail($slug = '')
    {
           return 'Ok';
    }
}

```
In router file.
```

$routes->group('admin', ['namespace' => 'Modules\Blog\Controllers\Admin'], function($routes) 
{
    $routes->get('blog/detail/abc', 'BlogController::detail/dsdsd');
});

```

I access to link: /admin/blog/detail/abc this show 404
But if change router

```
$routes->group('admin', ['namespace' => 'Modules\Blog\Controllers\Admin'], function($routes) 
{
    $routes->get('blog/detail/(:segment)', 'BlogController::detail/$1');
});
```
then success link

Thanks

**Comment by lonnieezell** [comment]
The way you changed it is correct and the way that it's intended to be used.
