### ISSUE TITLE
CSP + .kint   d(foo)

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1174]
When I am trying to print some data using d(foo) and I've got CSP enabled in the same time then there is no css loaded cuz of CSP rules:
I guess this is related to .kint 

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: void 0===window.kintRich&&(window.kintRi.... index:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). Source: .kint-rich{font-size:13px;overflow-x:aut.... index:3
```

Logs from FF console.

**Comment by lonnieezell** [comment]
Nothing we can do here. Kint's a third-party library so we can't change the way it outputs stuff. 

Personally, I recommend not using CSP in development, except to run some tests to make sure it's working correctly. Otherwise - it causes issues like this. :)
