### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by Amin01Kz** [bcit-ci/CodeIgniter4#1179]
There's a typographical error in line 36 in [debugging.rst](https://github.com/bcit-ci/CodeIgniter4/edit/develop/user_guide_src/source/general/debugging.rst)
the function ddd() should be dd()

Also, this page [https://raveren.github.io/kint](https://raveren.github.io/kint) is not available anymore in line 46.

**Comment by lonnieezell** [comment]
Fixed. Thanks/
