### ISSUE TITLE
$myModel->find(string "value-of-my-primary-key")

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1188]
As comment for find method states:

> 
> 	 * Fetches the row of database from $this->table with a primary key
> 	 * matching $id.

what is not true in case when primary key is a string. 
In this case all my rows are returned without any filters instead of desired one.

**Comment by samsonasik** [comment]
this should can be closed as #1189 merged?

**Comment by nowackipawel** [comment]
yeap.
