### ISSUE TITLE
How to use Controller own constructer?

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#1208]
<?php	
	class Blog extends \CodeIgniter\Controller	
	{	
		public function __construct(...$params)	
		{	
			parent::__construct(...$params);	
 			// Your own constructor code	
		}	
	}

not be use __construct

**Comment by byazrail** [comment]
Ref changed controller;
https://github.com/bcit-ci/CodeIgniter4/commit/f4c373ecee3083b01412101127edbc0883a4ee4c

**Comment by jim-parry** [comment]
Support questions should be asked on the forum, thanks.
We use github for bug tracking & work packages.

**Comment by lonnieezell** [comment]
Unless this is referencing someplace in the docs that I missed changing, in which case you should mention that....

**Comment by byazrail** [comment]
@lonnieezell hi,

CRITICAL - 2018-09-08 18:09:22 --> Cannot call constructor
#0 /Users/byazrail/Desktop/www/dev10.net/ThirdParty/Site/Controllers/Site.php(7): App\Core\SiteController->__construct(Array)
#1 /Users/byazrail/Desktop/www/dev10.net/core/CodeIgniter.php(782): Site\Controllers\Site->__construct()
#2 /Users/byazrail/Desktop/www/dev10.net/core/CodeIgniter.php(842): CodeIgniter\CodeIgniter->createController()
#3 /Users/byazrail/Desktop/www/dev10.net/core/CodeIgniter.php(234): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 /Users/byazrail/Desktop/www/dev10.net/public/index.php(48): CodeIgniter\CodeIgniter->run()
#5 /Users/byazrail/Desktop/www/dev10.net/rewrite.php(49): require_once('/Users/byazrail...')
#6 {main}

own extend core controller create __construct not found replaced initController.
How to use own controller extended?

**Comment by byazrail** [comment]
Old codes;
See user guide;
System Class List
The following is a list of the core system files that are invoked every time CodeIgniter runs:
- CodeIgniter\Controller

If you are extending the Controller core class, then be sure to extend your new class in your application controller’s constructors:
class Home extends App\BaseController {

}

My code extends SiteController;
<?php namespace App\Core;

class SiteController extends \CodeIgniter\Controller
{
	protected $langData;
	protected $session;
	protected $themeKey;
	public $userSessionData = false;

    public function __construct(array $param = [], ...$params)
    {
	    parent::__construct(...$params);

        // Your own constructor code
        helper(['url', 'form', 'functions', 'cookie', 'Site\site']);

		\Config\Database::connect();
		$this->session	= \Config\Services::session();

		$this->response->setHeader('Last-Modified', gmdate('D, d M Y H:i:s', time()) .' GMT')
						->setHeader('Content-Type', 'text/html; charset=UTF-8');
.....

Normal Controller And Extends SiteControllers;
<?php namespace Site\Controllers;

class Site extends \App\Core\SiteController
{
    public function __construct(...$params)
    {
        parent::__construct(['forceHttps' => false], ...$params);

        // Autoloads
    }
.......

Extends controllers own controllers $this->response, $this->request how access ?
Codeigniter\Controller not __construct :)
I have temporarily returned to the old code.

Have a nice day.

**Comment by byazrail** [comment]
code restyle bad. attach screens;
<img width="805" alt="screen shot 2018-09-08 at 21 40 53" src="https://user-images.githubusercontent.com/5870455/45257506-f83a0200-b3af-11e8-95b6-aefbbfba2a54.png">
<img width="899" alt="screen shot 2018-09-08 at 21 41 17" src="https://user-images.githubusercontent.com/5870455/45257507-f8d29880-b3af-11e8-9049-ca2273bb962d.png">
