### ISSUE TITLE
Time testing in travis-ci wonky

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#1229]
Travis-ci continues to break intermittently, because one of the tests can be out by 1 second. The error has nothing to do with any changes made in a PR. 

**CodeIgniter 4 version**
develop

**Error message**

1) CodeIgniter\I18n\TimeTest::testTimeWithDateTimeZone
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2018-09-21 19:56:07'
+'2018-09-21 19:56:08'
/home/travis/build/bcit-ci/CodeIgniter4/tests/system/I18n/TimeTest.php:76

**Comment by puschie286** [comment]
we can reduce the frequency of it occurring by creating the control time right at the beginning

**Comment by jim-parry** [comment]
I'm going to call this one done - I don't see any recurrences of the timing hiccups.
To boot, we now know how to fix them :-/
