### ISSUE TITLE
Testing output buffer not closed

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#1230]
A change was made at some point over the last few months, which results in some tests being flagged as "risky". The travis-ci builds, but the risky tests mess up code coverage.

**CodeIgniter 4 version**
develop

**Affected module(s)**
Travis-ci log excerpt:

2) CodeIgniter\CodeIgniterTest::testRunDefaultRoute
Test code or tested code did not (only) close its own output buffers
3) CodeIgniter\CodeIgniterTest::testRunEmptyDefaultRoute
Test code or tested code did not (only) close its own output buffers
4) CodeIgniter\CodeIgniterTest::testRun404Override
Test code or tested code did not (only) close its own output buffers
5) CodeIgniter\CodeIgniterTest::testControllersCanReturnString
Test code or tested code did not (only) close its own output buffers
6) CodeIgniter\CodeIgniterTest::testControllersCanReturnResponseObject
Test code or tested code did not (only) close its own output buffers
7) CodeIgniter\CodeIgniterTest::testRoutesIsEmpty
Test code or tested code did not (only) close its own output buffers
8) CodeIgniter\CodeIgniterTest::testTransfersCorrectHTTPVersion
Test code or tested code did not (only) close its own output buffers
9) FeatureTestCaseTest::testCallGet
Test code or tested code did not (only) close its own output buffers

**Comment by puschie286** [comment]
the source of all this is the CodeIgniter::tryToRouteIt where ob_start opens a new buffer but it doesnt close.

workaround : use tearDown to clear open buffers #1242

**Comment by jim-parry** [comment]
Fixed by #1242
