### ISSUE TITLE
Route in the News Tutorial Routes are ERROR all over.

### ISSUE THREAD

**Issue by InsiteFX** [bcit-ci/CodeIgniter4#1240]
Doing the News Tutorial since you changed the routing of the controller.

All the routes are giving a 404 error unless I change them from get and post to add.

Also the create method is throwing a expected array error on the request.
Lonnie something is wrong in the new way the routes and requests are working.

**Comment by jim-parry** [comment]
The above is part of the fix. Checking the routes now

**Comment by lonnieezell** [comment]
It looks like the issue happens when a combination of `get` routes and `add` routes are used, like: 

```
$routes->add('/', 'Home::index');
$routes->get('news', 'News::index');
$routes->get('news/(:segment)', 'News::view/$1');
$routes->add('(:any)', 'Pages::view/$1');
```

However, if all of the routes are changed to either `get` or `add` it works as expected.
