### ISSUE TITLE
TODO Toolbar needs logging

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#1258]
Debug/Toolbar has a todo note...
Needs to be logged, in constructor

**Comment by bangbangda** [comment]
More detailed description?
record the error message in the log file?

**Comment by jim-parry** [comment]
The only "todo" mention I see in the Debug/Toolbar class is in the constructor, where it implies that any non-existing collectors should trigger a log message.
My guess is handling it similarly to Debug/Exceptions::exceptionHandler.
Someone party to the original implementation might be able to shed more light on the intent.

**Comment by lonnieezell** [comment]
Yes, it was just to put something in the logs a developer could find to show they had a wrong classname. My usual preference is to throw an exception, but in this case didn't want to stop the toolbar from working, but did want to give the developer a chance to discover it.

**Comment by bangbangda** [comment]
ok
