### ISSUE TITLE
error 404 in routing with controller in subdirectories

### ISSUE THREAD

**Issue by hlmqz** [bcit-ci/CodeIgniter4#1276]
---
name: error 404 in routing with controller in subdirectories
about: Route with subdirectories not work!

---

**Describe the bug**
the section "Organizing Your Controllers into Sub-directories" explained in https://bcit-ci.github.io/CodeIgniter4/incoming/controllers.html#id8 not work!

**CodeIgniter 4 version**
CodeIgniter4 4.0.0-alpha.1

its work! 
![code_ok](https://user-images.githubusercontent.com/7216267/46268101-426d5980-c4fe-11e8-9070-a0d47f22056c.png)
![resp_ok](https://user-images.githubusercontent.com/7216267/46268112-50bb7580-c4fe-11e8-95c1-b2ec51b22810.png)

example with subdirectories not work!
![code_bug](https://user-images.githubusercontent.com/7216267/46268133-721c6180-c4fe-11e8-8362-c231aa94fcf6.png)
![resp_bug](https://user-images.githubusercontent.com/7216267/46268137-76e11580-c4fe-11e8-969b-be1832541be6.png)

 I tried with directory name in lowercase, but it not work.

**Context**
 - OS: Ubuntu 18.04 
 - Web server: Apache 2.4.29
 - PHP version 7.2.10

**Comment by lonnieezell** [comment]
You didn't change the namespace in `Othertest.php` to reflect the location in the subfolder. It should be `namespace App\Controllers\Mysubfolder`
