### ISSUE TITLE
News Tutorial Routes

### ISSUE THREAD

**Issue by InsiteFX** [bcit-ci/CodeIgniter4#1288]
Lonnie,

In the news Tutorial.

Static Pages: - The route is this.
`$routes->get('(:any)', 'Pages::view/$1');`

But at the end of the Create News Items - You have this, which route is the correct one?
`$routes->post('news/create', 'News::create');
$routes->add('news/(:segment)', 'News::view/$1');
$routes->get('news', 'News::index');
$routes->add('(:any)', 'Pages::view/$1');
`

Also the post news create does not work 404 page change the route to add and the form comes up but with the validation errors.

**Comment by lonnieezell** [comment]
Sorry - haven't had a chance to finish going through that tutorial. With code I pushed up last night, either should work, but I'd keep it all get/post and no generic `add()` if you're seeing issues still.
