### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by agus-prawoto** [bcit-ci/CodeIgniter4#1290]
I just simply run a simple form validation:

$validation->setRule('first_name', 'First Name', 'required');
$validation->run();
print_r($validation->getErrors());

Output:
Array
(
    [first_name] => The First Name field is required.
)

print_r($_POST);
Output:
Array
(
    [first_name] => Agus
)

**Comment by lonnieezell** [comment]
There's no bug here. You didn't give validation any data to validate against. 

You might try `$validation->withRequest()->run()`, or use [the controller's helper method](https://bcit-ci.github.io/CodeIgniter4/incoming/controllers.html#validating-post-data).
