### ISSUE TITLE
News Tutorial post riute still not working

### ISSUE THREAD

**Issue by InsiteFX** [bcit-ci/CodeIgniter4#1292]
Lonnie,

The News Tutorial get route doe's work now.

But the post route throw's a 404 Page Not Found Create ERROR.
If you change the route to an add route it then works but thow's the form validation errors.

**Comment by lonnieezell** [comment]
Just checking - does your form tag have `method="post"`? I'm sure it does, but that's the most obvious reason.

**Comment by lonnieezell** [comment]
Actually - it was the routing. I've fixed it in the latest commit, but the route to the form should use `match` instead of `post`: 

```
$routes->match(['get', 'post'], 'news/create', 'News::create');
```
