### ISSUE TITLE
Config files aren't discovered automatically when using the config() function.

### ISSUE THREAD

**Issue by bvrignaud** [bcit-ci/CodeIgniter4#1293]
I'm actually porting the Ion-Auth (3) to CI4.
You can have look to the wip here : [https://github.com/bvrignaud/CodeIgniter-Ion-Auth/tree/4](https://github.com/bvrignaud/CodeIgniter-Ion-Auth/tree/4).
I'm based on [Code Modules](https://bcit-ci.github.io/CodeIgniter4/general/modules.html?highlight=module#config-files) documentation.

As the documentation explain :
> Config files are automatically discovered whenever using the config() function that is always available.

I have a config file in my module_directory/Config.
In my library / model / controller, I'm trying to load my config file with **config('IonAuth')**
But it can't be load.
It works only if I put my config file in application/Config.

Thanks

**CodeIgniter 4 version**
The last develop version

**Context**
 - OS: LMDE 3
 - Web server : Apache on docker
 - PHP version : 7.1

**Comment by lonnieezell** [comment]
Where does the namespace point to? The way the scanning works is to look at the directory the namespace represents, like `Modules/IonAuth` and look for `Config/{file}.php` there. In this case that would be `Modules/IonAuth/Config/{file}.php`

If you including the package through Composer, the namespace would still have to be defined in `application/Config/Autoload.php` to work.

**Comment by bvrignaud** [comment]
I think I hadn't understood well the documentation.
As you can see, I had code it like this : https://github.com/bvrignaud/CodeIgniter-Ion-Auth/commit/72509bf4910c8ae8b323bc8dd39fe96bade35554
My first idea was to make something like this and if the final developer want to configure special settings, he have to duplicate the config file in the application/Config directory. And that doesn't works.
But, as I saw, we can set settings in .env file. So It's Ok.

Sorry for the inconvenience.
