### ISSUE TITLE
Making Views path changeable

### ISSUE THREAD

**Issue by BadeelProject** [bcit-ci/CodeIgniter4#1296]
The great feature of the CI3x is its flexibility according to the environment, especially in paths. Therefore, it would be  a great thing to make the views path movable.
I found a way to do it simply by altering a few files in the system folder, but it would be better if it's supported officially as feature of the core.

**Comment by lonnieezell** [comment]
If you'll look at [system/Config/Services](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Config/Services.php#L485) you'll find that the first argument to the `renderer` service is the view folder. If you have your views in a different folder all of the time you can override this method in `application/Config/Services` and set your own path so it's always used. If you need to use multiple you can get new instances of the renderer with different paths. So, it's already pretty flexible. 

It probably wouldn't hurt to add a `setViewPath` method to the View class, though.

**Comment by bangbangda** [comment]
the views path change frequently? If I only need to set it once, I think it would be better to add $viewPath in `application/Config/View.php`. 
how do you like it?

**Comment by lonnieezell** [comment]
Adding `$viewPath` to `application/Config/Paths.php` would be fine. Then `system/Config/Services.php` would need to be updated to use that as a default if none was provided. 

I would take a PR for that.

**Comment by bangbangda** [comment]
yes. good idea

**Comment by BadeelProject** [comment]
sorry for the late response ^^
@bangbangda have pointed to the tricky thing in your solution ^^
I'm managed to do that, but i had to change about 5 files in system folder to support altering viewpath from application/config, and this must be done on every copy of ci4 .
