### ISSUE TITLE
Small Typo Correction

### ISSUE THREAD

**Issue by rmcdahal** [bcit-ci/CodeIgniter4#1299]
**Classmap**
The classmap is used extensively by CodeIgniter to _eke_ the last ounces of performance out of the system by not hitting the file-system with extra file_exists() calls. You can use the classmap to link to third-party libraries that are not namespaced:
https://bcit-ci.github.io/CodeIgniter4/concepts/autoloader.html

EKE Should be Make

**Comment by qury** [comment]
"eke" seems perfectly fine to me.

**Comment by jim-parry** [comment]
"eke" is correct - it means to squeeze a bit more out of something, in this case performance.
Separately, the performance gains of the classmap are being questioned, so it may not be in the final project. Either way, no wording change is needed right now.
