### ISSUE TITLE
 Environment Configuration file

### ISSUE THREAD

**Issue by smartnathan** [bcit-ci/CodeIgniter4#1309]
Environment Configuration file does not work even after uncommenting adding the value.

**Comment by jim-parry** [comment]
A few more details? This doesn't give enough to work with.

**Comment by smartnathan** [comment]
OK, I will be more detailed.

**Comment by Xcreen** [comment]
I have the same problem. (or understanding the .env-configuration wrong)

For example i uncommenting app.baseURL in the .env-file(in root folder) and added the value there.
And leaving application/Config/App.php as default ($baseURL = '';).
The value will not be changed, so page throws error (empty or invalid base URL).

I guess that is something the issue-creator have also done.

**Comment by smartnathan** [comment]
Ok

**Comment by lonnieezell** [comment]
What is your OS and other details @Xcreen? 

I'm on a Mac using the following line in `.env` and it works just fine: 

```app.baseURL=http://localhost:8080```

**Comment by Xcreen** [comment]
OS: Windows 10 (1803)
Xampp with: Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/7.1.22
(A small info: Symfony-Framework with .env-file works on the same Maschine on the same Xampp.)

**Comment by lonnieezell** [comment]
@Xcreen Any chance you could try to debug that? I don't have a Windows/Xampp machine around to test it on. 

or if you and @smartnathan cannot reproduce anymore we can just close it.

**Comment by jim-parry** [comment]
The .env in the application folder was wrong, and has been removed.
Good that this is working as expected :)
