### ISSUE TITLE
 Filter in the router

### ISSUE THREAD

**Issue by demortx** [bcit-ci/CodeIgniter4#1315]
$routes->group('System',['namespace' => 'App\API\v1\System', 'filter' => 'api-guard'] , function($routes)

The api-guard filter has 2 methods before and after, for my ap it is necessary to log what happened during the request, and if we set the fitr through a router, then the after method simply does not work.

In the documentation about this there is no information, because of this, it was added that this is a mistake.

**CodeIgniter 4 version**
4.0.0-alpha.1

**Context**
 - OS: ubuntu16.04.1
 - PHP version 7.2.8-1

**Comment by lonnieezell** [comment]
It could be worded better, but the docs do say "This will always run the filter before the controller". 

Currently, it only supports running the `before` filter, when defined that way. Definitely open if you want to submit a PR for that!

**Comment by bangbangda** [comment]
I want to submit this PR.
How about setting up the filter like this?

`$routes->group('admin', ['namespace' => 'App\Controllers\Admin', 'filter' => ['before' => ['adminAuth'], 'after' => ['adminLog']]], function($routes)
{
});`

@lonnieezell

**Comment by lonnieezell** [comment]
I am fine with that if you want to submit that PR.
