### ISSUE TITLE
Incorrect Error Message ?

### ISSUE THREAD

**Issue by agus-prawoto** [bcit-ci/CodeIgniter4#1328]
Hi, when I call the session but it not initiated, CI4 gives an error on database instead of the session itself (this might confuse developers, they might guess the error come from database connection), for example, if I call:

$this->session->get('user_id');

form Models/WelcomeModel.php

it gives an error message:

CodeIgniter\Database\Exceptions\DatabaseException #8
You must set the database table to be used with your query.	search →

BASEPATH/Database\BaseConnection.php at line 933

**Comment by puschie286** [comment]
i guess the problem is the model - not the session
can you try it in the controller ? or something else without database dependency

**Comment by agus-prawoto** [comment]
Hi, in controller I got this error message:

ErrorException
Undefined property: App\Controllers\Item::$session

APPPATH/Controllers\Item.php at line 15

I think this error message is more meaningful rather than in the model

**Comment by lonnieezell** [comment]
By default on controllers there is no class property with the session. You must define one yourself, or get an instance of the session use the Service or the helper: 

```
session()->get('user_id');
   or 
$this->session = \Config\Services::session();
$this->session->get('user_id');
```

Not an error with the framework. You're just trying to use it like it's CI3...

**Comment by skywizzy** [comment]
> agus

Bro you just saved my project, thanks bro, i have been battling with this same error thinking is from my database not knowing is session error, i got the misleading error message below while the main error is from session. thanks bro...

CRITICAL - 2023-07-11 11:25:36 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 883.
 1 SYSTEMPATH\Model.php(642): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(803): CodeIgniter\Model->builder()
 3 APPPATH\Models\Superadmin_db.php(98): CodeIgniter\Model->__get('session')
 4 APPPATH\Controllers\Superadmin_ci.php(37): App\Models\Superadmin_db->adminfetchTopMsg()
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Superadmin_ci->superadmin_dashboard()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Superadmin_ci))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()

**Comment by kenjis** [comment]
I recommend all of you don't use Session in Models.
Passing a value in the session to models is sufficient and better.

**Comment by skywizzy** [comment]
Yea learnt that the had way already, the problem is that CI3 doesn't flag
it as CI4 does

**Comment by agus-prawoto** [comment]
> 

I totally agree.
But in my opinion, sessions store global data, for example user data (after the user has successfully logged in), so if it is available globally it would be more beneficial, we can place it in BaseModel.php so we can access it from all models.
