### ISSUE TITLE
Question new form validation rule

### ISSUE THREAD

**Issue by Glennmen** [bcit-ci/CodeIgniter4#1332]
I got an idea for a new form validation rule that I believe a project like this must have if you see how the internet has evolved.
I was however wondering if all the code has to be in 1 function or can it be split up to keep it more clean and improve readability? Currently as far as I could see all other validation rules are compact and only require 1 function.

I would like to start working on it soon and submit a WIP PR so you guys could give feedback.

**Comment by jim-parry** [comment]
Without knowing anything about what you have in mind, it is impossible to answer your question.
New feature requests are usually discussed/debated on the forum, before raising an issue here or submitting a PR. Why not raise a thread there & explain what you ahe in mind?
