### ISSUE TITLE
redirect()-> problem

### ISSUE THREAD

**Issue by demortx** [bcit-ci/CodeIgniter4#1346]
if you simply write like this, then there will not be a redirect, it will exactly transmit the status 200 in the head of it

redirect()->to('http://you.com/',302);

But if forcibly set through exit (302)

redirect()->to('http://you.com/',302);
exit(302);
Works

Please note that the redirect inside the site is working properly!
redirect()->to('/panel',302, 'refresh');

**Comment by lonnieezell** [comment]
The docs were updated last night in the repo, though they haven't been pushed out yet. 

What you need to do is to `return redirect()`
