### ISSUE TITLE
URI Routing bug

### ISSUE THREAD

**Issue by demortx** [bcit-ci/CodeIgniter4#1354]
After the upgrade, it stopped working, $routes->post

Example if declared
$ routes-> add ('auth', 'Main :: index');
$ routes-> post ('auth', 'Main :: auth_post');

That post stops working, always redirects to 
$routes->add('auth', 'Main :: index');

ignoring
$routes->post('auth', 'Main :: auth_post');

**Comment by jim-parry** [comment]
This sounds like correct behavior to me.
Routing is based on first match, so your "post" rule will be not be used.
Try reversing the order of your rules.
See https://bcit-ci.github.io/CodeIgniter4/incoming/routing.html#resource-routes

This is a support question/problem, and should be raised on the forum, thanks.

**Comment by demortx** [comment]
the order has changed, the result has not changed, until the update worked properly, this is clearly an error

**Comment by jim-parry** [comment]
Ok - i will leave this one for Lonnie.

**Comment by demortx** [comment]
note that the url is the same, only the methods differ

**Comment by jim-parry** [comment]
You say "after the upgrade" ... what are you referring to?
The last change to Router/Router was in August, a month before alpha.1

**Comment by lonnieezell** [comment]
There was previously an error with correctly recognizing methods when an `add` function was used in combination with any of the other verbs (`get`, `put`, etc). When that was fixed, this should be working, but I'd be curious what change you are referring to also.

**Comment by jim-parry** [comment]
btw, a quick unit test case returns "index" as the method, regardless of the order, and with the route collections's verb set to 'post'.

**Comment by jim-parry** [comment]
I would guess PR1285 pn Oct 2nd, changed RouteCollection

**Comment by jim-parry** [comment]
/**
	 * @see https://github.com/bcit-ci/CodeIgniter4/issues/1354
	 */
	public function testRouteOrder()
	{
		$this->collection->setHTTPVerb('post');

		$this->collection->post('auth', 'Main::auth_post');
		$this->collection->add('auth', 'Main::index');

		$router = new Router($this->collection);

		$router->handle('auth');
		$this->assertEquals('\Main', $router->controllerName());
		$this->assertEquals('auth_post', $router->methodName());

	}

Adding the above to RouterTest, it fails, with the actual method returned "index".

**Comment by demortx** [comment]
https://github.com/bcit-ci/CodeIgniter4/commit/da43a39de5808eb5173b848de197afc57c944239

Rolled back this fix and it all worked.
$collection = array_merge($this->routes['*'], $this->routes[$verb]);

**Comment by lonnieezell** [comment]
I'm going to guess we need to swap the order of the values in the array_merge, but not sure when I'll have a chance to look at that currently. Work is keeping me going with long days. :(

**Comment by jim-parry** [comment]
Just merged a fix for this, fingers crossed. Passes both the tests from #1285 and the new one I added above.

**Comment by jim-parry** [comment]
@demortx Can you check if this fix works for you? Thanks.

**Comment by jim-parry** [comment]
I am interpreting the lack of response as being a thumbs up for the fix.
