### ISSUE TITLE
An error occurs in View Class

### ISSUE THREAD

**Issue by 46-96** [bcit-ci/CodeIgniter4#1358]
version 4.0 alpha-1
Using a monolog will cause an error.

CRITICAL: Argument 5 passed to CodeIgniter\View\View::__construct() must be an instance of CodeIgniter\Log\Logger or null, instance of App\Libraries\MyLogger given, called in /app/ci4/ci4/system/Config/Services.php on line 497

-use CodeIgniter\Log\Logger;
+use Psr\Log\LoggerInterface;

-public function __construct($config, string $viewPath = null, $loader = null, bool $debug = null, Logger $logger = null)
+public function __construct($config, string $viewPath = null, $loader = null, bool $debug = null, LoggerInterface $logger = null)

It worked correctly by changing like this.
Is it wrong?

**Comment by lonnieezell** [comment]
You're correct. That's how it should be. Care to submit a PR?

**Comment by bangbangda** [comment]
I fix it.
