### ISSUE TITLE
Error when trying access URI with Global Function's name

### ISSUE THREAD

**Issue by mixinix** [bcit-ci/CodeIgniter4#136]
I've found errors & blank pages when trying access URI with Global Function's name (testing as controller):

http://ci4.dev/[controller]

Displays an error page (Service Accessors):

http://ci4.dev/esc
http://ci4.dev/view
http://ci4.dev/helper
...

Displays a blank page (Miscellaneous Functions):

http://ci4.dev/is_cli
http://ci4.dev/redirect
...

PHP: 7.0.5 (x86)
ENVIRONMENT: development

**Comment by jim-parry** [comment]
Bugfix Checklist:

- [ ] Component(s) modified
- [ ] Unit testing updated
- [ ] User guide updated
- [ ] Securely signed commits
- [ ] Conforms to style guide
