### ISSUE TITLE
Support replacer functions on validations

### ISSUE THREAD

**Issue by iamdual** [bcit-ci/CodeIgniter4#1363]
In CodeIgniter 3, this was a feature. We could add replacer functions (such as trim and strtolower) to the validations as a rule. Will you support this?

Example:
required|min_length[3]|max_length[32]|is_unique[users.username]|**trim**|**strtolower**

**Comment by InsiteFX** [comment]
This should be asked in the CodeIgniter Forums not here, this is for reporting bugs only.

**Comment by jim-parry** [comment]
Those should already be usable with CI4's validation, as "callable" rules. I don't see that clearly explained in the user guide, though it seems to be alluded to in the last section on the page, as part of a "note".
Have you tried to use any of these? This could be a case that the user guide needs a better explanation, or that the native functions need better support.

**Comment by iamdual** [comment]
Yes, functions working on validations but the request output still same as user's request. CI3 do replace them. In CI4, I need to replace it again before adding to the database.

**Comment by lonnieezell** [comment]
Ah - well no, that was done on purpose. These rules are for validation, not sanitation. While it may have been a convenient thing, that is no longer possible in v.4. 

At least that was the original intent when I rewrote this library. That muddies that concerns, is an SRO violation and makes the code less clear about what is being done to what. Unless you really want this in here @jim-parry I vote to keep it out.

**Comment by jim-parry** [comment]
Makes sense. Developers can trim or convert case independent of validation.
I'm fine with not proceeding with this.
