### ISSUE TITLE
Spark error

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1408]
My home dir where spark is located is: /home/pc/mydir
I am in: /home/pc/mydir/tools where I am trying to call   ``` php ../spark report:file_converted 1 0 ``` . Hovewer everytime Im getting  error (never mind if spark is called from script or command line):

```
PHP Warning:  chdir(): No such file or directory (errno 2) in /home/pc/mydir/spark on line 43
PHP Warning:  require_once(/Config/Constants.php): failed to open stream: No such file or directory in /home/pc/mydir/system/bootstrap.php on line 98
PHP Fatal error:  require_once(): Failed opening required '/Config/Constants.php' (include_path='.:/usr/share/php') in /home/pc/mydir/system/bootstrap.php on line 98
```

Problem disappears when spark is called directly within its directory.

**Context**

PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by jim-parry** [comment]
spark is only intended to be run from inside the root directory of a project ... https://bcit-ci.github.io/CodeIgniter4/cli/cli_commands.html#running-commands

How is this a bug?

**Comment by jim-parry** [comment]
It seems to me that the docs clearly say that your usage would be "spark tools/report:file_converted 1 0", from the project root.
