### ISSUE TITLE
[i18n] Localization In Core

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#141]
CI should provide localization and internationalization as a core feature. My research on this is on-going so this list might evolve with time.
- [x] New config setting 'locale' that will be referenced site-wide, defaulting to 'en_US'
- [x] Should be able to change locale at runtime
- [x] New class for working with Date/Time
- [x] New class for working with Numbers
- [x] Be able to automatically set locale based on headers.
- [x] Date helper timezone features should use this
- [ ] ???A Model trait/class that adds features for helping managing translation tables for fields.

**Comment by davidgv88** [comment]
What do you think about the support .mo .po files. In older versions of CI always is through an array.

**Comment by sv3tli0** [comment]
It will be good to have multiple translation source formats possible, even if CI has 2-3 by default.

**Comment by davidgv88** [comment]
Yes! For example with this two Sources:
- Array (Default),
- Gettext

**Comment by davidgv88** [comment]
For more info: http://forum.codeigniter.com/thread-65550.html

I will write the proposal in Forum.

**Comment by johnnymast** [comment]
Interesting i will read into this maybe i could help

**Comment by baselbj** [comment]
I liked this and will ake some research on it. I think the best example on localization is the .net they did will in this part.

**Comment by lonnieezell** [comment]
I'm not familiar with how .net handles it, but am open to solutions. CakePHP does a pretty good job with it, too. Basically, it should get in your way as little as possible, and be integrated into the tools you would use even if you weren't doing any localized work. 

Just be sure to become familiar with what's already in the framework: 

- locale is being [set in the IncomingRequest class](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/HTTP/IncomingRequest.php#L164)
- the lang library already works with locale and the intl extension is used, though as pointed out in #448 there's work to be done there.
- default locale is [set in the App config file](https://github.com/bcit-ci/CodeIgniter4/blob/develop/application/Config/App.php#L66)

So, it's started, but has a few notable things that are left to do. Most of it will likely be centered around integrating the [intl extension](http://php.net/manual/en/book.intl.php) which has been bundled with PHP since 5.3.

**Comment by baselbj** [comment]
I will study it soon :)

**Comment by lonnieezell** [comment]
I think we have everything implemented for this now. Closing.
