### ISSUE TITLE
Use the update() in BaseBuilder method

### ISSUE THREAD

**Issue by bangbangda** [bcit-ci/CodeIgniter4#1414]
---
name: Bug report
about: Call the update method in the Model

---

**Describe the bug**
Controller file `$userModel->where(['uuid' => '20181106004'])->update(['user_name' => 'bangbangda']);`
Expect to call the update method of BaseBuilder. but executed the Model update method.
and an error will occur.

**CodeIgniter 4 version**
CodeIgniter 4.0.0 alpha.2

**Affected module(s)**
Model

**Repair plan**
Update line 1443 of /system/Model.php file:
`if ($name !== 'builder' && $result instanceof BaseBuilder)`
ok? 

**Context**
 - OS: [e.g. Mac os 10.14]
 - Web server [e.g. Apache 1.13.10]
 - PHP version [e.g. 7.2]

**Comment by lonnieezell** [comment]
That is the intended behavior. It allows query builder calls to modify the query before using the model calls. Perhaps it should be clarified in the user guide, but if you call that stuff on the model, and not on the query builder, you should expect model methods to be used.
