### ISSUE TITLE
Migrations.classNotFound

### ISSUE THREAD

**Issue by dasua** [bcit-ci/CodeIgniter4#1420]
---
name: Bug report
about: Help us improve the framework by reporting bugs!

---

**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**

**CodeIgniter 4 version**
4.0.0.alpha.2.
Installed via composer: composer create-project codeigniter4/framework:4.0.0.alpha.2

**Affected module(s)**
https://github.com/bcit-ci/CodeIgniter4/blob/067465790c81a09c35f655fa1b2eb6bee993294b/system/Commands/Database/CreateMigration.php#L168

**Expected behavior, and steps to reproduce if appropriate**
When create a new migration with command php spark migrate:create users asing $name = $sequence . '_' . $name.

This produces in the migration file a new class as:

class Migration_20181107002247_users extends Migration

When execute php spark migrate:latest get this error:

Migrations.toLatest

Migrations.classNotFound
/app/system/Database/MigrationRunner.php - 250

In MigrationRunner, line :248 fails loading $class because its value is **App\Database\Migrations\Migrations_users** when the classname generated was **App\Database\Migrations\Migration_20181107002247_users**.

**Context**
 - OS: [Linux Debian stretch]
 - Web server [e.g. Apache 1.2.4]
 - PHP version [e.g. 7.2.11]

**Comment by bangbangda** [comment]
Sorry.The bug I introduced.
