### ISSUE TITLE
Routes ending in '/' redirect oddly 

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#147]
Seems to be an .htaccess thing, but accessing /home/ (with trailing slash) redirects to /public/home.

**Comment by sv3tli0** [comment]
I am not quite sure if its related but I prefer not to open too many issues related to Routes bugs.

When I clone the project into new localhost subdir (http://localhost/citest) 
When I open the home page at `http://localhost/citest/public/` it works fine. 
How ever when I add `<?=current_url()?>` it outputs 'http://localhost/' only. 

What I found is that in this condition https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/HTTP/IncomingRequest.php#L489 
the query path is substr from the uri. 
I think that there is some logical mistake. If I just remove this condition the how app stops working so it needs some closer look ..

**Comment by lonnieezell** [comment]
Testing again on my machine tonight, and, yes, this seems to be fixed.
