### ISSUE TITLE
Error in session FileHandler and BaseHandler

### ISSUE THREAD

**Issue by arma7x** [bcit-ci/CodeIgniter4#152]
1) Constructor should override parent for passing config https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Session/Handlers/FileHandler.php#L80:
 parent::__construct($config);
2) Typo in https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Session/Handlers/BaseHandler.php#L118 
 $this->cookieDomain = $config->**cookoie**Domain;

**Comment by ridho1991** [comment]
I fixed $config->**cookoie**Domain, and pull request #153 submitted. I hope it merged soon. thx

**Comment by lonnieezell** [comment]
Thanks!
