### ISSUE TITLE
“&get_instance()” in the Ci3 how to use it?

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter4#166]
CI3: &get_instance()
How to use it？

**Comment by lonnieezell** [comment]
You realize you're posting in CI4, right? 

If so, then I assume you're asking if CI4 has the equivalent of get_instance(), and the answer is no. There is no singleton object anywhere.

Please note that the Issues here are for bug reports and for CI4 planning. Questions about how to use the framework should be handled on [the forums](http://forum.codeigniter.com/);
