### ISSUE TITLE
Form Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#174]
More information will be added later, but I needed to brain dump this before I forgot. :)

Basically porting the existing form helper library with the following additions:
- [ ] Must support ALL HTML5 form field types
- [ ] Must handle auto-escaping of output correctly, and this will get tricky since some places (like attributes or urls may have to be escaped multiple times with different contexts (html, url, etc) in order to be correct. More info on the reasoning behind this can be found in [this blog post](http://blog.astrumfutura.com/2012/06/automatic-output-escaping-in-php-and-the-real-future-of-preventing-cross-site-scripting-xss/). 

EDIT: The second item is probably more targeted at an HTML builder...

**Comment by lonnieezell** [comment]
This one probably makes more sense to implement as a class.

**Comment by Portaflex** [comment]
A couple of questions:
- Does make sense to have a Form library folder with, say, Form class as the main class with static functions to "draw" forms, and a FormValidation class to validate forms, and a HtmlBuilder class that escapes outputs?
- That new HtmlBuilder has to do with htmlspecialchars?
- Do we need to type hint functions in all those classes? I make this question because, for instance, functions in Database class are not type hinted.
Thanks.

**Comment by lonnieezell** [comment]
FormValidation would definitely be separate class. And the HTML helper mainly makes creating lists easier. 

The Form library still needs to handle escaping the output since it automatically fills fields back based on direct user input. We wouldn't use just htmlspecialchars. Instead, we'd be using the [esc()](https://bcit-ci.github.io/CodeIgniter4/general/common_functions.html#esc) function. This would need to escape both the field value (in the html context) and any field attributes (with the 'attr' context). The form_open() equivalent would have to escape the URL as both a 'url' and 'html', in that order, I believe. That's one thing I need to look up more about, since I know that you should escape for all of the relevant contexts but not sure if order matters. Oh - and I guess that means that attr should also be escaped as 'html'? Yeah, need more research. :)

My original comment of the form being a class might not work out, actually. The thought was that it would be nice to not have to load the library and simply have it work by using `Form::open()` in the view, but was just thinking about that and it would end up being ugly because of the namespacing. I don't think doing a 'use' in the controller would carry over to the view.... so maybe keeping it as functions is fine here. 

Functions in Database class are probably not type-hinted only because it was primarily a port job and I haven't gone back to do that. :) Though some refuse to be typed since they accept multiple types of input (either an array or string). But, yes, we should be using type-hinting wherever we can. It keeps less errors hidden from the developer, and helps make both the code and the tests a little clearer.

**Comment by Portaflex** [comment]
Added some files in orther to get form_helper and FormValidation. Just a port from CI3, not finished.
