### ISSUE TITLE
Honeypot Filter

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#176]
Something like: https://github.com/CHH/stack-honeypot

**Comment by arma7x** [comment]
How about this implementation http://forum.codeigniter.com/thread-63141.html?highlight=honeypot

**Comment by InsiteFX** [comment]
We do not need to start bloating CI4 with third party add-on stuff.

**Comment by lonnieezell** [comment]
My thought was that this would replace the ineffective CAPTCHA system we have with something that, as far as I know, is still seen as being fairly effective at stopping bots. And, with filters now in the system, it can be automated so the user never has to think about it.

**Comment by arma7x** [comment]
Nice explanation here https://www.smartfile.com/blog/captchas-dont-work-how-to-trick-spam-bots-with-a-smarter-honey-pot/

**Comment by aanbar** [comment]
As I understand this cannot replace captcha; this is a method to protected against general purpose spam bots  & won't be effective if the bot was written for a specific site.

Anyway, I don't like the idea of having useless form fields in every single form I have so adding it automatically & checking for it automatically may not be convenient for everybody.

**How it works:**
* You create a div & add an empty text field and add a class to hide that form field from normal users.
* You check that the honeypot field which is required to be empty is actually empty upon form submission.

If I understand how it works correctly then here's my suggestion on how to implement this:

* Add a function in form_helper -- form_honeypot(string $name)
* either add a function in form_helper like check_honeypot(string $name): bool which returns boolean true when empty or false when it's filled & let the user handle it inside controller
* Or add a validation rule in form_validation like 'honeypot_field' which would give a generic error message like (Failed to validate form) without giving hints on what's wrong

We might have both options implemented & let the user chose what he wants.
This require adding a user guide on how to use this

**Comment by lonnieezell** [comment]
> Anyway, I don't like the idea of having useless form fields in every single form I have so adding it automatically & checking for it automatically may not be convenient for everybody.

Which is why it would be setup as a filter that users could decide to use or not. 

You're how it works section describes the original version. Improvements have been made to the theories that improve it's effectiveness, including randomizing where in the form it's placed, taking the name of an existing form-field, hashing the other on the form, and then putting them back on the way back in, time restrictions, etc. With the newer methods, they seem to be better than many, if not most, captcha's, and leaps above what CI3 provides. 

But the newer methods also work best as a filter/middleware so that it can analyze the built form during output and insert/modify the field names, etc, and then put things back and do it's check on the way in.

**Comment by ranjithsiji** [comment]
This is a fantastic feature. A must to be included in Codeigniter. Better than CSRF I think. 👍

**Comment by dvdnwoke** [comment]
The theory i have is adding it as middleware, so that on every request the honeypot field can be checked and redirected to blank page if the fields is not empty and possibility to randomize the field names.

**Comment by lonnieezell** [comment]
@dvdnwoke That's exactly correct. Though CI4 doesn't have "middleware" by that name. You would use [Controller Filters](https://bcit-ci.github.io/CodeIgniter4/general/filters.html) the same way.

**Comment by dvdnwoke** [comment]
Ok I will implement it over the weekend

**Comment by lonnieezell** [comment]
Great. I look forward to it!

**Comment by dvdnwoke** [comment]
This is what i was able to come up with any **suggestion** or **improvement** before sending it as pull request
`<?php namespace App\Filters;

use CodeIgniter\Filters\FilterInterface;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;

class Honeypot implements FilterInterface {

    /**
	 * Checks if Honeypot field is empty, if so
     * then the requester is a bot,show a blank
     * page
	 *
	 * @param RequestInterface|\CodeIgniter\HTTP\IncomingRequest $request
	 *
	 * @return mixed
	 */

    public function before (RequestInterface $request) {

        // Will there be need to protect against bad data
        if($request->getVar('honeypot')){
            die();
            //Is Redirection needed
        }

        
    }

    /**
	 * Checks if Honeypot field is empty, if so
     * then the requester is a bot,show a blank
     * page
	 *
	 * @param RequestInterface|\CodeIgniter\HTTP\IncomingRequest $request
	 * @param ResponseInterface|\CodeIgniter\HTTP\Response $response
	 * @return mixed
	 */

    public function after (RequestInterface $request, ResponseInterface $response) {
        
        $prep_field = '
            <div class="hidden" style="display:none">
                <label>Fill This Trap</label>
                <input type="hidden" name="honeypot" value=""/>
            </div>
            </form>';
        
        $body = $response->getBody();
        $body = preg_replace('/<\/form>/', $prep_field, $body);
        $response->setBody($body);
    }
}
`

**Comment by lonnieezell** [comment]
@dvdnwoke That's a good start. Here's a few comments: 

- make the name, label, etc set through a config file so users can easily change it per app. [See this class](https://github.com/CHH/stack-honeypot). Oh - and make the base HTML part a template string that can be defined in the config file, also, so user can make it look structurally like the rest of their site if they need to.
- move the logic to a new class. A simple implementation like you've started here is fine, but somewhere down the road we'll want to make it more robust and more effective. [Good ideas here](https://www.smartfile.com/blog/captchas-dont-work-how-to-trick-spam-bots-with-a-smarter-honey-pot/).
- don't forget docs and tests. :) 

Then go ahead an submit a PR and we can go from there. 

Thanks!
