### ISSUE TITLE
View: saveData

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#181]
Shouldn't the View::render() $saveData parameter default to true?
$options / $saveData is not used (per phpdocs) and is not in the user guide, which means that $data will be cleared on rendering the way it sits, and that view parameters cannot be passed to successive views.

**Comment by lonnieezell** [comment]
There was a discussion about this early on and the thought was that people should explicitly pass the data from one view to the next. So, while the data isn't automatically passed through, you'd just have to build the (smaller) data array to pass to it. The idea was that it created potentially unintended consequences for those not expecting it. I know Andrey was in on that conversation and I don't recall and it appears to have been a discussion thread on a commit, not an issue, so it's not easily findable. 

I know that us CI "old-timers" are used to it working the other way, though.

**Comment by jim-parry** [comment]
Ok - that one (amongst others) slipped by me. 
The code will produce unintended consequences as it stands, because the behavior differs from CI3 even though the signature looks the same ... the data parameters are being deleted automatically.
I will enhance the user guide writeup to address this :-/
