### ISSUE TITLE
Mess Detector rules

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#184]
Looking for someone familiar with [Mess Detector](https://phpmd.org/) to create a ruleset matching our style guide, or the common deviations from it or other bad smells.
This is initially intended for use inside an IDE, and ultimately perhaps as part of our travis-ci build.

**Comment by cryode** [comment]
Suggest possibly using [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to help with formatting code automatically, on top of or in lieu of mess detector.

**Comment by jim-parry** [comment]
That is a possibility. I am trying to cover all the bases, and hope that we get one that works.

The three suggested are the ones supported by my IDE, apparently for different purposes.

If a single tool would do the trick - detecing, reporting and fixing, both inside an IDE and as part of travis-ci, that would be good.


________________________________

**Comment by mwhitneysdsu** [comment]
Out of curiosity, I installed Mess Detector and ran it on selected classes in my CI3 codebase. The information it provides is very different from PHP-CS. I think there's a remote possibility that you could write rules for PHP-CS to do the same thing, but it would seem like an odd thing to spend your time on, given that MD works, and you would probably take a less automated approach to dealing with MD results.

**Comment by jim-parry** [comment]
It looks like the traction is with the code sniffer and not the mess detector.
Putting this one to sleep :-/
