### ISSUE TITLE
Paginating Multiple Results - user Guides

### ISSUE THREAD

**Issue by titounnes** [bcit-ci/CodeIgniter4#196]
// In the Controller
public function index()
{
    $userModel = new \App\Models\UserModel();
    $pageModel = new \App\Models\PageModel();

    $data = [
        'users' => $userModel->paginate(10, 'group1'),
        'pages' => $pageModel->paginate(15, 'group2'),
        'pager' => $model->pager
    ];

    echo view('users/index', $data);
}

// In the views:
<?= $pager->links('group1') ?>
<?= $pager->simpleLinks('group2') ?>

We have 2 models, $userModel and $page model. $model in data-pager not exists in this method

**Comment by sv3tli0** [comment]
It will be good to move that to the Forum..
If you have some problems that doesn't 100% means that there is a bug to be reported..

**Comment by titounnes** [comment]
This not a bug. I comment user guides in https://github.com/bcit-ci/CodeIgniter4/blob/develop/user_guide_src/source/libraries/pagination.rst. There is a mismatch between the model loaded with passed to view.

**Comment by lonnieezell** [comment]
Good catch. Darn copy/paste :) Thanks! I'll get that fixed up tonight.
