### ISSUE TITLE
Cookie Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#205]
I can see these being handy at times, though in controllers you can now use `$request->getCookie()` and `$response->setCookie()` so this might not be needed, honestly. However, for now we'll keep it in place. 

Basically a straight port, setup to use our new features and styles.

Development Checklist:

- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by prezire** [comment]
I can work on this as it needs prefixing from Config/App.

**Comment by prezire** [comment]
If I remember correctly, helpers were created mostly for View purposes. Perhaps this is useful on the UI side wherein there's no need to create variables from the controller thus, removing the tedious part. Meanwhile, are we missing Response::getCookie() method? CI3 has the implicit Input::cookie(), however I prefer the explicit Response::getCookie() to compensate for Response::setCookie().

**Comment by prezire** [comment]
In addition, I wonder if "headers already sent exception" has been solved for unit tests? I'm not thoroughly familiar with any concrete solutions to test cookies with this.

**Comment by prezire** [comment]
Cancel Response::getCookie(). Perhaps I can find a workaround via IncomingRequest::getCookie().

**Comment by lonnieezell** [comment]
>  I wonder if "headers already sent exception" for unit tests has been solved? I'm not thoroughly familiar with any concrete solutions to test cookies with this.

I doubt it. Someone had started refactoring some stuff for us but I don't think we got that far into our additional testing features. 

> Cancel Response::getCookie(). Perhaps I can find a workaround via IncomingRequest::getCookie()

Correct, cookies are read from the Request and written to the Response, as per HTTP specs. 

This shouldn't need anything fancy, though, grab the request or response object from `\Config\Services::request()` and `\Config\Services::response()`, and let that handle it.

**Comment by prezire** [comment]
Nice. Was looking for these two. I'll start focusing on Services class for future implementations. I'll also submit a PR for this helper in a couple of hours.

**Comment by lonnieezell** [comment]
Completed in #241
