### ISSUE TITLE
FileSystem "Helper"

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#207]
This is a class-based replacement for the directory, path, and file helpers. It seems logical that we could provide a class or two that allows you to represent the filesystem or get the details of it. 

However, once we head down this road, it starts to take us down the logical path that [FlySystem](http://flysystem.thephpleague.com/) already solves. 

Hmm... will discuss this one on the forums.

**Comment by Portaflex** [comment]
I would say that as for the local filesystem we are done with our current helpers:

> file_helper
> directory_helper
> path_helper

I would merge all three in one: fliesystem_helper. For further complication we can use FlySystem anytime.

**Comment by Portaflex** [comment]
#259
