### ISSUE TITLE
Inflector Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#210]
Port the existing helper over.

Development Checklist:

- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by prezire** [comment]
May I know if we can add a few more functions from the new Helpers?Or, should we just stick to the ones from CI3? A couple of additional functions similar to RoR might be useful http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html.

**Comment by prezire** [comment]
Furthermore, adding datatypes to the user guide / reference is very helpful in providing quick glances to the method signatures. PHP does the same thing as well http://icecream.me/44998e053b59b2bbf505c86ded89afee.

**Comment by lonnieezell** [comment]
Good point about adding type hints there. Definitely something we should be doing.  As for the other helper methods, I'm ok with some of them: 

- `dasherize` - yes.
- `upcase_first` - not needed since PHP has the native `ucfirst` which does the same thing (with less typing and faster)
-`humanize` we already have. Though if you want to flesh the existing function out to be more in line with the additional processing they do, I'm cool with that. 
- `ordinalize` - yes
- `ordinal` - yes
- `classify` - don't think this one's necessary. We don't have any defined conventions on class naming that we need to provide this special case for.

**Comment by markaatdemochimp** [comment]
Datatypes in user documentation is good but I've reverted it for now until fully approved / decided. Thanks for highlighting out the items. I'll continue with the remaining ones.

**Comment by prezire** [comment]
Datatypes in user documentation is good but I've reverted it for now until fully approved / decided. Thanks for highlighting out the items. I'll continue with the remaining ones.

**Comment by prezire** [comment]
Probably best to remove this from the list before someone starts to works on it too.
