### ISSUE TITLE
Text Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#211]
Port existing string helper over, remove deprecated methods/features. Combine with the Text Helper features. Add: 
- <del>auto_link_email</del>
- <del>auto_link_url</del>
- excerpt - see [Cake's function](http://book.cakephp.org/2.0/en/core-libraries/helpers/text.html#TextHelper::excerpt)

**Comment by Portaflex** [comment]
We have auto_link() (e-mail and url) in url_helper.php. Except for "www" and "://" patterns, what is the difference between them? Thanks.

**Comment by lonnieezell** [comment]
Doh! You're right. We don't need those in here. Thanks for pointing it out!

**Comment by Portaflex** [comment]
My pleasure!!
Lets get CI4 working soon!!
:-)

**Comment by lonnieezell** [comment]
> Lets get CI4 working soon!!

Trust me. I would love to! It's been sooo many hours of my free time spent working on this over the last - what? - 10 months or so? Yeah, I'm ready to have a release, but still a ways to go...

**Comment by mixinix** [comment]
CI4 "enthusiast" here. I feel someone is missing.. :)

**Comment by Portaflex** [comment]
Added new pull request with your guidelines. Hope it helps ...
