### ISSUE TITLE
Number Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#212]
Port the existing number helper over. With additional methods: 
- currency : works with locales to display numeric values in a specific currency with proper separator formatting, etc. 
- I like Cake's naming for: along the lines of `to_Readable_size()` with a new companion function `from_readable_size()`

Development Checklist:
- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by prezire** [comment]
Most helpers have existing classes found in the system core, which can be reused. Can we use the same approach for helpers such as this, that don't have one? In turn, it will make helpers easy to manage while providing more methods that didn't exist in CI3. Let me know if you're open to the ideas below:

//number_to_byte() //Taken from CI3's byte_format().
//number_from_byte()
number_to_amount(1000000000000000000000000); //Returns 1 Septillion.
//number_with_delimiter()
//number_to_distance()
//number_to_currency()
//number_to_percentage()
//number_to_weight()

**Comment by lonnieezell** [comment]
Additional classes don't make sense for every case, like the number helper. I can't see a reason to include a new class and interface for standalone functions. That increases the mental overhead of maintaining the framework without providing any benefit. If someone wants to extend these helpers, they can use their own helper class and just load it with a namespace. 

You're going to have to provide more explanation on what those different helpers would do before we could say or nay. Most of them are not apparent to me what they'd do.

**Comment by prezire** [comment]
Yep no worries. Let's not do that.

**Comment by Portaflex** [comment]
We've got a fair amount of php native number formatting functions. How many and which of them to use in the helper?

**Comment by lonnieezell** [comment]
@prezire Working on several of your method ideas for this now. See #299

**Comment by prezire** [comment]
Nice. I'll do my best to push within the next 2 days as well in case some things were left out.
