### ISSUE TITLE
Typography Helper

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#214]
Port the existing helper over.

Development Checklist:

- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by Portaflex** [comment]
In CI3 we have Typography Helper and Typography Library. The helper just loads the library for two of its functions and Security Class for entity_decode function.

Would it make sense to merge helper and library and have just a Typography class (library) with static methods, no helper needed?

**Comment by Portaflex** [comment]
Initial pull request made. Don't know how to create tests. :-(

**Comment by lonnieezell** [comment]
Sorry. Just now getting a chance to look at this. My initial reaction was a No to static methods, but your pull request doesn't use any, so that's all good. :)

I'll make some comments on that PR, since there's some formatting and style issues that need to be corrected, etc. 

[This article at SitePoint](https://www.sitepoint.com/getting-started-with-phpunit/) goes over the basics of using PHPUnit so that should get you started. Didn't you work with tests on the previous PR you made? Between that article and the existing tests, that should get you going, but don't hesitate to ask questions if you're unsure of something. I'll help you through it, but I'd really like to see tests with your PR's.
