### ISSUE TITLE
Error DotEnv.php on line 121

### ISSUE THREAD

**Issue by wolfgang1983** [bcit-ci/CodeIgniter4#216]
When I installed this version of CI got error. 

Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\project-codeigniter4\system\Config\DotEnv.php on line 121

**Comment by lonnieezell** [comment]
It sounds like you're not using PHP 7+. Can you confirm the version of PHP you're using?

**Comment by wolfgang1983** [comment]
You were right. I had to uninstall my old version of xampp which did not have the php 7 the one before that. On a note I love the home page and the debug bar.  You can close the issue now.
