### ISSUE TITLE
3.1.0 Email Library Corrupting PDF Attachments

### ISSUE THREAD

**Issue by SyntaxSniffer** [bcit-ci/CodeIgniter4#220]
When attaching MPDF generated PDF's to an email in 3.1.0 the header for the pdf file itself is modified and the beginning of the file is truncated.

I am attaching a screenshot to show what I mean.

Reverting only the email library file back to 3.0.6 in the system folder resolves the issue.

![3 1 0](https://cloud.githubusercontent.com/assets/2049188/17409051/88c90652-5a3b-11e6-9ab1-e9eed8b72f61.PNG)
![3 0 6](https://cloud.githubusercontent.com/assets/2049188/17409052/88ceec20-5a3b-11e6-89b7-e5ad5e75a59b.PNG)

**Comment by lonnieezell** [comment]
You've posted this in the wrong repo. :( This is the CodeIgniter 4 repo, which doesn't contain any email code yet. You want the [main CI repo](https://github.com/bcit-ci/CodeIgniter).
