### ISSUE TITLE
standardize comments

### ISSUE THREAD

**Issue by juanlopezdev** [bcit-ci/CodeIgniter4#234]
Hello, 
I really like IQ , but I have a problem with PHP comments , personally I think it is not standardized. They have a style guide for CI http://www.codeigniter.com/user_guide/general/styleguide.html#commenting and it would be advisable also to apply in developing CI4. 

In my personal opinion I think that the comments of this type would have to be reserved for variables , classes, methods or functions.

``` php
/**
 *
 */
```

And this, for any block you want to comment

``` php
// I'm a PHP comment
```

I also believe that you should avoid these types of comments :

``` php
// ---------------------------------------------
```

Currently I see this file a bit messy in a review for example.
https://github.com/bcit-ci/CodeIgniter4/blob/develop/application/Config/Routes.php

Greetings, thank you very much for giving a new version CI4

**Comment by InsiteFX** [comment]
`<?php
// This is a single-line comment

# This is also a single-line comment

/*
This is a multiple-lines comment block
that spans over multiple
lines
*/

// You can also use comments to leave out parts of a code line
$x = 5 /* + 15 */ + 5;
echo $x;
?>`

**Comment by lonnieezell** [comment]
@InsiteFX I have no idea what you're trying to say here.... 

@juanlopezdev I agree to some extent that we probably need to clean things up a little bit, but don't necessarily agree with all of your examples. 

Will leave this one open for now as a reminder to go back and clean up a bit.

**Comment by InsiteFX** [comment]
I was just showing how php.net says the standard comments should be like.
