### ISSUE TITLE
The Hooks feature does not work

### ISSUE THREAD

**Issue by jk1860** [bcit-ci/CodeIgniter4#248]
I wrote the Hooks::on() function in the application/Config/Hooks.php file , and I trigger the Hooks In the Home controller file(application/Controllers/Home.php) , but the hook does not work.

here is my code in the application/Config/Hooks.php file 
`Hooks::on('myhook',function(){
	echo 'hello this is Hooks';
});`

here is my code in the application/Controllers/Home.php file

`public function index()
	{
		\CodeIgniter\Hooks\Hooks::trigger('myhook');
		return view('welcome_message');
	}`
is there anything wrong with my way of using hooks or  should I load the application/Config/Hooks.php file first somewhere?

**Comment by lonnieezell** [comment]
Oops! You're right. Fixed in f71364505d3afaf3fa7cd72c5fc36b00a485f429
