### ISSUE TITLE
ErrorException when Connecting to Multiple Databases

### ISSUE THREAD

**Issue by mithaaprilia** [bcit-ci/CodeIgniter4#255]
I have two databases, and try to make multiple connections like this:
$blogDbUsers = \Config\Database::connect('users');
$blogDbBlogs = \Config\Database::connect('blogs');

Then, I got problem like this:
ErrorException
Trying to get property of non-object
BASEPATH/Database\MySQLi\Connection.php at line 280

**Comment by lonnieezell** [comment]
Just to confirm: `users` and `blogs` are separate **databases**, not **tables**, right? 

It sounds like they would be tables. In which case, you only need the one connection.

**Comment by mithaaprilia** [comment]
Yes, they are separate **databases**.
I know they look like tables, but they are two different databases.

**Comment by lonnieezell** [comment]
Please ensure that both of your database connections are setup properly in Config\Database. I just tried locally and it worked. 

```
$db1 = \Config\Database::connect('default');
$db2 = \Config\Database::connect('tests');

d($db1->listTables());
d($db2->listTables());
```

**Comment by mithaaprilia** [comment]
That's works. I tested it. However I got that error when I load the view. 
I can't see the the error details on that page, but I can see in view source like [this](http://pasted.co/52eb69a6)

I see the backtrace:
ErrorException
Trying to get property of non-object
BASEPATH/Database\MySQLi\Connection.php at line 280

BASEPATH/Debug\Toolbar\Collectors\Database.php : 152							
On method CodeIgniter\Database\MySQLi\Connection->getVersion		

BASEPATH/Debug\Toolbar\View\toolbar.tpl.php : 49							
On method CodeIgniter\Debug\Toolbar\Collectors\Database->display	

APPPATH/Filters\DebugToolbar.php : 47							
On method CodeIgniter\Debug\Toolbar->run

The problem is on that lines I guest.

**Comment by lonnieezell** [comment]
Thanks for pointing me in the right direction. The error happened because no queries had been run so far, so the database connection had not actually been initialized. So, it couldn't grab the version of the database when trying to display it in the toolbar.  Fix to follow.

**Comment by mithaaprilia** [comment]
You're welcome :-)
