### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter4#273]
$builder = $db->table('mytable');
$builder->set('field', 'field+1', FALSE);
$builder->where('id', 2);
$builder->update(); // gives UPDATE mytable SET field = field+1 WHERE id = 2

($builder->set('field', 'field+1', FALSE);)  this is bug !!!!

error:  UPDATE `mytable` SET field = 'field+1' WHERE `id` = 2

**Comment by lonnieezell** [comment]
Yeah, those situations have always been painful for CI's Query Builder IIRC. I got to where I was writing those queries manually. 

However, there's new [increment()](https://bcit-ci.github.io/CodeIgniter4/database/query_builder.html#CodeIgniterDatabaseBaseBuilder::increment) and `decrement()` methods in Query Builder you can use instead: 

```
$db->table('mytable')
    ->where('id', 2)
    ->increment('field', 1);
```

Note that these do run the query right then, though...
