### ISSUE TITLE
controller routing

### ISSUE THREAD

**Issue by maczdata** [bcit-ci/CodeIgniter4#284]
Please how do I route a controller in a subdirectory

**Comment by DavisMiculis** [comment]
This is only for issue and bug tracking. Please use CodeIgniter Forums for help - http://forum.codeigniter.com/

And you can easily find your answer in the documentation - http://bcit-ci.github.io/CodeIgniter4/general/controllers.html#organizing-your-controllers-into-sub-directories

**Comment by maczdata** [comment]
OK 10ks
