### ISSUE TITLE
Igniter 4 services

### ISSUE THREAD

**Issue by maczdata** [bcit-ci/CodeIgniter4#287]
Good day, i believe the codeigniter 4 services class is similar to laravel service provider!!
i just wanna suggest that shouldn't the services be broken in a service folder cus if codeigniter is been used to develop a large project, the long line of code in the single services file would be stressful to scroll

**Comment by lonnieezell** [comment]
At it's core they provide a similar function, but our Services layer is a very much simplified solution, on purpose. 

While I understand your concern, there are drawbacks to splitting them up, not the least of being an additional performance hit to load additional files and, I assume, instantiate additional classes? Also, how would those files be organized? The way that would make the most sense would be to have a single file per service, but that's overkill, and I'm fighting a losing performance battle already. :) 

I'm not sure what editor you use, but I believe most of them have ways to make this easier. For example, in PHPStorm that I use it can a) show a list of the methods in the class on the side for quick navigation, and b) there's a shortcut key that can locate any method in the project very quickly. If you know what you're looking for, you can simply search on the page. So, while none of those are direct solutions to your concern, those types of features can definitely help out with large files like that. 

And, honestly, I don't think this is a file you'll really spend a lot of time in.

**Comment by maczdata** [comment]
OK I actually use sublime text. I do understand your response. I just raised the issue for flexibility reasons. Cus I the scrolling down of long code aches the eyes and hand.
