### ISSUE TITLE
Separated services default with trait

### ISSUE THREAD

**Issue by mixinix** [bcit-ci/CodeIgniter4#292]
Custom config services:

```
<?php namespace Config;

class Services
{
	use \CodeIgniter\Services;

	public static function myCustom($getShared = true)
	{
		if ($getShared)
		{
			return self::getSharedInstance('autoloader');
		}

		return new App\Libraries\MyCustom();
	}

}
```
Default CodeIgniter:

```
<?php namespace CodeIgniter;

trait Services
{
	static protected $instances = [];

	// More CodeIgniter default config services...

	protected static function getSharedInstance(string $key, ...$params)
	{
		if (! isset(static::$instances[$key]))
		{
			// Make sure $getShared is false
			array_push($params, false);

			static::$instances[$key] = self::$key(...$params);
		}

		return static::$instances[$key];
	}

	public static function __callStatic(string $name, array $arguments)
	{
		$name = strtolower($name);

		if (method_exists(__CLASS__, $name))
		{
			return Services::$name(...$arguments);
		}
	}
}
```

I think that is very clean. What do you think, Sir?

**Comment by lonnieezell** [comment]
I think you're right, it is clean. I don't think clean always equates to the best usability. And I also think this is the wrong use of a trait. 

That said, this has been brought up by 3 people now. Here's my pros and cons on this: 

- if a developer needs to see what's going on, or modify an existing service, having them all in the application is handy, no other searching needed.
- Every extra file loaded is a slight performance hit, though the last few versions of PHP have mitigated this some with a pretty good realpath cache system
- I think that everyone that has brought the issue up so far is working on a project with a framework that is in very early alpha, under constant development, and is constantly changing and they are hitting pains when something is added to Services file. :) Once the framework is actually released, these changes will be few and far between. 
- And the plus side, doing a change like this would help make upgrades simpler, so it's entirely possible this will happen.

**Comment by mixinix** [comment]
Maybe like this:

```
.. application/
.. .. Config/
.. .. .. Services/
.. .. .. Services.php {custom}
.. .. .. ServicesTrait.php {default}
```

Or maybe I'm wrong. I can create custom service class like that. And then, make (service_extra or  shared_extra) helper for simplicity.

I think I'm agree with you with poin no. 1, 2, & 3.

Actually I don't like trait(s). :)

**Comment by lonnieezell** [comment]
> Actually I don't like use trait(s). :)

Then we don't use them :) If we decide to do something like this we'd just create a new `CodeIgniter\Config\Services` which would be what we have now, and then extend that class in `Config\Services`

**Comment by jim-parry** [comment]
+1 to your idea, Lonnie. That would solve some of the upgrading issues when application changes.

**Comment by lonnieezell** [comment]
@jim-parry cool, we'll go that route, then.
