### ISSUE TITLE
getSharedInstance doesn't work on costum services

### ISSUE THREAD

**Issue by mithaaprilia** [bcit-ci/CodeIgniter4#294]
I have custom service:

public static function loggedinuser($getShared = true)
    {
        if ($getShared)
        {
            return self::getSharedInstance('loggedinuser');
        }
        return (new UsersModel())->getUserById(session('user_id'));
    }

if I call it with $getShared = true, It doesn't work, show NULL with var_dump, if $getShared = false, It works, show the data.

However. I make sure that getSharedInstance doesn't work on custom services, by moving that function into \system\Config\Services.php. The result, that function works well with $getShared = true.

**Comment by ridho1991** [comment]
Hmm. I think the problem is parent class can't call child class method. getSharedInstance() can't call loggedinuser()

**Comment by lonnieezell** [comment]
A couple of things;

First - these boards are not intended to be used to advice or problem solving. They are for feature planning and bugs. 

Second - don't use a service for that. Just create a User class and instantiate that when you need it.
