### ISSUE TITLE
Now ci4 product development can be used? Or how long before they can be released? Very much looking forward

### ISSUE THREAD

**Issue by yuchonghua** [bcit-ci/CodeIgniter4#311]
Now ci4 product development can be used? Or how long before they can be released? Very much looking forward

**Comment by lonnieezell** [comment]
Glad to hear you're excited about CI4! But....It is not recommended to use it in production as it's still very much under development and in an Alpha state with portions that are not finished yet. We don't have an exact time frame for release, but my guess is early Spring.

**Comment by yuchonghua** [comment]
If used for project development, is not the latter part of the impact will not have api changes

**Comment by yuchonghua** [comment]
Now is the end of the three stages of ci in the first few stages of it

**Comment by lonnieezell** [comment]
I cannot say whether there will be API changes or not. But there are surely security issues and bugs...

**Comment by yuchonghua** [comment]
When is it expected to release? Can be released in January next year

**Comment by lonnieezell** [comment]
Probably longer than that. I wouldn't start a new project on it, personally.

**Comment by yuchonghua** [comment]
Can I take part in the development of Ci

**Comment by lonnieezell** [comment]
It's an open source project, so absolutely. Make sure to read the [Contributing to CodeIgniter](https://bcit-ci.github.io/CodeIgniter4/contributing/index.html) section of the user guide first. And take time to get familiar with the new code. Then look for topics that have the label "help wanted" and start pitching in.

**Comment by yuchonghua** [comment]
CodeIgniter4 Roadmap - Phase 2 When can I expect to finish?

**Comment by jim-parry** [comment]
@yuchonghua This is a forum topic, NOT a github issue.
