### ISSUE TITLE
view_cell optional variables array_key_exists null fix.

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#317]
Hi everyone,

array_key_exists() expects parameter 2 to be array, null given errors in fixed.
$cell_data = [];
if($test_data !== NULL) { // optional cell datas
	$cell_data[‘test’] = $test_data;
}
view_cell(‘test’, $cell_data);

Fix commit : https://github.com/byazrail/CodeIgniter4/commit/6816f1238a17f7eb5de18fd17c493cb4c25b64ca

**Comment by lonnieezell** [comment]
Fixed with 6864e6f2be7507a7f5fdbc38043a1a7c9ce84351
