### ISSUE TITLE
RedisHandler, Session regenerate id problem

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#318]
Hi all,

session_regenerate_id(): Failed to create(read) session ID: user (path: /var/lib/php/session)
on redis driver.

---
Handler;
If you need it, see : [Handler](https://github.com/byazrail/CodeIgniter4/blob/develop/system/Session/Handlers/RedisHandler.php)
Fix;
If you need it, see : https://github.com/byazrail/CodeIgniter4/commit/f21a857c5d4e2c72432256fde372db715bd98b99

**Comment by byazrail** [comment]
Hi all,

Handler;
If you need it, see : [Handler](https://github.com/byazrail/CodeIgniter4/blob/develop/system/Session/Handlers/RedisHandler.php)
Fix;
If you need it, see : https://github.com/byazrail/CodeIgniter4/commit/f21a857c5d4e2c72432256fde372db715bd98b99

**Comment by lonnieezell** [comment]
Thanks for digging into this! Really appreciate it. In the future, a pull request would be simpler to handle here, though, if you can. Will try to get this incorporated tonight.

**Comment by byazrail** [comment]
You are very welcome. I'm working on it. Let's see.

**Comment by byazrail** [comment]
I'm working on the Oci8 Database Connection Driver.
As soon as posible i ll check test then i will return test results.
Dev see - https://github.com/byazrail/CodeIgniter4/commit/ded36bb93ad56633c848c31906def7a6c33cb166
![screen shot 2016-12-01 at 00 34 26](https://cloud.githubusercontent.com/assets/5870455/20772323/c04602ac-b755-11e6-843b-ab880b4fd53d.png)
![screen shot 2016-12-01 at 00 34 58](https://cloud.githubusercontent.com/assets/5870455/20772324/c061e166-b755-11e6-8f28-594c2acf8c96.png)

**Comment by lonnieezell** [comment]
Great news about Oracle driver! Looking forward to it, though not looking forward to getting Travis setup to test it properly. :) 

I believe the last commit should fix up the session drivers. Unfortunately, that was a sloppy port from CI3 and doesn't have any tests written for it, but I should have that issue, and a few others I found, fixed now. Let me know if it's still broke.

**Comment by byazrail** [comment]
Hello,
Last commit great, but problem continue.

redishandler;
lockSession function;
		if (isset($this->lockKey))
		{
			return $this->redis->setTimeout($this->lockKey, 300);
		}
find replace;
		if ($this->lockKey === $this->keyPrefix.$session_id.':lock')
		{
			return $this->redis->setTimeout($this->lockKey, 300);
		}

have a nice day...
