### ISSUE TITLE
Database builder->table() connection reference problem

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#320]
Hi all,
CustomBuilder use BaseBuilder current connection not references.
create oci8 reference _limit function $this->connID false.

**Comment by lonnieezell** [comment]
I'm not 100% sure what your question is. You need to be a bit more specific in the future, please. Code samples help. 

You might check that you're initializing the class before you try to call whatever function it is you're calling, though. Or maybe it didn't connect correctly? I don't know your code so can't really help.

**Comment by byazrail** [comment]
Hi,
$builder = $this->db->table('BLABLA B');
$builder->where('B.STATUS', ':BSTATUS');
$builder->limit(0, 10);
$builder->get();

// Custom builder class on limit function;
	protected function _limit($sql)
	{
		if (version_compare($this->db->getVersion(), '12.1', '>='))
		{
			// OFFSET-FETCH can be used only with the ORDER BY clause
			empty($this->QBOrderBy) && $sql .= ' ORDER BY 1';

			return $sql.' OFFSET '.(int) $this->QBOffset.' ROWS FETCH NEXT '.$this->QBLimit.' ROWS ONLY';
		}

		$this->limit_used = TRUE;
		return 'SELECT * FROM (SELECT inner_query.*, rownum rnum FROM ('.$sql.') inner_query WHERE rownum < '.($this->QBOffset + $this->QBLimit + 1).')'
			.($this->QBOffset ? ' WHERE rnum >= '.($this->QBOffset + 1) : '');
	}

use _limit reference basebuilder;
not working $this->db->getVersion() reference connID.

**Comment by lonnieezell** [comment]
I can't see your code, and it's a custom driver so likely will have a fair amount of custom code, so I really can't say for sure. But it sounds like you're not connecting to the database, or storing that to the `connID` element. See [BaseConnection](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Database/BaseConnection.php#L362) for where it stores it. You'll have to step through each portion to find what's going wrong. 

Check out the MySQLi and PostgreSQL drivers for reference in CI4, then use CI3 ODBC stuff as a starting point would be my suggestion.
