### ISSUE TITLE
Post action after Toolbar -> Vars -> Headers Content-Type 2 lines

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#321]
Hi all,

Validation post process after debug toolbar vars tab on headers 2 Content-type.
See Image;
![screen shot 2016-12-07 at 22 38 56](https://cloud.githubusercontent.com/assets/5870455/20983639/e28cb1ce-bcc5-11e6-96e7-bc77862ea822.png)

**Comment by lonnieezell** [comment]
Yes, and it's valid to have 2 of the same type. I've verified that recently for this same problem. As for _why_ we have 2 of those being set, I'm not 100% sure at the moment, but if you want to dig into that's cool. :)

**Comment by byazrail** [comment]
I use all classes. Oci8, Redis, Approval, ViewCell, Own Core Classes (Controller, etc.).
I will provide information when it finds a solution. 👍
