### ISSUE TITLE
`google map` in Mysqli Could be a Mistake

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter4#324]
`

        $db->table('google_map')->where('address', 1)->update([
            'lng' => 104.067636,
            'lat' => 30.677334
        ]);

        var_dump($db->error()); // this is bug
`

`
	
ci4/system/Database/MySQLi/Connection.php
	//--------------------------------------------------------------------

	/**
	 * Executes the query against the database.
	 *
	 * @param $sql
	 *
	 * @return mixed
	 */
	public function execute($sql)
	{
        exit($sql);
		return $this->connID->query($this->prepQuery($sql));
	}

`
UPDATE `dr_google_map` SET `lng` = 104\.067636, `lat` = 30\.677334 WHERE `address` = 1

**Comment by lonnieezell** [comment]
Are you still getting this? Please make sure you've updated to latest code. There was a bug that would cause things like this that I'm pretty sure was fixed around the same time you originally posted. 

My [current test](https://github.com/bcit-ci/CodeIgniter4/blob/develop/tests/system/Database/Live/UpdateTest.php#L132) for this passes for me on both MySQL and Postgres.
