### ISSUE TITLE
a bug about set()

### ISSUE THREAD

**Issue by startbbs** [bcit-ci/CodeIgniter4#325]
here I use
`$db->table('user')->set('item_num','item_num+1',false)->where('id',1)->update(); `
the value of item_num in mysql become "0"

the above Executes: 
`UPDATE `lb_user` SET item_num = 'item_num+1' WHERE `id` = '1'`

but when I use the follow code
`UPDATE `lb_user` SET item_num = item_num+1 WHERE `id` = '1'`

it works well.

I guess the third param($escape) might be a bug. please test, thanks.

**Comment by jim-parry** [comment]
If this is a bug, raise the issue here, but you don't also have to cross-post it on the forum.

**Comment by lonnieezell** [comment]
I will definitely check on that but you can use the increment and decrement methods and not worry about it...
