### ISSUE TITLE
bug-form_open_multipart

### ISSUE THREAD

**Issue by startbbs** [bcit-ci/CodeIgniter4#345]
`<?php echo form_open_multipart('user/login',['class'=>'form']);?>`
when I use form_open_multipart, it would create the follow code
`<form action="http://127.0.0.1/user/login" class="form" enctype="multipart&#x2F;form-data" method="post" accept-charset="utf-8">`

please note the enctype, '/' was changed to `&#x2F;`

**Comment by samsonasik** [comment]
I give a try to fix it at #351

**Comment by davidgv88** [comment]
Hi @samsonasik 

I Think that this is not a issue.

The form works and the file is upload succesfully.

All attributes are being escaped using escapeHtmlAttr function from Zend Escaper Library.

Please look this https://framework.zend.com/manual/2.1/en/modules/zend.escaper.escaping-html-attributes.html

**Comment by lonnieezell** [comment]
Yup, even though it looks strange, it all works as expected in all of my tests.
