### ISSUE TITLE
Routes static parameter problem not found page

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#352]
Hi,

Sample routes line;
$routes->add('Settings', 'Site\Controllers\Pages::getSetting/1'); // 1 .etc alpha numeric or number problem.

Workaround;
$routes->add('bla/settings', 'Site\Controllers\Pages::getSettingOne');
$routes->add('zzz/settings', 'Site\Controllers\Pages::getSettingTwo');

Pages Controller on 2 function added;
getSettingOne() {return $this->getSetting(1);}
getSettingTwo() {return $this->getSetting(2);}

Have a nice day...

**Comment by lonnieezell** [comment]
That's the same way it's always been with CodeIgniter, IIRC. The first way that you're doing it, using the number 1, the system expects that to be method name, and methods cannot start with a number.
