### ISSUE TITLE
Old Cache-Control header tag remove?

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#355]
Hello,
using set_header on codeigniter 3.x remove old cache-control tag.
This 4 version not working or little bug not solutions.

working code;
$this->response->removeHeader('Cache-Control')
			->setHeader('Cache-Control', 'public, max-age=3600')
			->setHeader('Pragma', 'cache');

response;
Cache-Control:no-store, no-cache, must-revalidate
Cache-Control:public, max-age=3600
Pragma:cache
Pragma:no-cache

**Comment by lonnieezell** [comment]
Fixed in 5a84030367840709cb023b8104e6f76ccf400bd8
