### ISSUE TITLE
Validation field name issue?

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#356]
Hi,

$validation->setRule('username', 'required');
run response;
$validation->showError('username', 'single'); // The username field is required.
where the "username" function etc. language or string.

Have a nice day...

**Comment by lonnieezell** [comment]
I think the [userguide will answer that for you](https://bcit-ci.github.io/CodeIgniter4/libraries/validation.html#setting-custom-error-messages).
