### ISSUE TITLE
The efficiency of 'insertBatch' function

### ISSUE THREAD

**Issue by iMyth** [bcit-ci/CodeIgniter4#368]
Hi there,

I have a concern about the efficiency of 'insertBatch'. Would it be better to use 'insert into xx select xx union select xx ' instead of loop when having  small data?
well...exclude duplicate rows

thx & kind rgds

**Comment by lonnieezell** [comment]
Possibly. Care to create some benchmarks and test it? 

My biggest concern would be that it works for all of the database engines that CI3 currently supports. Aside from that, if there's a boost for small datasets but it slows down on larger datasets, we'd have to do a bunch of testing on all of those platforms to find where the happy medium is across all of them. 

While I wasn't involved in writing the insertBatch query, I'm guessing those elements played a big part in it.
