### ISSUE TITLE
session id validation when using php7.1

### ISSUE THREAD

**Issue by swxuan** [bcit-ci/CodeIgniter4#371]
Regex: /^[0-9a-f]{40}$/ is not working correctly when using php 7.1. According to php manual (http://php.net/manual/en/session.configuration.php#ini.session.sid-length), these values should be set as follow
session.sid_length = 40
session.sid_bits_per_character = 4

In my case, session file regenerated for every request, when FileHandler was used as session driver, and
session.sid_length = 32
session.sid_bits_per_character = 5

**Comment by byazrail** [comment]
Adapter, redis etc. are have bugs.

**Comment by lonnieezell** [comment]
Can you guys provide specifics about what you're seeing happening, what your setup is, etc. I need more details than, "It's not working" :)

**Comment by byazrail** [comment]
Hi :)
Workaround, according to the new system;
fix ; https://github.com/byazrail/CodeIgniter4/commit/7bf620c711c0573a82cbca22aaa38f4a3638285a

reference ;
https://github.com/bcit-ci/CodeIgniter/commit/2f760877c313871e5066b93b0b1aa76428c09fb6

**Comment by lonnieezell** [comment]
@byazrail That's great. Thanks. Could you submit that as a pull request? 

I did see something about those issues coming to light, but didn't follow it close enough, obviously. :)

**Comment by byazrail** [comment]
@lonnieezell welcome, submitted as pull request.
