### ISSUE TITLE
disable coveralls auto comment on pull request

### ISSUE THREAD

**Issue by samsonasik** [bcit-ci/CodeIgniter4#382]
I think coveralls auto comment should be disabled:

![screen shot 2017-01-20 at 1 03 29 pm](https://cloud.githubusercontent.com/assets/459648/22137999/f5a62a20-df10-11e6-9aeb-3ac60918ab74.png)

As the coveralls status is represented in build summary checklist itself.

**Comment by lonnieezell** [comment]
The one nice thing about having the comments on is that it makes a nice reminder for us or any contributors, to go write tests, which is a good thing. :) 

I think I'd like to keep them in for now, and I know it might get a bit noisy, so we'll keep an eye on it. It could definitely become annoying. I think most of those times, though, will be when someone isn't testing locally, but is using Travis to do all of the heavy lifting for them. Again, though, will keep an eye on it and see how bothersome it becomes.

**Comment by samsonasik** [comment]
Thank you, actually, the report itself is on the built summary on each commit pushed:
![screen shot 2017-01-23 at 12 25 06 pm](https://cloud.githubusercontent.com/assets/459648/22192476/155fc2c4-e167-11e6-9d6e-34179eb15b82.png)

**Comment by lonnieezell** [comment]
I understand that, but I think that has a different impact then seeing it in the comment. In the summary at the bottom, it simply feels like it's saying, "You failed" when all it really means is coverage went down. I think seeing the comment has a more immediate impact to the person submitting the PR, while the summary is more for the person accepting the PR. 

Don't worry, I'll likely get tired of it before too long, but want to live with it a little to make a final decision. :)

Thanks!
