### ISSUE TITLE
redirect reverseRoute problem

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#387]
redirect reverseRoute problem or non reverse route problem comment lines in.

![screen shot 2017-01-24 at 16 29 59](https://cloud.githubusercontent.com/assets/5870455/22249074/28975a9e-e24a-11e6-8c0f-066e64605302.png)

Response Header;
Cache-Control:no-store, max-age=0, no-cache
Cache-Control:no-store, no-cache, must-revalidate
CF-Cache-Status:MISS
CF-RAY:3263e1afa6653ff0-SOF
Connection:keep-alive
Content-Type:text/html; charset=UTF-8
Date:Tue, 24 Jan 2017 13:37:42 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified:Tue, 24 Jan 2017 13:37:42 GMT
Location:http://www.dev10.net
Pragma:no-cache
Server:cloudflare-nginx
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/7.0.14

non reverse route
![screen shot 2017-01-24 at 16 33 03](https://cloud.githubusercontent.com/assets/5870455/22249188/92743a72-e24a-11e6-8923-5500270df779.png)

or only / address
![screen shot 2017-01-24 at 16 33 40](https://cloud.githubusercontent.com/assets/5870455/22249198/9be94782-e24a-11e6-8eab-e80dc23264ad.png)

Response Header;
Cache-Control:no-store, max-age=0, no-cache
Cache-Control:no-store, no-cache, must-revalidate
CF-Cache-Status:MISS
CF-RAY:3263e1afa66537f0-SOF
Connection:keep-alive
Content-Type:text/html; charset=UTF-8
Date:Tue, 24 Jan 2017 13:39:42 GMT
Expires:Thu, 19 Nov 1981 08:59:00 GMT
Last-Modified:Tue, 24 Jan 2017 13:39:42 GMT
Location:/
Pragma:no-cache
Server:cloudflare-nginx
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/7.0.14

**Comment by lonnieezell** [comment]
You show me errors but don't tell me how to recreate them, including if you having matching routes in your file they should match up to, how the redirect method is called, etc. You also don't show the actual error you're getting, you just provide the first step in the backtrace. I can't help if I can't replicate.

At a guess, though, you're redirecting to a named route that doesn't exist. In that case, the actual error would have been "InvalidArgumentException Unable to locate a valid route.". If this is the case, please see [the docs](https://bcit-ci.github.io/CodeIgniter4/general/common_functions.html?highlight=redirect#redirect). 

I've done a quick test locally and it seems to work fine, so I'm guessing it's the parameter you're passing.
