### ISSUE TITLE
Problem with system bootstrap file needs to be fixed!

### ISSUE THREAD

**Issue by InsiteFX** [bcit-ci/CodeIgniter4#389]
The system bootstrap file is setting the public path, my service provider sets the path to public_html

So for the time being I have to edit the system/bootstrap file to edit this, this should be done in the index.php file for the public directory.

System files should never have to be edited.

Maybe use a define in the index.php file.

**Comment by lonnieezell** [comment]
A few things: 

1) Good point. 
2) I believe every hosting provider I've used in the past allows you to point the domain to any arbitrary folder, like the `public` folder. Does yours not allow this? 
3) We accept pull requests :)

**Comment by InsiteFX** [comment]
No, mine only allows to point to the public_html folder.

**Comment by lonnieezell** [comment]
Fixed in a0422d158ba44e20226b7384261e204953e8b190

**Comment by InsiteFX** [comment]
Thanks Lonnie,

**Comment by lonnieezell** [comment]
No problem.
