### ISSUE TITLE
timer long time getElapsedTime problem

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#390]
Hi guys,

cli use timer 10 mins or large execution process execution time result 1;
example result;
[##########] 100% Complete
parser is finished...
parser is total execution time : 1
[##########] 100% Complete
Finished...
Total execution time : 0,7284
Finished...
Total execution time : 1

use type;
process function;
timer(__FUNCTION__);

// codes...

call another function {
in function use another timer sample function name parser
timer(__FUNCTION__);
// codes...
timer(__FUNCTION__);
$execution_time			= timer()->getElapsedTime(__FUNCTION__);
CLI::write('parser is Finished...', 'green');
CLI::write('parser total execution time : ' . $execution_time, 'blue');
}

$execution_time			= timer()->getElapsedTime(__FUNCTION__);
CLI::write('Finished...', 'green');
CLI::write('Total execution time : ' . $execution_time, 'blue');

have a nice day

**Comment by lonnieezell** [comment]
Hmm. Unable to recreate locally. I've [written some new tests](https://github.com/bcit-ci/CodeIgniter4/commit/af7eb039b5c54024e69b229d1cf6ac3a2d8a4b6f) that should account for your use case, and they all pass. 

Your example is a little confusing to me so let me know if I didn't test the right thing. The first thing I see from your code is that you're not passing a string to the `timer()` function, but appear to be passing a constant. Depending on what that evaluates to, that could be causing an issue.
