### ISSUE TITLE
How to current page detailed information on router or etc?

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#393]
Hello,

How can I get the name of the controller and method of the page I am on?

sample;
$router->add('bla/bla', '\asd\dsa::test12');

use address bla/bla;
get detailed info;
namespace : \asd
controller : dsa
method : test12

have a nice day...

**Comment by lonnieezell** [comment]
Please visit the forums for questions. This area is for bug reports. Thanks.
