### ISSUE TITLE
Language File Array Support

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#414]
It would be useful to allow a language line to contain an array of strings to make working with lists easier.

If this is something that's agreed I can implement this and create a pull request.

**Comment by lonnieezell** [comment]
I can see that being useful, so yeah, go for it. Just make sure that it works with all of the intl string replacement in a logical manner. Oh, yeah, and tests. :)

**Comment by lonnieezell** [comment]
Sorry haven't gotten to comment on your PR yet. I've been working both ends of the day lately. I believe that should all be over after the deadlines on 2 different projects over the next week or so. 

What little time I've had so far has been trying to determine why Travis is showing all of the tests failing currently. I appreciate the PR and will get to it as soon as I can. Thanks!

**Comment by EpicKris** [comment]
@lonnieezell Thanks! I appreciate your comment and hope you find more time in your day after your deadlines. :)
