### ISSUE TITLE
One-Off Validation for a Single Value

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#418]
It may be useful to add the ability to do a one-off validation for a single value and single set of rules.

If this is something that's agreed I can implement this and create a pull request with some guidance on method naming.

**Comment by lonnieezell** [comment]
Sounds good. Go for it. :)

**Comment by EpicKris** [comment]
@lonnieezell Great, any suggestion on method names for this?

**Comment by lonnieezell** [comment]
Reading back over your description, are you recommending 2 methods here? If it's just a single method, I think we could use `check()`.
