### ISSUE TITLE
CLI with parameters is not working

### ISSUE THREAD

**Issue by baselbj** [bcit-ci/CodeIgniter4#422]
Hi,

While trying to test migrations using CLI and adding parameters it will not work. 

example:
run: php ci.php migrate:version 007
will get: Command 'migrate:version 007' not found

the problem is in CLI/console line 68 ($this->app->setPath("ci{$path}");) the setpath will implode all command segments.

Also line 69 (return $this->app->run();) should send command parameters this means that no parameters are passed to CLI command.

I can suggest a fix as the following:
1) getURI should return only first command segment.
2) CLI/CLI.php should return have function which returns command parameters
3) return $this->app->run(); should be something like return $this->app->run(CLI::getPrams());

If this solution is ok I can make a pull request :)

**Comment by baselbj** [comment]
I found the issue it was eraser than I expect. in CLI file line 675 function getURI():
change return implode(' ', static::$segments); to return implode('/', static::$segments);

**Comment by lonnieezell** [comment]
Good find! That was a leftover from when I recently refactored how the whole bootstrap process worked.

**Comment by baselbj** [comment]
Thank you ... I can help in many issues like this

**Comment by lonnieezell** [comment]
I look forward to it!
