### ISSUE TITLE
Validation Required Rule Only Accepts Arrays or Strings

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#423]
#The validation `required` rule currently only accepts arrays or strings, I am trying to pass it a `DateTime` object and it errors out, should the `required` rule be made to allow other types?

**Comment by lonnieezell** [comment]
yes it should be allowed to accept anything.

**Comment by EpicKris** [comment]
@lonnieezell In what instant should an object be considered to pass the `required` rule? Currently, I'm just passing the rule for any object.

On a side note I've also created my own rule set for PHP types, what're your thoughts on this?

**Comment by vahidvdn** [comment]
@EpicKris Why not use use anonymous function as a rule?

**Comment by codeliter** [comment]
@vahidvdn I think that would be a better approach

**Comment by lonnieezell** [comment]
Fixed in https://github.com/bcit-ci/CodeIgniter4/commit/e3f42e904dfbbe5afa38ecae5e462c00256534e1
