### ISSUE TITLE
Response Trait Fail Server Error Method

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#424]
It would be useful to have a `failServerError(string $description, string $code = null, string $message = ''): Response` method in the response trait to fail server errors.

If this is something that's agreed I can implement this and create a pull request.

**Comment by lonnieezell** [comment]
Good point. Yes, I think that's a good call.

And on the plus - side one of my two projects had their soft launch laaate last night and the other is scheduled to launch today or tommorrow, so I'll be freed up again next week. Yay! Though I may have to take a day or two to unwind. It's been a hellish 3 weeks. :)

**Comment by EpicKris** [comment]
@lonnieezell Good to hear you're getting through your projects! Sounds like some much needed rest is in order for you. :)
