### ISSUE TITLE
Response 404 not same satus get it

### ISSUE THREAD

**Issue by yonineitor** [bcit-ci/CodeIgniter4#425]
I'm trying to call a file that does not exist.

so, return  404 - File Not Found and name file.js

but in console, response status code **200** why does this happend?

![ok-warning](https://cloud.githubusercontent.com/assets/4680382/23566498/fbb4d008-0006-11e7-971f-37ce20ecf6f5.png)

**Comment by lonnieezell** [comment]
Can you provide an example of how you're setting the response values in your code?

**Comment by yonineitor** [comment]
Any route get it status 200 although there is not found.

![test](https://cloud.githubusercontent.com/assets/4680382/23669694/ed34e598-0319-11e7-9e4d-7211756218cd.png)

Setting response is required, where is there?
