### ISSUE TITLE
Migration File & Class Name Issues

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#437]
I am getting the error: `The migration class "App\Database\Migrations\Migration_Init" could not be found.` for my migration classes now.

application/Database/Migrations/00000000000001_Init.php
``` php
class Migration_Init extends Migration
{
}
```

**Comment by baselbj** [comment]
Did you namespace your migration?

As in the latest update all migration files should have namespace:

App/Database/Migrations

**Comment by lonnieezell** [comment]
Hmm. They shouldn't need to be namespaced. I just created one using the cli tool `php ci.php migrate:create` and ran the migration just fine. Here's what it's creating: 

```
<?php

use CodeIgniter\Database\Migration;

class Migration_temp extends Migration
{
    public function up()
    {
        
    }

    //--------------------------------------------------------------------

    public function down()
    {
        //
    }
}

```

**Comment by baselbj** [comment]
I will check it

**Comment by lonnieezell** [comment]
@baselbj You're right. I had tried that while in a feature branch that didn't have the latest changes to the migrations. 

@EpicKris Any update on this? Is your migration namespaced?

**Comment by EpicKris** [comment]
@lonnieezell Sorry thought I'd already replied. Yes, adding the namespace worked a charm!

**Comment by lonnieezell** [comment]
Ok, great. Closing this.
