### ISSUE TITLE
Language Line Prepend Recommendation

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#443]
I'm not sure if this is still a recommendation and would like some clarification.

It used to be recommended to prepend your language lines with a common word, but I see this is not done everywhere.
``` php
lang('Foo.fooBar'); // Prepended
lang('Foo.bar'); // Not prepended
```

Personally I prefer the non-prepended version, it looks cleaner.

**Comment by lonnieezell** [comment]
Not necessary now that the file name is the first segment. That is used in place the prepending now.
