### ISSUE TITLE
session getFlashdata() is not removing the flash data

### ISSUE THREAD

**Issue by qury** [bcit-ci/CodeIgniter4#446]
Hi,
I ran into an issue with flash data.
When i use `$session->setFlashdata(['item'=>'value']) ` the entries as preserved across multiple page loads.

I believe an unset method should be added to the `getFlashdata` method?

**Comment by lonnieezell** [comment]
What session driver are you using? That should be handled in the main Session.php file, during the `initVars()` method.

**Comment by qury** [comment]
I use  `CodeIgniter\Session\Handlers\FileHandler`
Does it make a difference that i initiate the session in the index.php file with `session_start()`?

**Comment by lonnieezell** [comment]
Yes, that definitely makes a difference. When you load/initialize the Session library for the first time, the session is automatically started. You don't need to do that. By starting the session manually at the start of the script you're not allowing CI to set the session driver up, which is used by PHP to handle sessions. So, CI can't provide the additional features like flash data. Remove that and I think you'll be fine.

**Comment by qury** [comment]
OK, this works fine, i just had to experiment with it a little bit, and use the sessoion() convenience function.
