### ISSUE TITLE
Environment File

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#452]
I noticed in the example environment file that some values are wrapped in `'` and others not, what determines what should be wrapped in `'` and not?

**Comment by lonnieezell** [comment]
I think that was my inexperience when I first set that up, honestly. I don't think any of them really need it.

**Comment by EpicKris** [comment]
Just wondering as I'm having an issue with my environment file where it doesn't seem to be reading the `app.forceGlobalSecureRequests = true` line correctly and as a result not redirecting to the secure version. Thought maybe there was an issue parsing the file.

**Comment by EpicKris** [comment]
I think I see the issue with this, but would like a second opinion, when initially bootstrapping CodeIgniter it loads the `AppConfig` without looking in the environment file.

**Comment by EpicKris** [comment]
Actually, force global secure requests doesn't seem to work at all for me, even if I set it directly in the App.php configuration file.

```
CodeIgniter\HTTP\RedirectException #307

BASEPATH/HTTP/Response.php at line 602
```

**Comment by lonnieezell** [comment]
We throw an exception mostly to make it testable, though there might have been an additional reason that I don't recall ATM. 

So - it's supposed to throw the exception. This is caught in CodeIgniter.php, line 211 at which point the script exits as expected. You say it's not working. What's it doing? I just ran a quick test with the following and it worked as expected, except that I don't have SSL setup for this local test domain so it gave me the expected error after redirecting. 

```
public function secure()
{
    $this->forceHTTPS(30);

    echo 'hi';
}
```
