### ISSUE TITLE
Rename "public" Folder Not Working

### ISSUE THREAD

**Issue by anasamu** [bcit-ci/CodeIgniter4#453]
I tried to change the name of a public folder in the application / Config / Paths.php can not work.

**Comment by lonnieezell** [comment]
I can't help unless you provide actual details. what did you set the value(s) to, and what does your folder structure look like?

**Comment by lonnieezell** [comment]
I cannot replicate as it works just fine here: 

- change the path to the name of the folder where you are serving your site from, like `public_html`
- ensure your folder is actually named that
- ensure your web host is pointing to the correct folder
- restart the web host

Everything works for me at that point. 

Closing.
