### ISSUE TITLE
If the controller’s method's parameter has a default value , the program will show 500 error

### ISSUE THREAD

**Issue by jk1860** [bcit-ci/CodeIgniter4#461]
`<?php namespace App\Controllers;

use CodeIgniter\Controller;

class Home extends Controller
{
	public function index($page = 'welcome_message')
	{
		 return view($page);
	}

	//--------------------------------------------------------------------

}
`
just modify the Application/Controllers/Home.php's code to this, the program will not work。

**Comment by lonnieezell** [comment]
I have not ran into any instances of this happening. You don't provide the exact error message you were getting, but it sounds pretty close to one that you'd get if you were not running on PHP 7. 

Can you verify the version of PHP you're using and provide the error message, please?

**Comment by jk1860** [comment]
my php version is 7.1.3 ,  and the error message is : 500 (Internal Server Error)

**Comment by lonnieezell** [comment]
Weird. That's something completely different than I get. Can you check your PHP error logs to see what the underlying error actually is? On mine, I get an Exception thrown, but that's due to an issue in the debug toolbar. Maybe try turning that off and seeing if that's the issue?

**Comment by jk1860** [comment]
in the file system/Filters/Filters.php,

**Comment by jk1860** [comment]
In the file CodeIgniter.php，the function handleRequest , this code
 `$response = $filters->run($uri, 'after');`

**Comment by jk1860** [comment]
In the file CodeIgniter , the function handleRequest, the code
`$response = $filters->run($uri, 'after');

		if ($response instanceof Response)
		{
			$this->response = $response;
		}`
If I delete these code ,the program is fine .

**Comment by jk1860** [comment]
yes, it is the debug Toolbar's problem!
