### ISSUE TITLE
Join not working in Query Builder

### ISSUE THREAD

**Issue by nskarl** [bcit-ci/CodeIgniter4#464]
> public function get($userid, $key)
	{
		$db	= Database::connect();
		$builder = $db->table('users');
		$builder->select('users.*');
		$builder->join('users_profiles', 'users_profiles.userid = users.id', 'left');
		$builder->where('users.id', $userid);
		$query = $builder->get()->getRowArray();
		if($query) return $query;
		return null;
	}

Tried all possible options, different aliases and without them - produces the same error:

Call to a member function getRowArray() on boolean

its work only with 1 table

**Comment by nskarl** [comment]
sorry. all is work.
dont work only with aliases

can i use aliase like as join ('users_profiles up', 'up.userid = u.id', 'left') ?

**Comment by jim-parry** [comment]
We use github for bug tracking, not support. You should post a thread on our forum instead.
