### ISSUE TITLE
Work with entities and validation bug

### ISSUE THREAD

**Issue by s524797336** [bcit-ci/CodeIgniter4#472]
If model set $returnType="App\Entities\xxx" and validation with `required_with[xxx]`
Because entity have a protected var `$datamap` and have a array value.

See system/Validation/Rules on line 308
`$requiredFields = array_intersect($fields, $data);`
Because `$data` have a `array datamap key` so it will return a `Array to string conversion` exception
Is it a bug or i'm not using it right?

**Comment by lonnieezell** [comment]
Can you provide sample code just to make sure I understand and have something to test against?

**Comment by s524797336** [comment]
File: App\Entities\User
<?php
namespace App\Entities;

use CodeIgniter\Entity;

class User extends Entity{

	protected $id;
	protected $username;
	protected $password;

}
Because `CodeIgniter\Entity` have a protected var $datamap on line 17 so this User class will inherit a protected var $datamap = [], right?
File: App\Models\UserModel
class UserModel extends \CodeIgniter\Model {
	protected $table = 'user';
	protected $primaryKey = 'id';
	protected $returnType = 'App\Entities\User'; //set to use user entity
	protected $validationRules = array(
		"pass_confirm" => "required_with[password]" //set this rule
	);
}
When call `save()` method on this model
File: CodeIgniter\Validation\Rules on line 308
`$requiredFields = array_intersect($fields, $data);`
If print_r($data) before this line, will get this
`Array ( [id] => [username] => xxx [password] => xxx  [datamap] => Array ( ) )`
So array_intersect will throw an error because datamap have a Array value

**Comment by s524797336** [comment]
Can you read full comment? i write a log but only show few, when i click edit, it's full....

**Comment by s524797336** [comment]
`save()` method can receive a entry object, when call `classToArray` method then `datamap` will appear, not exclude `datamap`

**Comment by lonnieezell** [comment]
Doh! You're right. I'll look into it tonight and see if this is a deeper issue, or if we can just ignore that one. I have a feeling this might be a bigger issue for any class properties that are arrays...

**Comment by s524797336** [comment]
Class have a `const` keyword to set some setting value like this datamap, because this value is not change.
`const datamap = array();`
Why not use that, i like use this keyword to do a lot of things

**Comment by lonnieezell** [comment]
That wasn't the problem. The problem was in the validation rules. 

With or without a const makes little difference here, but I'd like to leave the possibility for people to change that at runtime if they need to.

Pushing a fix now. Let me know if it works for you.
