### ISSUE TITLE
Route Blocking

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#474]
@lonnieezell i think the route blocking like you did in sprint php should also be available.

**Comment by lonnieezell** [comment]
Is it really needed, though? In CI4 you can turn off to auto-routing, making it so that you must specify each route, a common practice with a few other frameworks. When you do that, only the ones you specify are available so I'm not sure it's really helpful.

**Comment by chistel** [comment]
oh i never knew, just tested that, it's great.

**Comment by lonnieezell** [comment]
Awesome. Glad I could point you to something new! :)
