### ISSUE TITLE
Model issues

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#479]
I get the error message "Call to a member function get result() on boolean" in the model on line 328

**Comment by chistel** [comment]
typo error in my first messgae, It's " function getResult()" not "function get result()"

**Comment by dvaosta** [comment]
Is the query a SELECT? Otherwise $db->query("...") return a boolean.

**Comment by lonnieezell** [comment]
Please provide some form of context for this. Can you share code?
