### ISSUE TITLE
Router rule: (:alphanum) doesn't work

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#498]
Docs:  (:alphanum) will match **any string of alphabetic characters** or integers, or any combination of the two.
Routing:
`$routes->add('/objects/(:alphanum)/(:num)', 'Admin::objectsList/$1/$2');`
URL:
https://adm.domain.com/objects/users/10  - DOESN'T WORK

Routing:
`$routes->add('/objects/(:alpha)/(:num)', 'Admin::objectsList/$1/$2');`
URL:
https://adm.domain.com/objects/users/10  - WORKS

**Comment by iLevye** [comment]
i think alphanumeric rules should be like (?=.*[0-9])(?=.*[a-zA-Z]) in RouteCollection

**Comment by iLevye** [comment]
i think the 'alphanum' key must be define before 'alpha' key. can you try swap 'alphanum' and 'num' keys in system/Router/RouterCollection class $placeholders property

**Comment by beherit00** [comment]
`protected $placeholders = [
		'any'      => '.*',
		'segment'  => '[^/]+',
        'alphanum' => '[a-zA-Z0-9]+',
		'num'      => '[0-9]+',
		'alpha'    => '[a-zA-Z]+',
		'hash'     => '[^/]+',
	];`

It works with that change. Anyway I needed alphanumdash so I defined my own rule :).

**Comment by beherit00** [comment]
There is another "error" which has connection with that above... you can't create for example new rule which contain at the beginning key from  $placeholders.
For ex.
`$routes->addPlaceholder('alphanumdash', '([0-9a-zA-Z_\-\.]+)');` - doesn't work,
`$routes->addPlaceholder('dashalphanum', '([0-9a-zA-Z_\-\.]+)');` - works well
To be honest you shouldn't treat this as error but it should be mentioned in docs ;).

**Comment by lonnieezell** [comment]
Good catch with the ordering of default placeholders.
