### ISSUE TITLE
__set in \App\Entities\Sample doesnt works

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#499]
I'm trying to use Entities.
In my model SampleModel.php I've got:

```
    protected $table = 't_sample';
    protected $primaryKey = 'smp_id';
    protected $returnType = '\App\Entities\Sample';


    protected $allowedFields = [
        'all_fields_from_t_sample... without id ;)'
    ];
```
and in Entity Sample.php
```
<?php

namespace App\Entities;

class Sample
{
    protected $all_fields_1;
    protected $all_fields_2;
    protected $all_fields_3; ...


    public function __get($key)
    {...}

    public function __set($key, $value)
    {
                ddd($this->$key);
        if (isset($this->$key))
        {
            if($key == 'all_fields_1') {
                $this->$key = sthdifferent;
            }
            else
                $this->$key = $value;
        }
    }
}
```

but that __set is never used by BASEPATH.'Model.php'.
I can also define __set in my SampleModel instead  od Entity which called Sample... but why?

And why when I change method __set in SampleModel like that:
```
    public function __set($key, $value)
    {
        d($key, $value);
}
```
it prints **only** salt and their value ?
Is it a bug?

**Comment by beherit00** [comment]
Ok that issue is in documentation :).
https://bcit-ci.github.io/CodeIgniter4/database/model.html

instead of: `class Job` shoud be`class Job extends \CodeIgniter\Entity`

instead of 
`public function __get($key)
        {
                if (isset($this->$key))
                {
                        return $this->$key;
                }
        }

        public function __set($key, $value)
        {
                if (isset($this->$key))
                {
                        $this->$key = $value;
                }
        }`
should be:
`public function __get(string $key)
        {
                if (isset($this->$key))
                {
                        return $this->$key;
                }
        }

        public function __set(string $key, $value = null)
        {
                if (isset($this->$key))
                {
                        $this->$key = $value;
                }
        }`

**Comment by lonnieezell** [comment]
Good catch. The Entity class didn't exist when those docs were written up. I'll need to adjust those now.

However, there are docs for the Entity class, but it looks like they're not showing up in the index. You can find them, [here](https://bcit-ci.github.io/CodeIgniter4/database/entities.html), though.
