### ISSUE TITLE
Port SQLite database driver from CI3

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#502]

**Comment by Humni** [comment]
Will SQLite 3 be the min version?

**Comment by lonnieezell** [comment]
I haven't looked into the specifics of why we'd need to keep v2 around, but, yes, it was my intention to just do 3.

**Comment by Humni** [comment]
Sweet, I'll try to start getting somewhere with it

**Comment by lonnieezell** [comment]
Awesome! Let me know if you run into any questions.

**Comment by lonnieezell** [comment]
See https://github.com/bcit-ci/CodeIgniter4/pull/793
