### ISSUE TITLE
Port Zip library from CI3

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#505]

**Comment by otengkwame** [comment]
@lonnieezell How can i help

**Comment by lonnieezell** [comment]
If you want to make a PR with a converted library from CI3, that would be great. You can find all of the information about our contributor guidelines and style requirements [over here](https://bcit-ci.github.io/CodeIgniter4/contributing/index.html).

**Comment by jim-parry** [comment]
I suggest an approach like the Encryption package ...
system/Compression/Compression
system/Compression/CompressorInterface
system/Compression/Handlers/BaseHandler
system/Compression/Handlers/ZipHandler
application/Config/Compression
system/Config/Services::compressor()

This would set us up nicely for adding other compressers, like gz or tar.
What do you think, @lonnieezell ?

**Comment by lonnieezell** [comment]
Makes sense to me @jim-parry

**Comment by jim-parry** [comment]
Given the lack of advancement, or indication of same, I will tackle this.

**Comment by jim-parry** [comment]
Implementing the handler for PHP's built-in ZipArchive, it appears that that library does everything the CI3 one did. Closing this - we don't need to reinvent the wheel. Need to reference ZipArchive in the upgrading guide.
