### ISSUE TITLE
Bug: debug toolbar not visible

### ISSUE THREAD

**Issue by puschie286** [bcit-ci/CodeIgniter4#5215]
**Describe the bug**
the debug toolbar is not visible, the ?debug request show an invalid char at the end ('<') that prevent the toolbar from loading/showing correctly

**CodeIgniter 4 version**
current develop ( https://github.com/codeigniter4/CodeIgniter4/commit/d10a6029cd766f0a44e468d4f91899dcf99a522e )

**Affected module(s)**
Toolbar

**Expected behavior, and steps to reproduce if appropriate**
toolbar should load if environment is development

**Context**
 - OS: Windows 10
 - Web server: Apache 2.4.49
 - PHP version: 8.0.10
 - Database: MSSQL (sqlsrv)

**Workaround**
In Toolbar.php, 440 you need to decrease the length by one ( change -10 to -11 )
https://github.com/codeigniter4/CodeIgniter4/blob/d10a6029cd766f0a44e468d4f91899dcf99a522e/system/Debug/Toolbar.php#L440

**Comment by puschie286** [comment]
can someone verify if this is a php 8 or windows only bug ? 

guess it would be known or exist other bug reports if the toolbar is broken for everyone :/

**Comment by paulbalandan** [comment]
> **Workaround**
> In Toolbar.php, 440 you need to decrease the length by one ( change -10 to -11 )

`-10` already stops at the last character before `</script>`

**Comment by sfadschm** [comment]
> @lonnieezell yes, double checked - it has worked with a ealier version of 4.1.4

Everything working fine for me, too. 
Did you try 4.1.4 again after you found the error?
