### ISSUE TITLE
add yoda style

### ISSUE THREAD

**Issue by ytetsuro** [bcit-ci/CodeIgniter4#5226]
As there was an exchange in [this comment](https://github.com/codeigniter4/CodeIgniter4/pull/2487#discussion_r732919504), I would like to write in YODA notation in CodeIgniter.

I would like to add YODA to the Cs-fixer rules to avoid repeating the same mistake.

https://cs.symfony.com/doc/rules/control_structure/yoda_style.html

**Comment by kenjis** [comment]
We do not use yoda conditions.

The following code is only one exception:
```php
if (false === $query = $this->query($sql)) {
```

Personally I do not like the code, because it is difficult to read `if` condition.
The following is better.
```php
$query = $this->query($sql);
if ($query === false) {
```

Furthermore, it is much easier to read when it looks like this.
```php
$query = $this->query($sql);
if ($query->failed()) {
```

**Comment by kenjis** [comment]
There is `yoda_style`:
https://github.com/CodeIgniter/coding-standard/blob/f79b0009c9fb894e8725eccdde136671eb516c2c/src/CodeIgniter4.php#L539-L544
