### ISSUE TITLE
Superglobals reset

### ISSUE THREAD

**Issue by WitekS** [bcit-ci/CodeIgniter4#524]
After $ app-> run (); In index.php, all tables, for example $ _GET, $ _POST, $ _COOKIE, $ _REQUEST, $ _SERVER, etc are reset and the variable CI_ENV = 'development' disappears, and the page starts as Page rendered in 0.0033 seconds. Environment: production. Until the execution of $ app-> run (); Variables in Superglobals are OK

**Comment by lonnieezell** [comment]
Could you describe your setup, what server, server version, PHP version, etc, that you're running on please. I haven't seen this happen before and all tests are passing, even those that use the superglobals.

**Comment by WitekS** [comment]
I currently have PHP Version 7.1.4 with WAMP Stack 7.1.4-0 (details in the attachment). I had a problem with setting the develop mode so I started from step-by-step mode to see when the CI_ENV variable changed to production but after executing the command $ app -> run (); Any variable disappears and the page starts up in the production mode. Debugging I have by xdebug and netbeans.
[localhost-phpinfo.pdf](https://github.com/bcit-ci/CodeIgniter4/files/1039378/localhost-phpinfo.pdf)

**Comment by lonnieezell** [comment]
I'm starting to research this one tonight, but just as a side note - we recently changed the develop var to be CI_ENVIRONMENT, and it can be set from the .env file. Don't know if that will help or not.

**Comment by WitekS** [comment]
I already set up in .env CI_ENVIRONMENT = development and it works

**Comment by WitekS** [comment]
In the file public / .htaccess is set to the variable SetEnv CI_ENV development I changed it to SetEnv CI_ENVIRONMENT development is now ok without additional setting in the .env file. Development and production mode is set correctly. As for me the topic ended.

**Comment by kenjis** [comment]
I sent PR: #532

**Comment by lonnieezell** [comment]
Thanks @kenjis, it's been merged. @WitekS I'm glad you got things working on your end.
