### ISSUE TITLE
where i extends Controller, and rewrite __construct, get error

### ISSUE THREAD

**Issue by deliangyang** [bcit-ci/CodeIgniter4#527]
TypeError
Argument 3 passed to App\Core\MY_Controller::__construct() must be an instance of CodeIgniter\Log\Logger, none given, called in /Users/deliang/Work/work/CodeIgniter4/system/CodeIgniter.php on line 706

**Comment by lonnieezell** [comment]
It helps if you show code otherwise I can't really give any pointers.
