### ISSUE TITLE
Minor: Debug bar showing htmlentities (<strong>)

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#531]
This is just a minor issue I noticed,
The debug bar is printing out the html entities instead. Provided a test screenshot. 

![screenshot 2017-06-03 10 33 09](https://cloud.githubusercontent.com/assets/2489333/26754412/4ebbdfc4-4848-11e7-8d56-bc470a9822e1.png)

**Comment by lonnieezell** [comment]
Thanks for pointing this out. Not sure what's going on here, but I can look into in a week or so. Will be heading out for vacation on Tuesday and will be gone for a week.

**Comment by timothymarois** [comment]
Yeah I found it under `prepareReplacement` in `parser.php` 

At least from my findings, it's this line causing it to strip html tags.
**line 572**
`$filters[] = 'esc(html)';`

That's as far as I got.

**Comment by timothymarois** [comment]
Just looked at the docs for the unescaping in parser. So in `_database.tpl.php` the `{sql}` should be `{! sql !}` and I believe it's in more areas of the toolbar too.

**Comment by lonnieezell** [comment]
Oh, yeah, the new additions to the Parser might cause havoc I haven't checked in the debug bar.

**Comment by lonnieezell** [comment]
Fixed in 5df04254acfd36555d4f4a057d48db5da074a70e
