### ISSUE TITLE
Debug bar: Uncaught ErrorException: str_repeat(): Second argument has to be greater than or equal to 0

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#538]
Uncaught ErrorException: str_repeat(): Second argument has to be greater than or equal to 0 in /home/pc/sites/oneway/system/Debug/Exceptions.php:413
![screenshot-adm loc 2017-06-05 18-40-21](https://cloud.githubusercontent.com/assets/8414802/26776987/d8e9aaa0-4a1e-11e7-962b-53512211a4cb.png)

**Comment by lonnieezell** [comment]
Sorry it took so long - I just got back from vacation. Any chance you remember what was causing the issue? I've submitted a fix that might take care of the issue, but no real way to check...

**Comment by beherit00** [comment]
Unfortunately I can't remember what caused that exception. Anyway I'm not sure if that your fix is the best solution for: "second argument has to be greater then or equal to 0".
str_repeat('[/span]', -1) caused that exception... even if -1 will be a string then (int)$spans will be still -1

`$spans = "-1";
var_dump((int)$spans);
prints (int)-1
`

**Comment by lonnieezell** [comment]
Doh! You're correct. I was moving too quickly last night. Thanks.
