### ISSUE TITLE
override core files

### ISSUE THREAD

**Issue by ded100let** [bcit-ci/CodeIgniter4#546]
Hi! In CI4 mono override Model.php or Controller.php as in CI3? Folder core. Or is this not possible anymore? I would like to completely abandon Model.php TK has its own Model :) Thanks!

**Comment by lonnieezell** [comment]
CI4 makes creating your own base Model as simple as creating a new class and extending all of your other models from it. You can build one from scratch (or reuse the one you're used to) if you wish. 

However, I should point out that the [Model in CI4](https://bcit-ci.github.io/CodeIgniter4/database/model.html) actually brings quite a bit of useful functionality that you should read up on before abandoning.

**In the future, please use the forums for advice. These issues are used for bug tracking and feature planning.**
