### ISSUE TITLE
Validation Issues 

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#550]
I noticed validation class does not support array post like val[username].

also the doc for the validation is does not seem to be the reality.

**Comment by lonnieezell** [comment]
I thought it did support array input, but it's been a year since I worked on that feature, and there doesn't seem to be any tests for it so you might be right. I'll have to check on that. 

If you've found errors in documentation we'd love to know the details so we can clarify.

**Comment by chistel** [comment]
Ok, i main time i would check for the improper docs and highlight them out.

**Comment by chistel** [comment]
seems  the Doc is updated from my last check. still remaining the array request
