### ISSUE TITLE
Error: redirect() - ltrim() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#568]
Doesn't appear like this is working like it should. Anything placed within `redirect()` seems to throw an error.

Example: You'd except this to redirect the local url.
`redirect('/login');`

Error Exception:
`ltrim() expects parameter 1 to be string, object given`

![screenshot 2017-06-22 16 03 37](https://user-images.githubusercontent.com/2489333/27453450-8313f13c-5764-11e7-9449-80cf96d27848.png)

https://bcit-ci.github.io/CodeIgniter4/general/common_functions.html?highlight=redirect#redirect

**Comment by lonnieezell** [comment]
Hmmm. All of the test for that are passing. I tried the simple test that's in the Checks controller and it works. I was thinking it might have been a Closure that was somehow getting in there, but I wrote a new test for that it is passing. 

Can you post your routes file (or email it to me if you'd rather it not be public?

**Comment by lonnieezell** [comment]
@timothymarois are you still getting this?
