### ISSUE TITLE
Minor thing with View file not found exception...

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#570]
View/View.php:178

`throw new \InvalidArgumentException('View file not found: '.$file);`

when throwing exception prints only: "'View file not found: "

I think there is a place for small improvement:

`throw new \InvalidArgumentException('View file not found: '.$view);`

when exception will be thrown it  will #print: "'View file not found: not-existing-view-file.php"

**Comment by lonnieezell** [comment]
Good catch. Thanks. Will have that fixed momentarily.

**Comment by lonnieezell** [comment]
Fixed in a1f71ea6a3fe38408cf25c9cbd3495c68973cb9a
