### ISSUE TITLE
Model Order

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#571]
To be able to specify an order for results.

If this is something that's agreed I can implement this and create a pull request.

**Comment by lonnieezell** [comment]
Shouldn't be necessary. Any calls to the model that don't exist will try against the query builder and then the db connection class. So orderby calls should do exactly what you need.

**Comment by EpicKris** [comment]
Thanks, I don't know why I forgot about this! 😆
