### ISSUE TITLE
[FEATURE] Model Class: updateWhere() 

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#572]
I noticed we have a `deleteWhere()` on the model class. However the only way you can do an `update()` is by `primary key`, so it only makes sense to have an updater for batch changes. 

`updateWhere(array, array)`

If i'm mistaken let me know, but as for the docs and the source code, doesn't appear to be a batch update method. I also know the builder includes the `->where()->update()` however, that's not accessible from model, or at least not in the documentation. Thoughts? 

And yeah you could use the `save()` method to accomplish most, but there is occasions where a simple `updateWhere()` could come in handy for quick updates across the table.

**Comment by lonnieezell** [comment]
You can use any Query Builder functionality through model, interspersed with fluent model function calls, too. [See these docs](https://bcit-ci.github.io/CodeIgniter4/database/model.html#working-with-query-builder). 

I can't link directly there, but the Query Builder does have [updateBatch](https://bcit-ci.github.io/CodeIgniter4/database/query_builder.html#updating-data), just like in previous versions. Is that what you mean?

**Comment by timothymarois** [comment]
Yeah was having a difficult time getting the same result with builder through the model, though I didn't experiment too much, was in rush mode and quickly went onto another solution to accomplish it. But seeing the delete function, figured there should be a similar one with update. but anyways, we can close this for now. Thanks!
