### ISSUE TITLE
helper function uses include instead of include_once

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#575]
I'm finding that I may need to include a reference to some helpers in multiple areas of the code which will result in the helper file being included twice. The second time, it essentially is ignored because of the conditional check wrapping the helper functions but the file is still being included. Should this be changed to include_once? This is the line I'm referring to.
https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Common.php#L541

Thanks for all your efforts.

**Comment by lonnieezell** [comment]
That's a good point. Will change. Thanks.
