### ISSUE TITLE
camelize helper function incorrect

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#576]
The current camelize function looks to be a version of the humanize function. Previous versions of CI had this:
```
return strtolower($str[0]).substr(str_replace(' ', '', ucwords(preg_replace('/[\s_]+/', ' ', $str))), 1);
```
https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Helpers/inflector_helper.php#L192

Thanks again

**Comment by lonnieezell** [comment]
You're absolutely correct. Thanks.
