### ISSUE TITLE
XML formater xmltoarray indexed array incorrect

### ISSUE THREAD

**Issue by abldev** [bcit-ci/CodeIgniter4#577]
Don't check numeric key 
https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Format/XMLFormatter.php#L95

Solution
------------------------

if (! is_numeric($key))
				{
					$output->addChild("$key", htmlspecialchars("$value"));
				} else
				{
					$output->addChild("item{$key}", htmlspecialchars("$value"));
				}

**Comment by lonnieezell** [comment]
This looks good, but can you provide some sample code that was generating the problem you saw so that I can double-check and verify.

**Comment by abldev** [comment]
Return data:
return $this->respond([
			'productname' => 'Appale',
			'tags' => ['Vitamin', 'Fruit']
		]);

====================

XML Parsing Error: not well-formed
Location: http://localhost/ympcl1local/ax-app/public/entity/save
Line Number 2, Column 51:<response><productname>Appale</productname><tags><0>Vitamin</0><1>Fruit</1></tags></response>
--------------------------------------------------^

**Comment by samsonasik** [comment]
this should already fixed and can be closed.

**Comment by lonnieezell** [comment]
@samsonasik can you link to the specific code that fixed it? I'll need to ensure we have a test in the system to ensure this works, so want to make sure I get the test right :)

**Comment by samsonasik** [comment]
Here it is:

code: https://github.com/bcit-ci/CodeIgniter4/blob/e25a4319e155e87323c55c43e0abcc915f4eff7a/system/Format/XMLFormatter.php#L84-L93

test: https://github.com/bcit-ci/CodeIgniter4/blob/e25a4319e155e87323c55c43e0abcc915f4eff7a/tests/system/Format/XMLFormatterTest.php#L43-L56

**Comment by lonnieezell** [comment]
@samsonasik Perfect. Thanks! Will close.
