### ISSUE TITLE
Storing data

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#580]
I don't know if I have to attribute this issue to codeigniter or a something else.

I tried to save an hashed password  using the php hash function, but it truncates the first 4 char of the hashed password. mind you, I applied same rule regarding using that function. I applied same function in codeigniter 3 it worked well.

**Comment by satchwinston** [comment]
The same thing happened to me using the model->insert function.

**Comment by chistel** [comment]
the image below shows what am talking abt

![ellor fw](https://user-images.githubusercontent.com/621320/27771506-85da8602-5f47-11e7-98a6-c5d545c9e097.png)

**Comment by daylightstudio** [comment]
This area in the protectIdentifiers method code looks suspicious to what may be causing your issue:
https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Database/BaseConnection.php#L1064

**Comment by lonnieezell** [comment]
I've run into this previously and thought I had it conquered but perhaps not :) can you share the code you're using so I can recreate? I'm pretty sure it was happening previously due to it be double escaped.

**Comment by chistel** [comment]
below is the code
` 
  $password = '123456';
  $usermodel = new UserModel();
  $hashpass = \App\Libraries\Auth\Password::hashPassword($password);
  // Update user password
  $pdata = [
     'user_password'     =>$hashpass ,
   ];
    if (! $usermodel->update($user['user_id'], $pdata))
    {
      	$this->error = $usermodel->error()['message'];
         //$this->error = 'Unknown error encountered';
         return false;
    }
`

**Comment by lonnieezell** [comment]
A couple of assumptions, please tell me if I'm wrong: 

1. UserModel doesn't do anything extra and is simply extending CodeIgniter\Model.
2. hashPassword library basically uses PHP's `password_hash()` function with a BCRYPT as the type? 

What does the hash look like after it's generated? Is it the same as in your image above?

**Comment by chistel** [comment]
yea its same as the above image.

i even ran a the regular query without the model, same thing

**Comment by lonnieezell** [comment]
Ok, thanks for the confirmation. I will try to look into this tonight, but with a Holiday here in the states, and a sick kid, it might not happen for a couple of days.

**Comment by chistel** [comment]
oh sorry about the kid, well project is been used for is not going live soon, so it cool

**Comment by lonnieezell** [comment]
@chistel Pull down the latest code and let me know if you run into any issues. I managed to get a bit of free time before calling it a day here.

I've reworked how named bindings works with the Query object and this should help, but still feels a touch hacky. Tests pass but I don't have a full-fledged app yet to test it under a variety of use-cases.

**Comment by chistel** [comment]
(y) nice one, it worked absolutely well @lonnieezell

**Comment by lonnieezell** [comment]
Awesome. Closing.
