### ISSUE TITLE
\InputRequest $request->getFiles() doesn't return FileCollection instance

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#586]
Screen from documentation:
![screenshot-bcit-ci github io 2017-07-05 11-25-31](https://user-images.githubusercontent.com/8414802/27845694-c8a24de2-6174-11e7-8448-65007e84ae3d.png)
Result:
![screenshot-adm --- rpi 2017-07-05 11-25-14](https://user-images.githubusercontent.com/8414802/27845695-c8da2186-6174-11e7-8599-d89ec752e70b.png)

**Comment by beherit00** [comment]
There is also no "hasFile()" method which is mentioned in the same part of docs.
https://bcit-ci.github.io/CodeIgniter4/libraries/incomingrequest.html#id15

**Comment by lonnieezell** [comment]
Whoops! You're correct. It uses a FileCollection internally, but then returns an array. Will fix it up shortly.
