### ISSUE TITLE
\IncomingRequest method getFiles() - Should really return only arrays?

### ISSUE THREAD

**Issue by beherit00** [bcit-ci/CodeIgniter4#590]
if yes im wondering if can return empty array if there is no elements inside $_FILES instead of null
![screenshot-adm  rpi 2017-07-06 19-01-15](https://user-images.githubusercontent.com/8414802/27903696-8a77d8e8-627d-11e7-9dc5-063657d2a9af.png)

I'd like to propose for line 492:
`return is_array($this->files->all())?$this->files->all():[];`

**Comment by beherit00** [comment]
After some investigation better place to make changes I think is populateFiles method of
 class FileCollection.

**Comment by lonnieezell** [comment]
To fix another issue earlier today, the returned value is now the FileCollection itself, which has some additional tools to work with.
