### ISSUE TITLE
form_open_multipart('', [], $hidden)

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#598]
I'm not so sure if this will cause a problems in browsers (probably does) but in fact it looks strange:

`form_open_multipart('', [], $hidden)`
prints:
`<form action="https://www.dmvoneway.com/contact" enctype="multipart&#x2F;form-data" method="post" accept-charset="utf-8">`

so there is "& # x 2 F;" instead of "/"

**Comment by lonnieezell** [comment]
I verified that it works just fine in Safari, Chrome, and Firefox. May look funny, but it's perfectly valid HTML and is the result of ALL attributes being correctly escaped.
