### ISSUE TITLE
Command Line Seeding Error

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#601]
The documentation says to run `php index.php migrations seed TestSeeder` to seed data from the command line, but running this command produces the error:
```
ERROR: Page Not Found

Controller or its method is not found.
```

Looks like it should be `php ci.php db:seed TestSeeder`?

**Comment by lonnieezell** [comment]
Sorry - looks like that portion of the docs is incorrect. And at a glance I'm not seeing any docs about what it should be. Bad me.

try this: 

```
php ci.php db:seed
```

**Comment by EpicKris** [comment]
So the command works, but it can't find my seed `TestSeeder` producing the error:
```
CodeIgniter CLI Tool - Version 4.0-dev - Server-Time: 2017-07-13 09:36:33am


An uncaught Exception was encountered

Type:        Error
Message:     Class 'TestSeeder' not found
Filename:    /Users/kristian/Repos/cozyglow.co.uk/system/Database/Seeder.php
Line Number: 155
```

**Comment by lonnieezell** [comment]
I believe it doesn't handle namespaced classes at the moment, so try removing any namespace from the seeds. I guess that needs fixing.

**Comment by lonnieezell** [comment]
I was wrong, it [should support](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Database/Seeder.php#L126) namespaced files just fine. 

Can you show me the basics of your TestSeeder class and where it's located?

**Comment by EpicKris** [comment]
``` php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TestSeeder extends Seeder
{
    public function run()
    {
        $this->call(ProductCategorySeeder::class);
        $this->call(ProductSeeder::class);
    }
}
```

**Comment by lonnieezell** [comment]
Remove the namespace from your Seeder and you should be good.

**Comment by EpicKris** [comment]
@lonnieezell Thanks, I'll do that! But shouldn't it support namespaces as you mentioned?
