### ISSUE TITLE
I'm not sure but captcha seems currently unavailable. Would it be included in ci4?

### ISSUE THREAD

**Issue by AidenJeon** [bcit-ci/CodeIgniter4#604]
Hi, I'm a CodeIgniter Korean forum administrator.
I'm interested in ci4.

**Comment by lonnieezell** [comment]
Captcha will not be available. It was very old technology that truly did little to protect a site as it was easily readable by most scripts that people might use. Instead, a sophisticated HoneyPot solution is in the plans.

**Comment by kgulle** [comment]
Any improvement on honeypot solution?
