### ISSUE TITLE
Too much escaping negative int  (int < 0)

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#606]
When I'm trying to save entity with a property which is a negative number then there is too much escaping with final query:

![sth](https://user-images.githubusercontent.com/8414802/28169578-29f9c9be-6826-11e7-8d20-cccff13acc2c.png)

is:   \\-10   should be -10

**Comment by lonnieezell** [comment]
@nowackipawel Please try it now. I believe it should be fixed.

**Comment by nowackipawel** [comment]
Yeah it works now. I thought you won't be escaping integer number but anyway it work as should.
