### ISSUE TITLE
Route naming and Groups

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#612]
I'm experiencing an issue with routing where the options in the route group (e.g. 'namespace') are being overwritten. For example, the following I would expect the URI admin/user/create to work:
```
$routes->group('admin', ['namespace' => 'Admin\Controllers'], function($routes)
{
	$routes->get('user/create', 'UserController::create', ['as' => 'user_create']);
}
```
However, because I added the `['as' => 'user_create']`, it overwrites the default options and loses the 'namespace' option. I'd like to propose replacing the lines around 1120 in the RouteCollection::create method (https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Router/RouteCollection.php#L1120):
```
if (is_null($options))
{
	$options = $this->currentOptions;
}
```
with something like the following so that the current group options get merged with the passed options: 
```
$options = array_merge((array)$this->currentOptions, (array)$options);
```

**Comment by lonnieezell** [comment]
That's a good call. Care to submit a PR for that? :)

**Comment by daylightstudio** [comment]
Yep... wanted to run by the solution first to make sure I wasn't missing something or if there was a preferred way of implementation. I'll send it in shortly.

**Comment by lonnieezell** [comment]
Appreciate it. And that sounds good. That's what it was intended to do, but I obviously took a misstep :)
