### ISSUE TITLE
Q: Support of array notations is not longer supported?

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#627]
Is there any reason why array notation is not longer supported?
I found code which supported it is commented in \CodeIgniter\HTTP\Request:

`
//
//		// Does the index contain array notation?
//		if (($count = preg_match_all('/(?:^[^\[]+)|\[[^]]*\]/', $index, $matches)) > 1) // Does the index contain array notation
//		{
//			$value = $array;
//			for ($i = 0; $i < $count; $i++)
//			{
//				$key = trim($matches[0][$i], '[]');
//				if ($key === '') // Empty notation will return the value as array
//				{
//					break;
//				}
//
//				if (isset($value[$key]))
//				{
//					$value = $value[$key];
//				}
//				else
//				{
//					return NULL;
//				}
//			}
//		}
`

**Comment by lonnieezell** [comment]
Simply because no one has gone back to make sure it works :)
