### ISSUE TITLE
Refactor DB Backup to stream to file instead of holding in memory

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#64]
Might make sense to move this to the Forge class? Probably not, though it would make sense if that was renamed to Schema...

Would love a backup and import function that could save out and read back the schema to the exact point. Could be a nice other option for migrations - complete database schema dumps by date....

Development Checklist:
- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by jim-parry** [comment]
2.5 years without a nibble. Closing, and anyone interested can propose the capability on the forum.
