### ISSUE TITLE
Feature requested- Auth and Template Engine

### ISSUE THREAD

**Issue by rrajesh011** [bcit-ci/CodeIgniter4#647]
Can we have inbuilt Auth Lib and Template Engine like laravel.

**Comment by lonnieezell** [comment]
Search the forums. That won't be happening, sorry.  However, the new parser is pretty darn powerful and you could easily [create your own template engine](http://blog.newmythmedia.com/blog/show/2017-06-12_simple_template_engine).

**Comment by EpicKris** [comment]
Would it be worth considering creating an auth interface for authorization? I do not know if this has already been discussed, so I am just throwing it out there.

We could have an auth interface (somewhat like caching), so different auth libraries can be switched in and out with a simple configuration file. People can make adapters between the auth interface and the auth libraries (which they could then share too).

**Comment by lonnieezell** [comment]
If we were implementing some form of Auth, that would be the way to go, because the argument has always been we can't create a one size fits all auth library. Since we're not, though, I don't think it makes sense.
