### ISSUE TITLE
Add indexing functions to Forge

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#65]
Development Checklist:
- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by davidgv88** [comment]
When I finish the task of foreign keys #63 I will look this feature

**Comment by baselbj** [comment]
Hi, I will try finding time to help so please provide me with more information about this issue.

**Comment by lonnieezell** [comment]
Actually - looks like this has already been done. We've got our standard keys and foreign keys in place. Not sure what this originally meant other than that. :(

Thanks for the interest in helping out! There's definitely other things that need a helping hand.

**Comment by baselbj** [comment]
just tag me and I will try helping you :)
