### ISSUE TITLE
Undefined method CLIRequest::isSecure()

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#656]
Hi there,
I'm used to use some of cli requests in my applications and I tried to check how to use it in CI4, but unfortunately:

`An uncaught Exception was encountered
Type:        Error
Message:     Call to undefined method CodeIgniter\HTTP\CLIRequest::isSecure()
Filename:    /home/pi/sites/sth/system/Common.php
Line Number: 646`

**Comment by nowackipawel** [comment]
Even when I tried to make a small bad hack there is another problem when I'm trying to run sth via cli:

`An uncaught Exception was encountered

Type:        ErrorException
Message:     Undefined index: HTTP_HOST
Filename:    /home/pi/sites/sth/system/Router/RouteCollection.php
Line Number: 1250
`

**Comment by lonnieezell** [comment]
CLI requests cannot be sent over HTTPS so there is `isSecure` check within a CLI Request. That's only in an [IncomingRequest](https://bcit-ci.github.io/CodeIgniter4/libraries/incomingrequest.html) object.

**Comment by nowackipawel** [comment]
Pls correct me if I'm wrong but cli request are dedicated for using via command line (shell), if yes then IMHO there is a problem with  Common.php which calling to undefined method isSecure() of CLIrequest class.  Ofc in Route configuration there was a route for path which I used defined as  ->cli('path', 'Class:method');

BTW: If I added method isSecure() { return true;} to CLIRequest class CI throw  exception from second comment.

**Comment by lonnieezell** [comment]
Oh, I misunderstood. I thought you were trying to **call** isSecure from a cli request. You're right, then. Sounds like there's an issue in Common.php. 

Care to make pull request for it?
