### ISSUE TITLE
Routing issue - bad args in function call.

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#672]
I defined routing like this:

`$routes->get('/objects/(:Dalphanum)/sort/(:Dalphanum)/([A-Z]{3,7})', 'AdminList::objectsSortCreate/$1/$2/$3', ['subdomain' => 'adm']);`

where Dalphanum is: 
`$routes->addPlaceholder('Dalphanum', '([0-9a-zA-Z_\-\.]+)');`

And 
`var_dump(func_get_args());`

which is inside objectsSortCreate method prints:

`array(3) { [0]=> string(6) "someth" [1]=> string(6) "someth" [2]=> string(3) "FOO" } `

when I'm trying to open:

`https://adm.dmvoneway.com/objects/someth/sort/FOO/BAR`

when I changed route for:

`$routes->get('/objects/(:Dalphanum)/sort/(:Dalphanum)/([A-Z]{3,7})', 'AdminList::objectsSortCreate/$1/$2/$3/$4/$5', ['subdomain' => 'adm']);`

var_dump prints:

`array(5) { [0]=> string(6) "someth" [1]=> string(6) "someth" [2]=> string(3) "FOO" [3]=> string(3) "FOO" [4]=> string(3) "BAR" } `

I'm not sure if should be: 

[0] => someth
[1] => sort
[2] => FOO
[3] => BAR

instead of returning value.

**Comment by lonnieezell** [comment]
What is the error you're getting? I'm glad you're trying to debug, but it's easier if you tell us what you expected to happen, and what actually happened so we can see what the problem might be.

**Comment by nowackipawel** [comment]
![screenshot-html-online com 2017-08-14 14-09-28](https://user-images.githubusercontent.com/8414802/29258090-381bf7e6-80fa-11e7-8aa5-c4ab71e8aa72.png)

**Comment by lonnieezell** [comment]
Sorry it took me so long. I've added a [new test](https://github.com/bcit-ci/CodeIgniter4/blob/develop/tests/system/Router/RouterTest.php#L135) for this that replicates it about as closely as I can, and the tests pass with the expected parameters. 

Your regex pattern looks fine at a glance. 

I'm not sure why it's showing that like it is, but I expect if you set your parameters you expect in your method it should be fine: 

```
public function objectsSortCreate($object, $sort, $key)
{
    . . .
} 
```
