### ISSUE TITLE
Fatal error: Cannot use Config\Services as Services

### ISSUE THREAD

**Issue by abldev** [bcit-ci/CodeIgniter4#674]
Fatal error: Cannot use Config\Services as Services because the name is already in use in /system/CodeIgniter.php on line 38

Working after remove below line from /system/CodeIgniter.php
use Config\Services;

**Comment by daylightstudio** [comment]
I ran into a similar issue and it had to do with my PHP version. I updated to 7.15 and it fixed the issue:
https://github.com/bcit-ci/CodeIgniter4/pull/582

**Comment by lonnieezell** [comment]
@abldev What version of PHP are you using? Are you on Windows?

**Comment by abldev** [comment]
PHP Version 7.0.8

OS: OS X Yosemite, Ver : 10.10.5

**Comment by lonnieezell** [comment]
I've seen that happen twice - once on a Windows setup where paths weren't configured properly (would have to scour the forums for the link), or as @daylightstudio said, for versions of PHP under 7.0.15. IIRC, the person with the previous issue was using 7.0.10. 

Please try upgrading and let me know if that works for you.

**Comment by abldev** [comment]
Its works after upgraded PHP version to 7.1.4.

I test after remove 'use Config\Services;' line and works for me.

**Comment by lonnieezell** [comment]
Does it work without removing that line, though?

**Comment by abldev** [comment]
Yes, it work

**Comment by JakeAi** [comment]
I was removing that line as well. Then I upgraded my PHP version to the newest I could for Wamp and it worked ever since.

**Comment by lonnieezell** [comment]
Sweet. Will update the readme's minimum PHP version to 7.0.15, then, unless someone has it working on Windows with an earlier build?
