### ISSUE TITLE
show strange chracters in kint.php inside system/ThirdParty folder.

### ISSUE THREAD

**Issue by imranrbx** [bcit-ci/CodeIgniter4#676]
Hello Team,
 while exploring Codeigniter 4 i have come across a file named Kint.php which have strange characters inside, is it normal or i messed or missed something ?

[screenshot](https://prnt.sc/g8axdj)

Thank You!

**Comment by lonnieezell** [comment]
That's normal with the new version of Kint. It's a third-party library and I'm not sure what encoding they're using for the file, but we don't modify that one at all.
