### ISSUE TITLE
Postgres Json type error on save

### ISSUE THREAD

**Issue by abldev** [bcit-ci/CodeIgniter4#677]
When try to save json type data using PostgreSQL add slashes on json encoded string in wrong format, below mentioned actual data to save and converted data while debugging Query.php  

Actual data  : '{"value":"Supplier 1","id":"4c49455250505355f00001e774e18ed2"}'

Converted to : '\{"value"\:"Supplier 1","id"\:"4c49455250505355f00001e774e18ed2"\}' and raise an error.

It works after commenting the line 423 in /system/Database/Query.php

$escapedValue = preg_quote(trim($escapedValue, $this->db->escapeChar), '|');

**Comment by lonnieezell** [comment]
I plan on trying to replace the `preg_replace` for named binds with a `strtr` tonight. I think that will fix things... should fix this, also.

**Comment by samsonasik** [comment]
@lonnieezell just ref , at #678, using stripslashes fix the postgres part, but it will make the mysql part error

**Comment by samsonasik** [comment]
@abldev should be fixed at develop now
