### ISSUE TITLE
multiple File upload issue

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#679]
upload of multiple files returns null

below is what i tried
`<input accept="image/*" multiple type="file" id="feed-editor-image-input" name="images[]"/>`
` $imagesFile = $this->request->getFiles('images');
	   var_dump($imagesFile);`

**Comment by JakeAi** [comment]
@chistel In the function `getFiles()` on line [487](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/HTTP/IncomingRequest.php#L487) of the IncomingRequest class, if you change 
```
public function getFiles(): FileCollection
{
	if (is_null($this->files))
	{
		$this->files = new FileCollection();
	}
	return $this->files;
}
```
to
```
public function getFiles()
{
	if (is_null($this->files))
	{
		$this->files = new FileCollection();
	}
	return $this->files->all();
}

```
It will work for now. I would let @lonnieezell check over this though because it is a dead end with `getFiles()`.

**Comment by lonnieezell** [comment]
A couple of thoughts for you @chistel: 

1. Is your form setup with `enctype=multipart/form-data`? Forgetting that is a common error, for me anyway.
2. Did you dump the $_FILES variable to ensure there was anything actually uploaded that the server recognized? 
3. You're calling `getFiles('images)`, however that method simply returns all files within a FileCollection class (and, yes, @JakeAi that's the way it should be. The FileCollection class provides some handy helper functions you might want to use.).  To retrieve a single file, you should use the `getFile()` method (singular). Or use `getFiles()` and then you can do checks like `hasFile()`, etc. 
4. Finally, when trying to access a single file of an array of files like you have here, you should use [dot array syntax](https://bcit-ci.github.io/CodeIgniter4/libraries/uploaded_files.html#multiple-files).

**Comment by chistel** [comment]
@JakeAi That was my first solution,  but it returned  error say Hercules must be an instance  of FileCollection except I have to remove the instance from it

**Comment by chistel** [comment]
@lonnieezell pls can you give a sample of running a multi file upload to a folder using the `getFiles()` method

**Comment by lonnieezell** [comment]
@chistel I might be able to pull something together tonight (just getting my morning started here), but you never answered the questions - especially #1 and #2.

**Comment by chistel** [comment]
@lonnieezell Oh skip me, #1 & #2 did that,  and 3 I figured that I was on the wrong path. 
Now it's returns all. but it would be better using specific field I'd that just returning all.

**Comment by JakeAi** [comment]
@lonnieezell I couldn't even get getFiles to work without modifications. getFiles creates a new FileCollection class, but there is no construct and doesn't call any functions?, and this->files is null. If you call getFile('w/e') and then getFiles, it works.

```PHP
// This works
	print_r( [
			$_FILES,
			$this->request->getFiles(),
		] );
```

```PHP
// This doesn't work
	print_r( [
			$_FILES,
			$this->request->getFile( 'images' ),
			$this->request->getFiles(),
		] );
```
```HTML
 <form action="/Shared/Test" method="post" enctype="multipart/form-data">
        <input multiple type="file" id="feed-editor-image-input" name="images[]"/>
        <input type="submit">
    </form>
```

```PHP
Array
(
    [0] => Array
        (
            [images] => Array
                (
                    [name] => Array
                        (
                            [0] => 170586-Subaru_Impreza_WRX-Subaru_Impreza-Subaru-JDM.png
                            [1] => 17499755_1403719142999697_1454939783_o.jpg
                        )

                    [type] => Array
                        (
                            [0] => 
                            [1] => image/jpeg
                        )

                    [tmp_name] => Array
                        (
                            [0] => 
                            [1] => D:\Wamp\tmp\php6315.tmp
                        )

                    [error] => Array
                        (
                            [0] => 1
                            [1] => 0
                        )

                    [size] => Array
                        (
                            [0] => 0
                            [1] => 118352
                        )

                )

        )

    [1] => CodeIgniter\HTTP\Files\FileCollection Object
        (
            [files:protected] => 
        )

)
```

**Comment by chistel** [comment]
@JakeAi  I figured it out in to ways, either add the all method of FileCollection into a constructor or go with the previous method you suggested but removing the fileCollection instance from `getFiles()` method

**Comment by chistel** [comment]
@lonnieezell Never mind about my last response and request, I figured it out. I would make a doc regarding it.

**Comment by JakeAi** [comment]
@chistel All you need to do is return all() and remove the return type after getFiles(). You don't need to necessarily remove the instance.
```PHP
public function getFiles(): FileCollection // <-----
{
	if (is_null($this->files))
	{
		$this->files = new FileCollection();
	}
	return $this->files; // <-----
}
```
to
```PHP
public function getFiles() // <-----
{
	if (is_null($this->files))
	{
		$this->files = new FileCollection();
	}
	return $this->files->all(); // <-----
}

```

**Comment by chistel** [comment]
@JakeAi exactly what I did

**Comment by JakeAi** [comment]
@chistel Oh, right on. I'm still confused though. Is @lonnieezell right? Or is something broken? Like, I understand about the helper functions, but I couldn't get it to work at all.

**Comment by chistel** [comment]
@JakeAi he is right, I can't find anything broken there.. when I make the doc, I would clarify it

**Comment by JakeAi** [comment]
Can you post your sample code?

**Comment by chistel** [comment]
@JakeAi am on mobile now,  but  here is what I have, 
 `If($image file = $this->request->getFiles())
{  
    foreach($imagefile['images'] as $Im)
    {
       if ($im->isValid() && ! $im->hasMoved())
       {
            $newName = $img->getRandomName();
            $img->move(WRITEPATH.'uploads', $newName);
       }
    }
`

where the **images** is the form field name
<input type="file" name="images[]" multiple />

**Comment by JakeAi** [comment]
@chistel did you add the all() to the IncomingRequest then? Because your code doesn't work out of the box.

**Comment by chistel** [comment]
@JakeAi yes I added it

**Comment by JakeAi** [comment]
@chistel Ahhh, that's what I meant about being broken. So something does need changed.

**Comment by chistel** [comment]
@JakeAi 🙄🙄🙄 yes just that

**Comment by lonnieezell** [comment]
@chistel 's changes have been merged in, so closing this.
