### ISSUE TITLE
Postgres json column search error

### ISSUE THREAD

**Issue by abldev** [bcit-ci/CodeIgniter4#680]
https://github.com/bcit-ci/CodeIgniter4/blob/0d6bf21cd61438ae0e030e6ccc9d28ae9caf0f64/system/Database/BaseBuilder.php#L2801

Added white space bteween '>>' operator

Sample rule:
 project->>'value'  LIKE :project->>'value' ESCAPE '!'  
converted to 
project->>'value'  LIKE :project-> > 'value' ESCAPE '!' 
its shows error.

Update :
============ 
Modified above line to:
\s*[^->]>\s*',                  // >

**Comment by lonnieezell** [comment]
Could you submit a PR for this?

**Comment by abldev** [comment]
Submitted PR
