### ISSUE TITLE
imagecopyresampled(): supplied resource is not a valid Image resource

### ISSUE THREAD

**Issue by JakeAi** [bcit-ci/CodeIgniter4#689]
I have tried multiple code setups for the image class and I cannot get it working, the way I need it to. I can do one file at a time. If I want to create thumbnails it errors. These are the setups I've tried. I have been digging through the class trying to find where it goes wrong, but I can't find it anywhere.

```PHP
foreach ($this->sizes as $size) {
	$copyImage = \Config\Services::image( 'gd' )
			->withFile( "{$folderPath}/{$filename}.{$extension}" )
			->resize( $size, $size )
			->save( "{$folderPath}/{$filename}x{$size}.{$extension}" );
}
```

```PHP
$copyImage = \Config\Services::image( 'gd' );
foreach ($this->sizes as $size) {
	$copyImage->withFile( "{$folderPath}/{$filename}.{$extension}" )
			->resize( $size, $size )
			->save( "{$folderPath}/{$filename}x{$size}.{$extension}" );
}
```

**Comment by lonnieezell** [comment]
I won't have time to look into this until later today, but I would guess it's due to how you're calling `\Config\Services::image( 'gd' )`. That will return a shared instance by default. Try this: 

```
\Config\Services::image( 'gd', null, false)
```

**Comment by lonnieezell** [comment]
You're right, it does make sense. And looking at the code, `withFile` should refresh, since it creates a new image. Looking deeper, though, it looks like the `$resource` value isn't reset during the `withFile` call, which is probably why it's always using the same file. I'll push a fix for that momentarily.
