### ISSUE TITLE
To much escaping in where

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#691]
```
    public function getSthByDomainId($domain_id) {
        $this->[WITH or WITHOUT builder() HERE]->select('sth_id')
            ->where('sth1_sth_id', "(SELECT `aaa_bbb_id` FROM `t_abc` WHERE `aaa_id` = " . $this->db->escapeString($domain_id) .")", FALSE)
            ->get()
            ->getResult();
        d($this->db->getLastQuery());
```
produces escaped query instead of FALSE passing as a third parameter of ->where method.

`SELECT `sth_id`
FROM `t_sth_sth`
WHERE sth1_sth_id = '\(SELECT `aaa_bbb_id` FROM `t_abc` WHERE `aaa_id` \= 1\)'`

-----
Edit after a minute:
OK everything is ok when as second parameter we will pass NULL as is in docs, but anyway will be more useful if we would be able to pass field name as first parameter, subquery as second and false as third.

**Comment by lonnieezell** [comment]
I can see how that might be useful in this particular case, but causes issues with other cases, I believe. And this is the way that CI has been since the beginning I believe. Glad you got it working, though.
