### ISSUE TITLE
Why is system/bootstrap.php lowercase?

### ISSUE THREAD

**Issue by anrip** [bcit-ci/CodeIgniter4#695]
Maybe it is system/Bootstrap.php ?

**Comment by anrip** [comment]
system/Helpers/cookie_helper.php maybe is system/Helpers/CookieHelper.php

**Comment by lonnieezell** [comment]
bootstrap isn't located through the autoloader so it's not important to be uppercase, though it would make sense the way the rest of the framework has evolved. 

As for helpers - any functional files (as opposed to classes) are kept lower-case and snake cased as per our style guides.
