### ISSUE TITLE
ErrorException #1 htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by malayvuong** [bcit-ci/CodeIgniter4#702]
I have this error Exception. I wonder why i received this error and how to fix it. I decided to delete this display full error detail.

<img width="1257" alt="screen shot 2017-09-01 at 13 28 06" src="https://user-images.githubusercontent.com/13240975/29957862-ee5d9f82-8f19-11e7-8432-1e36c44d305c.png">

```
<?php if (! is_array($value) && ! is_object($value)) : ?>
<?= htmlspecialchars($value, ENT_SUBSTITUTE, 'UTF-8') ?>  // Delete this line
<?php else: ?>
<?= '<pre>'.print_r($value, true) ?>
<?php endif; ?>
```
When i delete this line `ci4/application/Views/errors/html/error_exception.php(149): htmlspecialchars(Object(__PHP_Incomplete_Class), 8, 'UTF-8')` so this error has display normally.

After i delete this line, result like this:
<img width="1249" alt="screen shot 2017-09-01 at 13 35 24" src="https://user-images.githubusercontent.com/13240975/29957952-7b01b018-8f1a-11e7-8efd-63adac1293a4.png">

Does this negatively affect the display of errors?

**Comment by InsiteFX** [comment]
htmlspecialchars takes 4 parameters. the last ones are optional.

So echo out your $value and see if it is a string.

**Comment by malayvuong** [comment]
I don't know how. I'm from Vietnam, so in my php file, sometime I comment or texture has some Vietnamese in theres.
So I echo $value, this is the result:
<img width="1232" alt="screen shot 2017-09-03 at 22 09 20" src="https://user-images.githubusercontent.com/13240975/30004181-a45fa448-90f4-11e7-8517-cfd9fcdae1dd.png">

**Comment by InsiteFX** [comment]
Shouldn't your auth.html be named auth.php ?

**Comment by malayvuong** [comment]
I don't think so, .html just an extension for the url.
When I echo an invalid variable; this error displayed.

**Comment by lonnieezell** [comment]
A better option than deleting the line (and the potential protections they give) is to try and fix it. Not sure how an object was getting through when we were checking to ensure it wasn't an object, but that's no biggie. I've changed it to check if it's a string which should keep us safe. Try again and let me know how it works for you.

**Comment by malayvuong** [comment]
It's work!

Thanks.
