### ISSUE TITLE
Bug: app.proxyIPs must be array and can't be loaded from dotenv.

### ISSUE THREAD

**Issue by runnermatthew** [bcit-ci/CodeIgniter4#7034]
### PHP Version

8.0

### CodeIgniter4 Version

4.2.11

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

PostgreSQL 13.9

### What happened?

4.2.11 set the following requirement for in Config/App.php for `public $proxyIPs`

> @var array<string, string>

CodeIgniter4 has no way to set arrays from dotenv. This forces an App.php config file in addition to dotenv for each deploy.

### Steps to Reproduce

In Config/App.php set `public $proxyIPs = [];`

In dotenv set `app.proxyIPs =['172.25.0.1/16'=>'X-Forwarded-For']` where `172.25.0.1/16` covers your reverse proxy IPs. `$request->getIPAddress()` still returns proxy IP address

### Expected Output

`$request->getIPAddress()` to return the IP set by the proxy server in the X-Forwarded-For header.

**Comment by kenjis** [comment]
This is not a bug. 

Environment variables are not PHP variables.
dotenv dose not support array like this:
`app.proxyIPs = ['172.25.0.1/16'=>'X-Forwarded-For']`

Why don't you set them in the Config file?

**Comment by kenjis** [comment]
Workaround is to add the constructor in `Config\App`, and set `$proxyIPs` from environment variables.
