### ISSUE TITLE
view parser throws InvalidArgumentException

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#704]
`$this->parser = \Config\Services::parser();`

render() method called automatically with $file = /var/www/codeigniter4/application/Views/_database.tpl.php

throws InvalidArgumentException on line 147 of Parser.php

**Comment by lonnieezell** [comment]
I'll need to see a little more code, because it you do what you've shown: 

```
$parser = Services::parser();
$parser->render();
```

you get an error because render requires a string value in the first parameter.

**Comment by gustavojm** [comment]
Thanks for your prompt reply. I don't even call the render() method. It gets called by CI I think

the source code of the method in the controller is the following:
    
```
public function parsear() {
        $db = \Config\Database::connect();
        $this->parser = \Config\Services::parser();
        $table_name = 'users';
        $fields = $db->getFieldNames($table_name);
        print_r($fields);
}
```
the attached file is the "view-source" of the page because the backtrace does not get rendered.  

[view-source_ci4.com_index.php_categories_parsear.txt](https://github.com/bcit-ci/CodeIgniter4/files/1276199/view-source_ci4.com_index.php_categories_parsear.txt)

**Comment by lonnieezell** [comment]
CI doesn't automatically call the render method, so that would be in your code somewhere. Maybe a parent controller?

**Comment by gustavojm** [comment]
Seems to be called by 
BASEPATH/Debug/Toolbar/Collectors/Database.php : 186

```
		$output = $parser->setData($data)
				->render('_database.tpl');
```

**Comment by jaynarayan89** [comment]
I have similar problem. I have posted details on forum [link to ci forum](https://forum.codeigniter.com/thread-68866.html)

**Comment by lonnieezell** [comment]
@gustavojm Doh! Silly me. Forgot the toolbar used the Parser. Looking into it.
