### ISSUE TITLE
Separate DebugToolbar from CI_DEBUG

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#707]
I keep running into scenarios where I'd like CI_DEBUG mode to be on but I don't want the DebugToolbar to render because it adds additional code to the response that I don't want (and can mess up AJAX responses that return HTML). Would you accept a PR for a separate constant (e.g. CI_DEBUG_TOOLBAR) to display the DebugToolbar?

**Comment by lonnieezell** [comment]
No need. Comment the toolbar out in `application/Config/Filters.php`: 

```
public $globals = [
		'before' => [
			// 'csrf'
		],
		'after'  => [
			// 'toolbar'
		]
	];
```

**Comment by daylightstudio** [comment]
Thanks.
