### ISSUE TITLE
Form validation not working when Passing Empty array [ ]

### ISSUE THREAD

**Issue by jaynarayan89** [bcit-ci/CodeIgniter4#715]
It should return false when no rules are set.

**Comment by jaynarayan89** [comment]
When I tried to return false from  run method  of validation class

//using this lines 
if(empty($this->rules))
{
	return false;
}

it gives the following error:

session_start(): Failed to initialize storage module: user (path: )	


I am Using php 7.1.9 with wamp on windows 7

**Comment by jaynarayan89** [comment]
When I set sessionsavepath in config the session  error is solved .
 May I issue PR for this ?

**Comment by lonnieezell** [comment]
The [getErrors() method](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Validation/Validation.php#L561) checks the session to handle redirects with input. 

What type of PR do think this needs? It sounds like your session driver was simply not setup.

**Comment by jaynarayan89** [comment]
In CI3 when no rules are set  validation returns false. 
while looking into tests In CI4 I found following method
testRunReturnsTrueWithNothingToDo()

So I am confused. Either we have to fix run method to return false or fix the docs to say that run method will return true if  you no rules set

**Comment by jaynarayan89** [comment]
@lonnieezell  any suggestion?

**Comment by lonnieezell** [comment]
The docs should be fixed up to say that run method will return true. I'll change that now.

**Comment by lonnieezell** [comment]
Hmm. Reading through that passage again, it makes me think it was done that way as a safety mechanism so you didn't get a false sense that things were working when, in reality, you forgot to add the rules. Maybe false is better.

**Comment by lonnieezell** [comment]
Closed via: 0bda6ee4028ca3154628dea0b3ef52de493a3eaa
