### ISSUE TITLE
Should Model class implement the magic setter/getter methods for protected properties?

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#720]
for example to get the table name from the model

$model->getTable()

without having to declare $table as public in the model.

**Comment by lonnieezell** [comment]
Why do you need the table outside of the model? Isn't that the point of the model - to separate out the persistence from the rest of the app?

**Comment by gustavojm** [comment]
Yes, that's the point of the model, but...

I'm trying to achieve something like what you did in SprintPHP

https://github.com/ci-bonfire/Sprint/blob/develop/myth/_generators/Controller/ControllerGenerator.php#L280-L288

And when I say "something like" I mean "exactly that" ;-)

**Comment by lonnieezell** [comment]
:) In that case, use Reflection and you can get protected/private properties. 

However, you could also contribute to [vulcan](https://github.com/lonnieezell/vulcan) which is a code generation suite I've worked on a bit. it's not complete just yet, but has a pretty good start.

**Comment by lonnieezell** [comment]
CI4 already has a [ReflectionHelper](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Test/ReflectionHelper.php) trait that provides a couple of methods for reading/writing protected fields.

**Comment by gustavojm** [comment]
Awesome thing! I didn't know about "vulcan". I'm gonna give it a look and see if I can cooperate in some way, considering that my coding skills are not that great and are definitely outdated.
Thanks!
