### ISSUE TITLE
Double quotation in getFieldData();

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#721]
`$fields = $this->db->getFieldData('categories');`

Generates a double quotation in the table_name. The only valid for Postgres is the single quotes like in 'categories'

`
SELECT "column_name", "data_type", "character_maximum_length", "numeric_precision", "column_default" FROM "information_schema"."columns" WHERE LOWER("table_name") = '"categories"'
`

**Comment by K-YSoftware** [comment]
I suggest you better use laravel

**Comment by natanfelles** [comment]
@gustavojm I have no time now, but just searching something say me that this bug is here: https://github.com/bcit-ci/CodeIgniter4/blob/606fe137185c0f28681e9ffcc490264f8aafc1bd/system/Database/Postgre/Connection.php#L303

Please, update and if you fix it, open a PR.

Thanks!

**Comment by gustavojm** [comment]
Hi, @natanfelles 

$table is already surrounded by " by the method call 

$this->protectIdentifiers($table, true, null, false)

in 
$fields = $this->_fieldData($this->protectIdentifiers($table, true, null, false));

https://github.com/bcit-ci/CodeIgniter4/blob/606fe137185c0f28681e9ffcc490264f8aafc1bd/system/Database/BaseConnection.php#L1599-L1604

**Comment by lonnieezell** [comment]
According to [the Postgres docs](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) double-quotes are perfectly valid, and are what is used in their examples, even.

**Comment by gustavojm** [comment]
With double quotation I meant, single and double quotes altogether like in this LOWER("table_name") = **'"categories"'**.
And it was throwing an error.

I'm sorry if there was a misunderstanding in what I wanted to say, English is my second language,
Regards.
