### ISSUE TITLE
False Information In Documentation With Actual Code

### ISSUE THREAD

**Issue by sk8dvlpr** [bcit-ci/CodeIgniter4#7216]
My CI4 Version  : `4.2.10`
Documentation Link : https://codeigniter.com/user_guide/database/query_builder.html#updatebatch

I don't know if I'm reading the documentation wrong, but it does explain that the second parameter can take Array data.

`$builder->updateBatch($data, ['title', 'author']);`

But when I open the function in the code, it says that the second parameter is a string.

Path : `vendor/codeigniter4/framework/system/Database/BaseBuilder.php/updateBatch`

```
/**
   * Compiles an update string and runs the query
   *
   * @throws DatabaseException
   *
   * @return false|int|string[] Number of rows affected or FALSE on failure, SQL array when testMode
   */
   public function updateBatch(?array $set = null, ?string $index = null, int $batchSize = 100)
   {
   ....
```

What I want to do is do a Batch update but use more than one index. Back again on the documentation there also says can use `$builder->setData($data)->onConstraint('title, author')->updateBatch();`. But the onConstraint function is not found. And I want to ask if there is a way to batch update with more than one index?

**Comment by ddevsr** [comment]
You must upgrade to v4.3.x, that code already in v4.3.x

**Comment by kenjis** [comment]
Yes, https://codeigniter.com/user_guide/ is the official user guide for the latest release.
In this moment, v4.3.1.

If you want to see older versions, you can download from:
https://github.com/codeigniter4/userguide/releases

**Comment by wangling97** [comment]
Oh, that's why. I thought version 4.2.10 is still relevant with existing documentation.
