### ISSUE TITLE
$request->uri->getSegment(); return error

### ISSUE THREAD

**Issue by dannywebdev** [bcit-ci/CodeIgniter4#722]
Sorry my english. getSegment() return error If Number of segment is > of real segmento.

example.com/admin

$request->uri->getSegment(4); return error

In CI3 segment(4, NULL) return NULL

Again sorry my English.

**Comment by natanfelles** [comment]
See #701

**Comment by lonnieezell** [comment]
#701 has been merged so this should be fixed. It will return an empty string instead, though.
