### ISSUE TITLE
Passing  array as argument in Parser Plugin not working

### ISSUE THREAD

**Issue by jaynarayan89** [bcit-ci/CodeIgniter4#724]
I am trying to create plugin for form_open method and want to pass array as argument. But it is not working.

{+ form_open action="jj" attributes="['id'=>'myform']" +}

**Comment by lonnieezell** [comment]
That's not supported by the parser. Instead, you should accept things as key pair values, like: 

```
{+ form_open action="jj" id="myform" +}
```

etc. Inside the plugin you'd need to determine what special bits wouldn't be part of the attributes array and pull those out separately. On this plus side, this is easier to read.
