### ISSUE TITLE
Mysqli Driver doesn't  throw sql level exceptions / error

### ISSUE THREAD

**Issue by jaynarayan89** [bcit-ci/CodeIgniter4#734]
<del>It should gives some appropriate message or raise exception if user forgets to add  deleted field in table. Right now it is very hard to figure out that mistake from error massage and back trace.</del>

**Comment by ujjaldutta** [comment]
I think for softdelete $builder->where('deleted', 0) the field name should be dynamic so I can put column name deleted to something else.
I faced same error but after installing php 7.1.10 the problem solved.

**Comment by jaynarayan89** [comment]
when I try an insert operation on non existing table it silently fails without giving any error. I think the actual problem is  **mysqli not throwing exception when error occurs**.

I think we need to  use something  mysqli_report(MYSQLI_REPORT_ALL)  when we instantiate mysqli object.

I  add the line in connect method of  CodeIgniter\Database\MySQLi\connection and it work until this 
pagenotfound  issue #765  occurs.

**Comment by jaynarayan89** [comment]
@ujjaldutta the problem is still there . just delete the deleted field from table and it will give you some unrelated error instead of saying the field isnt exists,

**Comment by jaynarayan89** [comment]
@lonnieezell sorry to bother you,but  will you please look in this issue? If you are busy then nudge me little to right direction. I am working on this from couple of days and I feel that  I am very close to solution. Thanks.

**Comment by lonnieezell** [comment]
As for the second comment: 

> I think for softdelete $builder->where('deleted', 0) the field name should be dynamic so I can put column name deleted to something else.

That's definitely something I'd accept as a PR to the model.

As for the core of the issue - @jaynarayan89 I think you are closer than I am at this point in knowing the solution. From what you've described, it sounds like your proposed solution of adding the `mysqli_report` is a good remedy, so that we can see what's actually happening. Which is always a good thing. I would think that would depend on the environment the app is running under, though, since I believe it's currently setup to throw the errors in development only. To be honest, though, my understanding of the db layer is not as thorough as it could be since the drivers are primarily ports with a few bigger changes. 

With the pageNotFound issue (hopefully) resolved, is your fix working?

**Comment by jaynarayan89** [comment]
@lonnieezell  When  i use mysqli_report(MYSQLI_REPORT_ALL); in connect methos it gives the following error. 

 **Fatal error: Uncaught InvalidArgumentException: 1146 is not a valid HTTP return status code in D:\xampp\htdocs\ci4.dev\pms\system\HTTP\Response.php on line 279**

![image](https://user-images.githubusercontent.com/6889629/31587025-9929431c-b1f7-11e7-843c-b7cc4b40f32e.png)

**Comment by jaynarayan89** [comment]
@lonnieezell  I think we have to adjust the determinecodes() methed of codeigniter\debug\exceptions class. 

when i changed the line  number 301 from 
if ($statusCode < 100 )
to
if ($statusCode < 100 || $statusCode == 1146)
it works.

here 1146 is the error code we get from mysqli_sql_exception

I am not sure what this method is actually doing so i am not requesting PR, But i would like to . Please guide me .Thanks.

note: I have added mysqli_report(MYSQLI_REPORT_ALL);  to connect method of mysqli driver.

**Comment by jaynarayan89** [comment]
As per [MYSQL OFFICIAL ERROR LIST](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html) mysqli_sql_exception can throw codes from 1000 to  1727 (server side errors) or  2000 to 2059 (client side errors).

**Comment by lonnieezell** [comment]
That method is taking the code of the exception and turning it into an HTTP status code that should be returned. Looks like we should make that more like: 

```
if ($statusCode < 100 || $statusCode > 599)
```

**Comment by lonnieezell** [comment]
@jaynarayan89 Let me know if this latest push fixes it.

**Comment by jaynarayan89** [comment]
@lonnieezell  The latest push fixed it. Please review #779 .
