### ISSUE TITLE
PHPCBF - CodeIgniter4-Standard

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#757]
What do you think of mentioning the [CodeIgniter4-Standard](https://github.com/louisl/CodeIgniter4-Standard) in the user guide?

**Comment by jim-parry** [comment]
He has offered to transfer the repo to us, so it will get integrated somehow.
Mentioning a third party repo in the user guide has problems, as it is out of our control.

**Comment by natanfelles** [comment]
Ok. Thank you sir.
