### ISSUE TITLE
Debug Tool: Show view filepath

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#758]
Hello, @lonnieezell !

Today I remembered that [Magento makes it possible](https://insync.co.in/how-to-enable-template-path-and-block-name-hints-in-magento-commerce/) to see the paths of the blocks in the frontend and considered this useful because it facilitated the development.

Then I implemented something in the CI, if it is in the development environment will have a button in the debugbar allowing to see the path of the views.

I want to open a PR for you to analyze, just tell me what you think I'll end later and send the PR.

  Thanks!
![captura de tela de 2017-10-06 11-50-09](https://user-images.githubusercontent.com/3011423/31283696-b4ec94b8-aa8c-11e7-9b0c-b7419da8a2d4.png)

![captura de tela de 2017-10-06 11-50-15](https://user-images.githubusercontent.com/3011423/31283706-bb3f4342-aa8c-11e7-83b8-01f809a0b427.png)

**Comment by lonnieezell** [comment]
Now that you bring this up, this is actually something that I remember wondering how tough it would be to do, but never looked into. I'd be very interested in seeing what you came up with for this.
