### ISSUE TITLE
DebugBar Routes Collector throws ErrorException when optional parameter is not passed to controller

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#762]
Calling a controller method:
 
`    public function edit($id = NULL) {`

without specifying the optional parameter $id like in http://localsite/admin/article/edit

throws ErrorException with the white screen of death if the debug bar is active.

The same error was reported in the forum by user qury
https://forum.codeigniter.com/thread-67555.html

This is what I've been able to debug so far...

Undefined offset: 0	in 
BASEPATH/Debug/Toolbar/Collectors/Routes.php line 99   

`var_dump($rawParams);
`
array(1) {
        [0]=>  object(ReflectionParameter)#308 (1) {
        ["name"]=>  string(2) "id" }
 }

`var_dump($router->params());`
array(0)

**Comment by lonnieezell** [comment]
How is your route defined?
