### ISSUE TITLE
Bug: segment not passed on to controller class function in documented routing example

### ISSUE THREAD

**Issue by jonniestuefer** [bcit-ci/CodeIgniter4#7623]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

This routing example from the documentation does not work as expected:
`$routes->get('product/(:segment)', 'Catalog::productLookup');` ([from URI Routing - Examples- setting routing rules](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#examples))
The segment does not get passed to the Catalog::productLookup function.

### Steps to Reproduce

1) Install Codeigniter
2) Create the 'Catalog' controller with the 'productLookup()' function which takes one parameter (the :segment) and output that parameter
3) Add the route `$routes->get('product/(:segment)', 'Catalog::productLookup');` to the Config\Routes.php file
4) visit the url and see that the parameter is empty

### Expected Output

The :segment parameter should be passed to the function Catalog::productLookup and output.

### Anything else?

The following variations do work:

Specifying `$1` in the second argument:
- `$routes->get('product/(:segment)', 'Catalog::productLookup/$1');`

Using the 'Array Callable Syntax':
- `$routes->get('product/(:segment)', [\App\Controllers\Catalog::class, 'productLookup']);`

**Comment by michalsn** [comment]
I see no issue.

```php
$routes->get('product/(:segment)', 'Catalog::productLookup');
```

is working fine, as described in the [user guide](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#examples)

> A URL with product as the first segment, and anything in the second will be mapped to the \App\Controllers\Catalog class and the productLookup() method:

So if you want to read the parameter part you have to do it manually:

```php
$this->request->getUri()->getSegment(2);
```

---

As for "Array Callable Syntax" this is also documented: https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#array-callable-syntax and working as expected. Any placeholder is automatically translated into a parameter.

**Comment by jonniestuefer** [comment]
Thanks for checking it out and sorry for wasting your time.

**Comment by michalsn** [comment]
No worries.
