### ISSUE TITLE
Undefined property: Config\App::$errorViewPath

### ISSUE THREAD

**Issue by anrip** [bcit-ci/CodeIgniter4#765]
Displayed at 12:12:06pm — PHP: 7.1.9 — CodeIgniter: 4.0-dev

ErrorException
Undefined property: Config\App::$errorViewPath	search →
BASEPATH/CodeIgniter.php at line 805

798         // Show the 404 error page
799         if (is_cli())
800         {
801             require  $this->config->errorViewPath . '/cli/error_404.php';
802         }
803         else
804         {
805             require  $this->config->errorViewPath . '/html/error_404.php';
806         }
807 
808         $buffer = ob_get_contents();
809         ob_end_clean();
810 
811         $this->response->setBody($buffer);
812         $this->response->send();

**Comment by lonnieezell** [comment]
@anrip Is this using the very latest code?

**Comment by jaynarayan89** [comment]
@lonnieezell  yes, i am geting this error too. after merging with latest code.

**Comment by jaynarayan89** [comment]
latest commit in my fork is 6eedefb  (a day ago)

**Comment by anrip** [comment]
yes， last code

**Comment by deathart** [comment]
Can you show us the code of the Application/Config/Exceptions.php file?

**Comment by anrip** [comment]
```
<?php namespace Config;

/**
 * Setup how the exception handler works.
 *
 * @package Config
 */
class Exceptions
{
	/*
	 |--------------------------------------------------------------------------
	 | LOG EXCEPTIONS?
	 |--------------------------------------------------------------------------
	 | If true, then exceptions will be logged
	 | through Services::Log.
	 |
	 | Default: true
	 */
	public $log = true;

	/*
	 |--------------------------------------------------------------------------
	 | DO NOT LOG STATUS CODES
	 |--------------------------------------------------------------------------
	 | Any status codes here will NOT be logged if logging is turned on.
	 | By default, only 404 (Page Not Found) exceptions are ignored.
	 */
	public $ignoreCodes = [ 404 ];

	/*
	|--------------------------------------------------------------------------
	| Error Views Path
	|--------------------------------------------------------------------------
	| This is the path to the directory that contains the 'cli' and 'html'
	| directories that hold the views used to generate errors.
	|
	| Default: APPPATH.'Views/errors'
	*/
	public $errorViewPath = APPPATH.'Views/errors';
}
```

**Comment by chistel** [comment]
the issue is codeigniter.php uses the config property "$this->config->errorViewPath " from \Config\App.
so get it fixed, a possible merging of property from \Config\App and \Config\Exception or returm that property to it previous place. or call the exception config seperately where required.

**Comment by lonnieezell** [comment]
Yup, only happens with 404Overides in place, by the looks of it. Will look at it closer tonight, hopefully, but looks like we should be throwing a PageNotFoundException there and letting the exceptions class handle it.

**Comment by jaynarayan89** [comment]
@chistel  Your are right. I tested with a fresh install and get the same error. when I created public $errorViewPath = APPPATH.'Views/errors' in Config\app then it works.  codeigniter.php is trying to access  errorviewpath property on instance of \config\app but the property does not exists.

what do you mean by "a possible merging of property from \Config\App and \Config\Exception or returm that property to it previous place. or call the exception config seperately where required." ?

both  property $config and $viewpath of   \CodeIgniter\Debug\Exceptions is protected so cant be used in codeigniter.php
