### ISSUE TITLE
Class 'App\Models\NewsModel' not found

### ISSUE THREAD

**Issue by marcos-queiroz** [bcit-ci/CodeIgniter4#766]
Good morning, is anyone already testing CI4?

I followed the tutorial https://bcit-ci.github.io/CodeIgniter4/tutorial/index.html

I'm having trouble trying to use the Model, I'm getting the error that the Model class could not be found. As in this new version of CI the mode of how we loaded the Model has changed, I wonder if anyone has had the problem and solved it.

Thank you very much in advance

**Comment by jaynarayan89** [comment]
@marcos-queiroz  We need to see your code. It would be batter to create a topic on ci4 forum and post your code there. You will get help there quickly. In my humble opinion this is not the right place for asking support.

**Comment by lonnieezell** [comment]
@jaynarayan89 is correct. These forums are for new feature planning and bug-reporting. Please take questions to the forums. You'll find a number of people there already fairly familiar with CI4 that can help you out.
