### ISSUE TITLE
redirect()->to() problem with output buffering

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#769]
I have an AdminController class that all the rest of the controllers will extend.
in the constructor of  AdminController I check if the user is already logged, otherwise...

`redirect()->to('/admin/user/login');`

but it doesn't get redirected, even though I see the 'Location;' header sent to the browser correctly.
Seems to be a problem with the output buffering

For it to work I should do

```
redirect()->to('/admin/user/login');
ob_end_flush();
```
should we make the redirect()->to() method call ob_end_flush()?

Thanks in advance!

**Comment by lonnieezell** [comment]
Well, it's designed to be returned not just ran, so `return redirect()->to(...)`. However, I didn't think of testing it within a constructor so not 100% sure if it will work correctly in that situation. However, I think [filters](https://bcit-ci.github.io/CodeIgniter4/general/filters.html) might be just what you're looking for.

**Comment by gustavojm** [comment]
Initially I was using `return redirect()->to('/admin/user/login');` but it didn't redirect. It returned to the constructor of the child class and kept executing the code of the controller.
That's why I had to remove the `return` statement, to be able to execute the `ob_end_flush()` after that

**Comment by lonnieezell** [comment]
Gotcha, and that's what I was afraid of. So, that's something I'll take a look into in the near future.

Filters, however, were designed for exactly what you're trying to do.

**Comment by demortx** [comment]
Debug off -> work redirect()->to(...)
