### ISSUE TITLE
about where(null)

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#770]
The null parameter cannot be passed in the where method
Like this

`$db->table('test')->where(null)->get()->getRow();`

Run error reporting

**Comment by JakeAi** [comment]
@jinmarcus Why do you need to do this?

**Comment by jinmarcus** [comment]
Ci3 can be, I have been accustomed to write, because you can write functions, $where can be as a parameter by value, if there is no $where you can pass null, now to determine $where exists, is not very convenient

CI3 like this

```
public function getSort($db, $where = null, $order = 'id desc') {
        return $this->db->select('sort')
                            ->order_by($order)
                            ->where($where)
                            ->get()
                             ->result();
}
```


but now, CI4 like this

```
public function getSort($db, $where = null, $order = 'id desc') {
        $this->db->table($db)
                        ->select('sort')
                        ->orderBy($order);

        if ($where !== null) {
            $this->db->where($where);
        }

        return $this->db->get()
                                  ->getResult();
}
```

This way, it doesn't get smooth！
and getWhere(null) is ok ,why where(null) not?

**Comment by lonnieezell** [comment]
Hm. I didn't think we changed anything in those query builder methods. I would accept a PR for this, though.

**Comment by jinmarcus** [comment]
https://github.com/bcit-ci/CodeIgniter4/pull/792
