### ISSUE TITLE
Ignore_value should be the value of ID, how do I get it?

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#772]
In the model file

```
protected $validationRules = [
    'css' => 'required|is_unique[dbname.css, id, ignore_value]'
 ];
```

Ignore_value should be the value of ID, how do I get it?

**Comment by gustavojm** [comment]
Something like this:

protected $validationRules = [
    'css' => 'required|is_unique[dbname.css, id, '. $this->request->input->getPost('id'). ' ]'
 ];

**Comment by lonnieezell** [comment]
That's a rule that might be better done in the controller itself, honestly. There are times when 2 layers of validation is a good thing, and you might find that you prefer it all in the controller. Personally, I do validation in the model just to ensure it's valid data. In the controller is validation that determines whether it should be allowed to be stored. In the controller it's also easier to catch the validation issues and redirect back.

**Comment by jinmarcus** [comment]
I know in controller is ok, but I like to write the basic logic only in the controller, and pass the database processing to the model. If the model can't get the value of ID, then the model becomes meaningless.

**Comment by lonnieezell** [comment]
If you have suggestions on how to handle that, I'm open to hearing them.

**Comment by jinmarcus** [comment]
In the model.php page, automatically retrieve the ignored values instead of passing the ignored values.
