### ISSUE TITLE
How do you access the $this bound data of the controller in the view? Ci3 is OK, ci4 doesn't seem to work

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#775]
How do you access the $this bound data of the controller in the view? Ci3 is OK, ci4 doesn't seem to work

**Comment by jinmarcus** [comment]
such as ci3's get_instance

I can use the global $this anywhere in the controller, model, view in CI3, but ci4, I can't use the global $this in the view, the model, which worries me

**Comment by jaynarayan89** [comment]
get_instance is not available because there is no "super object" aka singleton is present in ci4. In my humble opinion this is not a bug and you should take your question to the ci4 forum.

**Comment by jinmarcus** [comment]
The feedback from the forum is a bit slow

https://forum.codeigniter.com/thread-69145.html

**Comment by jim-parry** [comment]
THis was a design decision early in the CI4 development. This is a feature, not a bug.
If you wish to argue for it, the forum is the proper place, slow or not.
