### ISSUE TITLE
$this->CI->request->getIPAddress() protected

### ISSUE THREAD

**Issue by demortx** [bcit-ci/CodeIgniter4#776]
use \App\Libraries;
Controllers -> new \Authentication($this);

$this->CI->request->getIPAddress() Cannot access protected property App\Controllers\Main::$request

how to get ip?

**Comment by deathart** [comment]
"$this->CI" equals what?

My code : 

`$this->request = \Config\Services::request();
$this->request->getIPAddress()`

**Comment by InsiteFX** [comment]
There is no more CodeIgniter Super Object.

**Comment by jim-parry** [comment]
Asked & answered on the forum.
