### ISSUE TITLE
Validation issue and routing issue

### ISSUE THREAD

**Issue by maczdata** [bcit-ci/CodeIgniter4#782]
notice querystring like "jobs/type?[]=" does not work and also the validation library does not validate array input like "job[owner]"

**Comment by lonnieezell** [comment]
Please provide more details about how you're trying to use them. I'll have to dig into code later, but square brackets are typically considered unsafe within a uri. [Here's a good article](https://perishablepress.com/stop-using-unsafe-characters-in-urls/) explaining it with links to the original RFC.

Validation - you might be right. I thought we had that in there, but I don't see any tests in place for that. Will have to check on that.

**Comment by maczdata** [comment]
for the square bracks, i want  to pass an array of values from a get request using check boxes, which is to be used in the controller.
when the form is submitted, a get a blank page with and error title, no debug trace inclusive, and the toolbar becomes unresponsive.

**Comment by maczdata** [comment]
what if the square brackets is encoded, does it make it safe to use??

**Comment by lonnieezell** [comment]
yes, encoding makes it safe. The URI class should take care of that for you, I believe. Another option is to use a comma-separated list and turn it into an array elsewhere.

**Comment by lonnieezell** [comment]
I'm assuming you're building the URI through javascript, so you build a URI out of the selected options something like `jobs/type?options=developer,designer`. 

Looking back on your actual issue, though - what was the actual error generated? You might need to check logs for it.

**Comment by maczdata** [comment]
No JavaScript included, and it does not return anything in the log.
