### ISSUE TITLE
Bug: Lang strings not work if that string ends with the dot (.) and at least two levels deep.

### ISSUE THREAD

**Issue by nalakapws** [bcit-ci/CodeIgniter4#7960]
### PHP Version

8.0

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

PostgreSQL 10

### What happened?

Test.php (Lang string file).

```php
<?php

return [
    'level_one' => [
        'level_two' => [
            'The string with the dot at the end.'
                => 'The string with the dot at the end.'
        ]
    ]
];

```

In the view file.

```php
<?= lang('Test.level_one.level_two.The string with the dot at the end.') ?>
```

The output.

```html
Test.level_one.level_two.The string with the dot at the end.
```

The expected output.
```html
The string with the dot at the end.
```

This only happen when the lang string key and the value two levels deep in the lang array and has the dot (.) at the end of lang key. Without the dot (.) it's works fine. But this issue only happening when the lang array element at least two levels deep.

### Steps to Reproduce

Info given

### Expected Output

Info given

**Comment by neznaika0** [comment]
This is not a bug. When your key has a dot at the end, the parser expects an array. 
```php

<?php

var_dump(explode(".", "File.with.dot."));

array(4) {
  [0]=>
  string(4) "File"
  [1]=>
  string(4) "with"
  [2]=>
  string(3) "dot"
  [3]=>
  string(0) ""
}
```

He's waiting for the key at the end.
 I would not recommend using phrases instead of keys

**Comment by nalakapws** [comment]
"But if that string is only one level deep, then it works just fine. I have many strings like that in my app, and they all work fine. This is the first time I've encountered a string that is two levels deep.

**Comment by nalakapws** [comment]
Yes it does. I have hundreds of strings thats ends with a dot.

Lang array element
```php
'alerts' => [
    'Fields marked with {0}*{1} are required.'
         => 'Fields marked with {0}*{1} are required.'
]
```
In the view file.
```php
<?= lang('Users.alerts.Fields marked with {0}*{1} are required.', ['<span class="text-danger">', '</span>']) ?>
```

How its display
![Screenshot_14](https://github.com/codeigniter4/CodeIgniter4/assets/30935025/a3dd582c-a038-4f26-b04a-d2a8cbf34d84)

I think this is a bug.

**Comment by neznaika0** [comment]
What do you expect when there are several dots in a phrase? Maybe you should reconsider the "with a dot at the end" approach?

I can't check the code now, I don't have a PC

**Comment by kenjis** [comment]
In the documentation, there is no example that a key ends with a dot.
https://codeigniter4.github.io/CodeIgniter4/outgoing/localization.html#creating-language-files

And dots are used for dot array syntax. So a key should not end with a dot.
It seems https://github.com/codeigniter4/CodeIgniter4/issues/7960#issuecomment-1729970923 is a bug.

**Comment by nalakapws** [comment]
Yeah! I will use [dot] for dots in the lang keys.
Thanks!

**Comment by kenjis** [comment]
@nalakapws Sorry, we use dot as a meta character in this case, so we probably don't support dot as a literal dot in a key.
Because if we do it, it is not consistent or confusing.

You have options:
1. Extend Language class
2. Remove the last dot in the key
3. Use gettext instead of CI4 Language class

**Comment by kenjis** [comment]
I found this package:
https://github.com/michalsn/codeigniter-gettext

**Comment by kenjis** [comment]
@nalakapws Paul made a fix for you. #8104

But, I agree with this.
> The examples in the user guide indicate that the language files should contain a key and a string for that key. The key was never designed to hold a complete sentence.
https://github.com/codeigniter4/CodeIgniter4/pull/8104#pullrequestreview-1702746709

Using a sentence as a key is never designed, and a sentence might contain dot in it not in the end.
E.g., "Dr. Smith is a doctor."
If a sentence includes a dot, it won't work.

**Comment by nalakapws** [comment]
@kenjis  @paulbalandan Thanks for both of you. This is a great addition for sure.
