### ISSUE TITLE
Routing problem /sth-abc->App:sth/foo (ok)    and   /sth/abc->App:sth/foo (nok)

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#799]
I tried to use normal strings instead of parameters ($1) in controller calling. 
$routes->get('/sth-abc',                       'App::sth/foo',  ['subdomain'=>'']);
$routes->get('/sth/abc',                       'App::sth/foo',  ['subdomain'=>'']);

In the  case route is defined as: '/sth-abc',  everything works as expected - www.host.com/sth-abc shows page returned by App::sth with foo as first parameter. In the second case when route is '/sth/abc'  www.host.com/sth/abc returns 404.

I'm not sure if it is bug, because there is no example like this in docs but it can be a useful feature.

**Comment by lonnieezell** [comment]
I thought we had fixed it, but there might be a bug still in the routing that doesn't like have a leading slash in the "from" portion of the route. Try rewriting that more like this: 

```
$routes->get('sth/abc', 'App::sth/foo', ['subdomain'=>'']);
```
