### ISSUE TITLE
Feature - CLI Prompt with Validation

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#800]
Hello!

Today I was testing the CLI and it is awesome. 😄 

Then I created a [Command](https://github.com/natanfelles/CodeIgniter4/commit/4b9ccdc1edb67bc9c9930ab137f9fa344fd6540f) to insert/update values in a DB table or simply to get validated data.

I see that the `prompt()` validates *required* and *in_list* values. Then I thought about to use the full Validation Library Rules and implemented [some adjusts](https://github.com/natanfelles/CodeIgniter4/commit/4275ddfc4c75beb04e3488149a61a0a1ac649c68).

With this is possible continue to prompt until the input be valid:

```php
$email = CLI::prompt2('Email', null, 'required|valid_email');
```

If you think that this can be useful do some analysis in the latest commits of [this branch](https://github.com/natanfelles/CodeIgniter4/commits/cli_prompt_validation).

**Comment by lonnieezell** [comment]
I like this! I would definitely accept that as a PR - but not as a new method. Just redo the existing `prompt()` method.

**Comment by natanfelles** [comment]
Coding on #808
