### ISSUE TITLE
Create a skeleton system for codeigniter

### ISSUE THREAD

**Issue by You85** [bcit-ci/CodeIgniter4#806]
Create a skeleton system for codeigniter with a frondend part (a home page, a contact page)
and a backend part with a basic administration that manages the users.
Indeed, it would be interesting for new developers to have a pre-built base to better understand the system.
it will be a great way to start with CodeIgniter 4.

**Comment by InsiteFX** [comment]
This should be posted in the CodeIgniter Forums not here, this is for reporting bugs to the new CodeIgniter. Besides users will create it and post it when it is released.

**Comment by jim-parry** [comment]
Agreed. Lonnie already has blog entries addressing samples like this.
