### ISSUE TITLE
Error changing databases CodeIgniter\Database\MySQLi\Connection::dbSelect()

### ISSUE THREAD

**Issue by skunkius** [bcit-ci/CodeIgniter4#813]
Hi to all!

I've tried to change my database according to docs (... $db->dbSelect($database2_name) ...), got error:

`Call to undefined method CodeIgniter\Database\MySQLi\Connection::dbSelect()`

If I try `$this->db->setDatabase('my_other_database')`, I've got error too:

`Call to a member function select_db() on boolean`

Soooo, changing databases is not working.

**Comment by samsonasik** [comment]
@skunkius I've created PR #814 for it, please test if that fixes the issue.

**Comment by skunkius** [comment]
Yes, it works!
