### ISSUE TITLE
Question about Filters

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#824]
Currently a Controller Filter have this skelleton:

```php
<?php namespace App\Filters;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use CodeIgniter\Filters\FilterInterface;

class MyFilter implements FilterInterface
{
	public function before(RequestInterface $request)
	{
		//
	}

	public function after(RequestInterface $request, ResponseInterface $response)
	{
		//
	}
}
```

What about to update for something like:

```php
<?php namespace App\Filters;

use CodeIgniter\HTTP\IncomingRequest;
use CodeIgniter\HTTP\Response;
use CodeIgniter\Filters\FilterInterface;

class MyFilter implements FilterInterface
{
	public function before(IncomingRequest $request)
	{
		//
	}

	public function after(IncomingRequest $request, Response $response)
	{
		//
	}
}
```

**Motive:** We will can use all methods of the IncomingRequest and Response. I think that the interfaces only are a little limited in this place.

**Comment by lonnieezell** [comment]
You can still use all of the methods in the IncomingRequest and Response class as is. By specifying the Interfaces, it just means that ANY class that implements that interface can be passed in. This is needed to make sure a Filter can be used for CLI requests, also. Or that you can extend the IncomingRequest class to customize something, and still have that work.

**Comment by natanfelles** [comment]
Hahah, of course.

This is what happens when one depends a lot on code completion.

I was trying here but the methods that appear are just from the *RequestInterface*. But the *IncomingRequest* class are there, too.

![captura de tela de 2017-11-09 18-50-26](https://user-images.githubusercontent.com/3011423/32629002-e2a3132a-c57e-11e7-93a8-efe0b099df0a.png)

Many thanks, @lonnieezell .

**Comment by lonnieezell** [comment]
Yeah, I thought it might have been something like that :) No worries.
