### ISSUE TITLE
Display Label on Form Validation

### ISSUE THREAD

**Issue by FlavioCesarino** [bcit-ci/CodeIgniter4#826]
I want to request the following resource.

In CodeIgniter 3, I used this to display the label name in form validation

`$this->form_validation->set_rules('first_name','First Name','required'); `

In CodeIgniter 4, I am not able to do this.

`$validation->setRule('first_name', 'required');
$validation->setRules(['first_name', 'required']); `

These options do not work.

I do not want to display the field name.
I want to display the label name.

**Comment by jim-parry** [comment]
Ok, so you are on your second post on the forum, and now an "issue" here. I gather you are desperate for this feature?
You could always submit a PR, but multiple posts on the two forums is annoying!

**Comment by FlavioCesarino** [comment]
I posted this in the forum, now I'm posting here.
  kilishan, recommended me to post here to analyzear subject

**Comment by natanfelles** [comment]
Duplicated #696

**Comment by FlavioCesarino** [comment]
This is exactly what I want.
