### ISSUE TITLE
Bug: Validation is_unique not working

### ISSUE THREAD

**Issue by stalker1980** [bcit-ci/CodeIgniter4#8289]
### PHP Version

8.1

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

5.7.44 - MySQL

### What happened?

Hi, guys!

'rules' => 'required|min_length[2]|is_unique[languages.code,id,{id}]'
When I send data from a form, a LogicException is thrown in
![Screenshot_1](https://github.com/codeigniter4/CodeIgniter4/assets/67198890/1a1aaf1e-6fe3-407e-872b-a733ade5daf7)
in this line code method retrievePlaceholders 
![image](https://github.com/codeigniter4/CodeIgniter4/assets/67198890/2db4d496-4b32-48d3-a287-4ad3ead5867c)
return me value
$placeholderFields array (1)
0 => string (2) "id"
and in this line code it null, in array with rules 
![image](https://github.com/codeigniter4/CodeIgniter4/assets/67198890/8acb6c7a-a68a-42ca-8428-795e7e9e54a0)

### Steps to Reproduce

Nothing

### Expected Output

Nothing

**Comment by kenjis** [comment]
This is not a bug. It is intentional.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
