### ISSUE TITLE
Unable to install Codeigniter using composer

### ISSUE THREAD

**Issue by rrajesh011** [bcit-ci/CodeIgniter4#829]
Here is the output when i run composer command

D:\xampp\htdocs>composer create-project codeigniter4/framework

  [InvalidArgumentException]
  Could not find package codeigniter4/framework with stability stable.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by lonnieezell** [comment]
Well - the framework is still very much in alpha-level development, so you won't be able to get a "stable" version  of the framework yet. 

Plus - we just got the codeigniter4/framework package switched over to us from another user, so you'll have to wait until a little more work has been done on this.

**Comment by rrajesh011** [comment]
Thanks for quick reply @lonnieezell

**Comment by cube76** [comment]
> Well - the framework is still very much in alpha-level development, so you won't be able to get a "stable" version of the framework yet.
> 
> Plus - we just got the codeigniter4/framework package switched over to us from another user, so you'll have to wait until a little more work has been done on this.

so what I need to do to make a project?
