### ISSUE TITLE
Validation - permit_empty

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#830]
On CI 3, input data sent with blank values are accepted by Form Validation.

For example: 

If exists rules to a email field like it: `valid_email|is_unique[users.email]`, the validation accepts blank values, a string `''`. Of course `''` is not a valid_email. I believe that the validation must fail. But I see that this also occurs in others frameworks, accepting '' as a valid email, if is not set the `required` rule for example.

On CI 4 it is not happening. If the user send `''` and exist a `valid_email` then the validation show the error. Because `''` is not a valid email. I think this a best way to validate.

If the user do not send the field email (think about an API) and it have not the `required` rule, then the validation pass. But if he send a blank value the Validation show the error... OK.

But a third use case, and common. And, what about if is possible to receive an empty value? Having the `valid_email` rule the Validation do not accept `''`.

An possible solution, I think, could be an rule to permit this use case. Like a `permit_empty`, that would cancel all other field rules if the value is empty.

If what I tried to explain could be confuse, please see:

- A thread about that in the forum: https://forum.codeigniter.com/thread-69173.html
- An example usage in CI 4: https://youtu.be/lmAPsJDthFA?t=3245

**Comment by lonnieezell** [comment]
Laravel has something similar, the `sometimes` rule. In this described case, though, and blank string equates to "empty", and is likely what the user would get back from the form. I don't have problems with this idea, but if we're going to allow empty should probably allow all version of empty, including a blank string.

**Comment by natanfelles** [comment]
The first thing to think can be: *Then the required rule is not necessary?* Yes. It is. But means **required** could hold the field and not the value.

If is required, then the field MUST be sent. And can be an empty string if is accepted. But the field MUST be sent.

**Comment by natanfelles** [comment]
Yes. I believe that an `null` value could be sent/accepted. But the field of this empty value must be received (if required).

**Comment by natanfelles** [comment]
I did not know the `sometimes` rule. But, yes, according to [this question](https://stackoverflow.com/questions/35196715/laravel-sometimes-validation-rule#answer-35197043) is the same thing that I think about.

**Comment by natanfelles** [comment]
Related to #614
