### ISSUE TITLE
when set cache to file, when get a error

### ISSUE THREAD

**Issue by anrip** [bcit-ci/CodeIgniter4#836]
$config->path will be setted the system path

> ErrorException
is_writable(): open_basedir restriction in effect. File(C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps/) is not within the allowed path(s): (D:/xServer-nmp/webroot/;D:/xServer-nmp/storage/php71/)

**Comment by InsiteFX** [comment]
You need PowerShell to be setup as Administrator

**Comment by lonnieezell** [comment]
This is not a framework error.
