### ISSUE TITLE
Moved uploaded files doesn't retain new filename.

### ISSUE THREAD

**Issue by JakeAi** [bcit-ci/CodeIgniter4#839]
Once an uploaded file has moved and has an integer appended on the end for allowing multiple of the same files... the file object does not retain the new filename. In the function [move()](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Files/File.php#L169) it calls [getDestination()](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Files/File.php#L201) which can create a new filename and return a new path to move to. But the new filename does not get saved, it is used to move the file, and then gone. @lonnieezell I don't really know how you'd want to address this, other than reparsing the new path from getDestination... Just seems redundant. 

```PHP

if (!$this->file->move( $path, $this->file->getName(), true )) {
	throw new \ErrorException( "An error occured uploading your file." );
}

$this->file->getName(); // fails

```

Also I think this [ternary operation](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Files/File.php#L173) needs flippe.

```PHP
/**
 * Returns the destination path for the move operation where overwriting is not expected.
 *
 * First, it checks whether the delimiter is present in the filename, if it is, then it checks whether the
 * last element is an integer as there may be cases that the delimiter may be present in the filename.
 * For the all other cases, it appends an integer starting from zero before the file's extension.
 */

$destination = $overwrite ? $this->getDestination($targetPath . $name) : $targetPath . $name;
//$destination = true ? true : false;

```

**Comment by JakeAi** [comment]
**From this**

```PHP
	public function move(string $targetPath, string $name = null, bool $overwrite = false)
	{
		.......................
		$destination = $overwrite ? $this->getDestination($targetPath . $name) : $targetPath . $name;
		.......................
		// Success, so store our new information
		$this->path = $targetPath;
		$this->name = $name;
		$this->hasMoved = true;

		return true;
	}
```

**to this**
```PHP
	public function move(string $targetPath, string $name = null, bool $overwrite = false)
	{
		.......................
		//Flip ternary operation
		$destination = !$overwrite ? $this->getDestination($targetPath . $name) : $targetPath . $name;
		.......................
		//**Reparse the new file from the new destination, works on my end**
		$newFile    = pathinfo( $destination );
		$this->path = $newFile['dirname'];
		$this->name = $newFile['basename'];
		$this->hasMoved = true;

		return true;
	}
```

**Comment by lonnieezell** [comment]
For file name we do need to save the name after determining the destination since the docs state: 

> If the file has been moved, this will return the final name of the moved file

I would update the filename with `basename()` from the destination variable we get so that it can be saved back to the class. Should take care of it. 

As for overwriting and flipping the ternary: it would have been nice if you would have given the logic for _why_ you wanted it flipped :) Took me a second, but yes, you're correct that should be modified otherwise overwriting won't actually work.

**Comment by JakeAi** [comment]
After more testing I did read the docs and saw that it returns a new instance of the file. So I ended up not digging into a fix since I am still developing. As for the ternary, I assumed since I was looking at it for an hour that other people would understand xD. But you're right, I didn't document the logic well at all.
