### ISSUE TITLE
New Toolbar Collector for Events

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#84]
Should show event name and timing, both in it's own tab and in the timeline.

Development Checklist:
- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by filisko** [comment]
Hi @lonnieezell,
What about 4 columns like the ones I have in the image? (Time, Event, Priority and Times Triggered).

![Image Events Collector](https://i.snag.gy/OEu5y3.jpg)

I just started working on this (so don't pay too much attention to what you see).

**Comment by lonnieezell** [comment]
@filisko I think that's a good start. Ideally, it would be awesome to be able to expand each row and see the data that was passed to each event. That, I think, would be quite helpful. Unfortunately, there's no mechanism yet for the expanding rows. It's on my wishlist for the toolbar, but haven't made it there yet :)

**Comment by ranjithsiji** [comment]
@filisko this is a very good idea to have in the debug bar. 👍

**Comment by filisko** [comment]
Sorry that I didn't too much time for this. I got back to this today.

@lonnieezell, should I try to do a PR once I've got the 'Time' column working and the tests added?

Thank you @ranjithsiji.

**Comment by lonnieezell** [comment]
@filisko yes, a PR is exactly correct.

**Comment by filisko** [comment]
Hi @lonnieezell,
- Does 'DBQuery' event need to be shown at all in the Events toolbar collector? Isn't just enough with the 'Database' section?
- Should we show the events that don't have any registered action (Events::on()) but that were triggered?
- Should we rename 'post_controller_constructor' event to something like ... 'postControllerConstructor' ?

**Comment by lonnieezell** [comment]
@filisko Good questions. 

1. No, don't need to include DBQuery events. Primarily interested in user-generated events. 
2. Yes, I think we should show all events. That will help be a trigger to developers looking to see if all of their events are firing.
3. Probably should. Which means all system events should be renamed (with docs updated). I think there are a grand total of 4).

Thanks!

**Comment by filisko** [comment]
@lonnieezell, is it good idea to trigger events inside the Events class?

**Comment by lonnieezell** [comment]
Initial thought is, "No", but would need more details.

**Comment by filisko** [comment]
so directly call to the Events Collector from the Events class on dev environment is the solution?

**Comment by lonnieezell** [comment]
Oh, I see what you're saying. Yes, I think so. Otherwise I can see it getting into a loop and never getting out.

**Comment by filisko** [comment]
Yes !!!! You totally got it! I thought that it would take you more time to realize that lol :smile: 
Thank you!

**Comment by lonnieezell** [comment]
:) Was I doing that in the code or something?
