### ISSUE TITLE
Session in filter

### ISSUE THREAD

**Issue by deathart** [bcit-ci/CodeIgniter4#840]
Hello,

I just noticed that the sessions in the filters are not working properly
Already when I make a $this->session->get () it returns me an empty array when it must have 7 results 

If I do just before a $this->session->start () and a $this->session->get () it returns it to me:
ini_set (): A session is active.  You cannot change the session module's ini settings at this time

On the other hand, if I do a $this->session->start () and a dd ($this-session->get ()) the 7 results are returned to me.

**Comment by puschie286** [comment]
well, to use the session data you have to initialize it first by call session()->start() before any header is set ( "To use cookie-based sessions, session_start() must be called before outputing anything to the browser. " ) [Ref](php.net/manual/en/function.session-start.php)
i call it in the controller constructor
or you set session.auto_start to true in php.ini ( [Ref](http://php.net/manual/en/session.configuration.php#ini.session.auto-start) )
so i guess its not a bug - but we could implement a check in get if the session has started ( [Ref](http://www.php.net/manual/en/function.session-status.php) )

**Comment by deathart** [comment]
The problem is that it doesn't matter where I enable session-start the result and the same, whether in my controller or the filter ah know that in my filter I call a library, and that in this library it's the same thing.

**Comment by deathart** [comment]
The problem came from me, I just realized that I was doing a start session in another one of my libraries.

**Comment by puschie286** [comment]
Are you sure that your libary does not call header() or echo something ? Can you name your libary so we can do some test ( or provide a code example )
  

  
I remember i had similar issue that was cause by error in my php.ini with in the session settings.
  

  
  

  
  
>
