### ISSUE TITLE
There is something wrong with ViewTest::testRenderScrapsDataByDefault

### ISSUE THREAD

**Issue by vinodselvin** [bcit-ci/CodeIgniter4#846]
ViewTest::testRenderScrapsDataByDefault 

asserts 
$this->assertTrue(empty($view->getData()));

 it has be not empty

$this->assertTrue(!empty($view->getData()));

**Comment by lonnieezell** [comment]
Yup. Am aware. That's because I changed the default way that acts and forgot to change the test. Will get to it soon :)

**Comment by vinodselvin** [comment]
I guess due to that all my pull requests are failing, see here https://github.com/bcit-ci/CodeIgniter4/pull/845
