### ISSUE TITLE
Use PHP 7.0 or 7.1 typehints?

### ISSUE THREAD

**Issue by TomasVotruba** [bcit-ci/CodeIgniter4#847]
@Paradinight referenced me here from
https://github.com/bcit-ci/CodeIgniter/pull/5341#issuecomment-347300338

Is there any need for typehints and/or bumping to PHP 7.1?

**Comment by lonnieezell** [comment]
I'd love to go ahead and push this to 7.1 minimum, especially after seeing the gophp7.1 push. 

Would love the help on that.
