### ISSUE TITLE
Config Unexpectedly Being Overwritten by $_ENV variable

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#853]
In my setup, I apparently have a generic $_ENV['PATH'] variable that's being set automatically. This is causing problems with the Cache::$path variable and is overwriting the default value which is what I want. This seems like it may be a common issue for folks since the default in the getEnvValue method doesn't have any namespacing/prefix. A work around for me was to set a "cache.path" in my .env.

**Comment by zl59503020** [comment]
Me too, in the windows environment

**Comment by lonnieezell** [comment]
Fixed with e83d18f0214a118d2d660921453e078175bd34ba
