### ISSUE TITLE
Problem with using Entity class (Could not execute App\Entities\::__construct())

### ISSUE THREAD

**Issue by stefanaminb** [bcit-ci/CodeIgniter4#855]
Problem with using Entity class (system\Entity.php: 72). 
Could not execute App\Entities\Client::__construct()

The Database class cant use fetch_object with this constructor

`public function __construct(array $data = null)
	{
		if (is_array($data))
		{
			$this->fill($data);
		}
	}`

**Comment by stefanaminb** [comment]
On remove the constructor it works.

**Comment by lonnieezell** [comment]
Please show how you're using it and creating it. I use the Entity class in sample projects just fine.
