### ISSUE TITLE
Suggestion regarding codeigniter 4

### ISSUE THREAD

**Issue by bawasaab** [bcit-ci/CodeIgniter4#856]
Dear CI devs congratulations for CI4 from the bottom of my heart. 

As the php 7.1 have huge performance comparatively to php 5.x there is a new project for asynchronous  php on github which is equivalent to Nodejs. 

please find below official link
https://reactphp.org/

github repos:
https://github.com/reactphp

framework equivalent to express.js
https://github.com/CapMousse/React-Restify

please have a look so the CI4 can be able to use full asynchronous features of php within the framework. 

you did nice job as always.

with regards,
deepak bawa

**Comment by jim-parry** [comment]
I see you have raised this as a thread on our forum, which is the proper place for suggestions.
