### ISSUE TITLE
Catch in Controllers/Checks.php

### ISSUE THREAD

**Issue by engineer89** [bcit-ci/CodeIgniter4#859]
Hi, 

Netbeans give me error because of naming the function "catch".

The issue is in "application/Controllers/Checks.php" in line 300 at the current state.

`public function catch() {`

**Comment by lonnieezell** [comment]
Well - that is a temp controller so it will eventually disappear. :) 

That being said - we've seen this before and it's an issue with NetBeans and reserved keyword detection.
