### ISSUE TITLE
When codeigniter 4 will be released ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [bcit-ci/CodeIgniter4#860]
When codeigniter 4 will be released ? 
Any tentative date ? 

Can it compete with laravel ? I am big fan of codeigniter and i want it to be a better one.

**Comment by jim-parry** [comment]
It will be released when it is ready. This question has been addressed multiple times on the forum, which is the appropriate place for such discussion/questions - we use github for bug tracking and work packages.
