### ISSUE TITLE
Respond Error Pages by Content-Type

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#863]
As title says, to add a way to respond 404 and other error pages by request content-type.

Maybe just the Status Code or with a default message like the HTML views do...

**Comment by lonnieezell** [comment]
Completely agree. We could just have the exception message/code used and converted to JSON/XML/HTML depending on what content-type is negotiated with the client. 

We also need to do this for the Toolbar at some point.
