### ISSUE TITLE
about SessionHandlerInterface error

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#864]
Frequent operations show errors
No page can be opened
Reboot the server is normal
What's the problem, please?

Wrong picture：
http://wx3.sinaimg.cn/large/82c9caaegy1fmf2xiv52lj21hc0p40tw.jpg

**Comment by maczdata** [comment]
Are you using the latest update??

**Comment by jinmarcus** [comment]
The last time for the version I used is 2017-11-20
is ok?

**Comment by jinmarcus** [comment]
How to solve it

**Comment by lonnieezell** [comment]
Guidance for this can be found on [the forums](https://forum.codeigniter.com/thread-66544.html?highlight=contains+1+abstract+method). that's for a CI3 issue, but the session library didn't change from 3 to 4.
