### ISSUE TITLE
remark

### ISSUE THREAD

**Issue by janay666** [bcit-ci/CodeIgniter4#871]
in application/Config/Routes.php 
$routes->add('blog-site', 'Home::blogAction',['as' => 'blog']);

if < a href="{base_url()}blog-site">foo< / a > then http://localhost:8888/ci4/public/blog-site         <= public / blog-site
if < a href="{base_url()}{route_to('blog')}">foo< / a > then http://localhost:8888/ci4/public//blog-site <= public // blog-site

**Comment by lonnieezell** [comment]
Are you using the latest code from the develop branch? I cannot recreate this. The following all work with a single slash created: 

```
echo base_url().route_to('blog');
echo esc(base_url(route_to('blog')));
echo esc(base_url().route_to('blog'), 'attr');
echo esc(base_url(route_to('blog')), 'attr');
```
