### ISSUE TITLE
About environnement error_reporting

### ISSUE THREAD

**Issue by 35598253** [bcit-ci/CodeIgniter4#889]
Setting Environnement to Production,error_reporting (E_ALL & ~E_NOTICE) does not work, is it me to set the problem, or is it CI4 Setting ? Display_errors no problem!

**Comment by lonnieezell** [comment]
You can adjust stuff for production here: https://github.com/bcit-ci/CodeIgniter4/blob/develop/application/Config/Boot/production.php

**Comment by 35598253** [comment]
Thanks to reply, I changed in this file, but when there is no definition variables, or will appear errorexception Undefined variable: In the production environment, 
I want to prompt the error and direct operation, what should I do?
