### ISSUE TITLE
Database failover error on postgresql

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#899]
BaseConnection
initialize() function
failover connect before DNS clean required.

sample;
					$this->DSN = '';

					// Try to connect
					$this->connID = $this->connect($this->pConnect);

**Comment by lonnieezell** [comment]
I'm confused on what the actual error is that you're reporting. Please provide a better example and how you would expect it to work.

**Comment by byazrail** [comment]
hi,

old database dns string not clean new failover connection try.
postgreSQL Connection connect function;

```
if (empty($this->DSN))
{
	$this->buildDSN();
}
```

failover before not empty buildDNS;

BaseConnection;

```
// Replace the current settings with those of the failover
foreach ($failover as $key => $val)
{
	$this->$key = $val;
}

$this->DSN = ''; // added new line.

// Try to connect
$this->connID = $this->connect($this->pConnect);
```
