### ISSUE TITLE
Model::first() ambiguous id error

### ISSUE THREAD

**Issue by daylightstudio** [bcit-ci/CodeIgniter4#903]
I'm getting errors when I have a join on my Model. I'd recommend adding the table's prefix:
```
$builder->orderBy($this->table . '.' . $this->primaryKey, 'asc');
```
https://github.com/bcit-ci/CodeIgniter4/blob/1b8c4914e139f6bb20a4b949e019c4412a00c053/system/Model.php#L422

**Comment by daylightstudio** [comment]
The find method also could use the table prefix on lines 316 and 322.

**Comment by lonnieezell** [comment]
My time's extremely limited right now due to work. In the future - Pull Requests are a much faster way of getting these changes incorporated.
