### ISSUE TITLE
About Filters matching rules

### ISSUE THREAD

**Issue by bangbangda** [bcit-ci/CodeIgniter4#908]
Have different views on the current match rules,
for example:
`public filters = [
    'foo' => ['before' => ['admin/*']]
];`

URI is  `admin/show` , foo filter is run.
URI is  `admin/102/edit` foo filter is run.
but.
URI is `admin` ,foo filter **is not run**.

if the routes  is `$routes->resource('admin')`,
then filters is set `'foo' => ['before' => ['admin/*','admin']]`

i think `'foo' => ['before' => ['admin/*']]` is ok.

Is this okay.what do you think?

**Comment by lonnieezell** [comment]
If you want it to run on `admin` also, just change the rule to `'foo' => ['before' => ['admin*']]` and it should work for all of it. Note the lack of trailing slash there.
