### ISSUE TITLE
Find a bug ，CSRFVerify

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter4#912]
/System/Security/Security.php

`// Regenerate on every submission?
if ($this->CSRFRegenerate)
{
	// Nothing should last forever
	unset($_COOKIE[$this->CSRFCookieName]);
 #    **$this->CSRFHash = null; // here, Need to be set to null**
}`

**Comment by lonnieezell** [comment]
I'm not 100% sure if this is a bug or not. That library was copied over from CI3 so for now I'm trusting that CI3 has it right as it's been used in quite a few production pieces. Unless you can provide steps to reproduce a bug I'll have to close this for now.
