### ISSUE TITLE
Load language issue

### ISSUE THREAD

**Issue by iceleo-com** [bcit-ci/CodeIgniter4#913]
Hi,

I don't see the document about the Languages. I try this method:
```
	$language = service('language', 'en');
	$language->load('test');
```
And I get a error: 

> Call to protected method CodeIgniter\Language\Language::load() 

Any ideals help me to load a language?

Thanks!

**Comment by ridho1991** [comment]
No need to load language.
Just: echo lang('Languagefile.Languagekey');

see https://bcit-ci.github.io/CodeIgniter4/libraries/localization.html

**Comment by iceleo-com** [comment]
Thank ridho1991,

And how I change the value of $defaultLocale and $supportedLocales from my database? I need to change it dynamically.

**Comment by deathart** [comment]
https://bcit-ci.github.io/CodeIgniter4/libraries/localization.html#specifying-locale
