### ISSUE TITLE
This is a problem with frequent operations

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#933]
This is a problem with frequent operations

http://wx1.sinaimg.cn/large/82c9caaegy1foa6ts9nd5j21hc0ooab8.jpg

All pages are such this error

Excuse me, what's the reason？

**Comment by lonnieezell** [comment]
IIRC this was commonly happening on PHP versions less than 7.0.15 (you're using 7.0.13 here). Updating your PHP version should do. 

Please note, also, that the minimum supported version for CI4 has been changed to 7.1.
