### ISSUE TITLE
Major Security Flaw - Database Credentials get leaked. 

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#935]
It appears on php errors, using development mode, the database credentials get leaked from the config variables. 

```
[db] => CodeIgniter\Database\MySQLi\Connection Object

[hostname] 
[username]
[password] 
[database] 

```
It appears the database config is public, these variables should be concealed, at least to protected or private. Development or production mode, never should I see database credentials printed on the screen. 

That is why we have a `.env` file on each environment to protect the application from unauthorized users, or hacks and even developers from seeing true credentials of the database.

**Comment by lonnieezell** [comment]
I don't know that I'd say it's a "major" flaw. They would never be seen in production. And the .env file is to keep credentials out of repos. But I've fixed it all the same. Thanks.
