### ISSUE TITLE
mysqli_sql_exception: No such file or directory

### ISSUE THREAD

**Issue by kenny-ngo** [bcit-ci/CodeIgniter4#943]
When I try to run phpunit test, I run into the following error. 

128) CodeIgniter\Database\Live\WhereTest::testOrWhere
mysqli_sql_exception: No such file or directory

Any help would be greatly appreciated.

**Comment by lonnieezell** [comment]
Sounds like your test database isn't setup correctly. This page from the user guide should be a help: 

https://bcit-ci.github.io/CodeIgniter4/general/testing.html#test-database-setup
