### ISSUE TITLE
Validation "matches" rule is not getting the label from the corresponding field

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#946]
```php
$rules = [
	'new_password'         => [
		'label' => 'New Password',
		'rules' => [
			'required',
			'min_length[5]',
		],
	],
	'confirm_new_password' => [
		'label' => 'Confirm New Password',
		'rules' => [
			'required',
			'matches[new_password]',
		],
	],
];
```

> The Confirm New Password field does not match the new_password field.

**Comment by natanfelles** [comment]
Updating this line

https://github.com/bcit-ci/CodeIgniter4/blob/d18838cf110ecf59cdadcd48b526da28ce701b54/system/Validation/Validation.php#L678

to

```php
$message = str_replace('{param}', $this->rules[$param]['label'] ?? $param, $message);
```

could solves. Not sure about possible conflicts.

---

Or an special check only to rules that corresponds to other fields: `differs`, `matches`, `required_with`, `required_without`.

**Comment by lonnieezell** [comment]
Oh, dang. Yeah, that seems to be leftover from before we could support array syntax. I was getting ready to say that it's working fine in [my Auth library](https://github.com/lonnieezell/myth-auth) that I'm working on, but that's using the [string syntax](https://github.com/lonnieezell/myth-auth/blob/develop/src/Controllers/AuthController.php#L131): 

```
'password'     => 'required|strong_password',
'pass_confirm' => 'required|matches[password]',
```

And this is where we run into issues for being too flexible. :) 

One you've got might work, but would definitely need some tests in place trying it both ways.
