### ISSUE TITLE
url_helper current_url https fix.

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#947]
hi guys,

`
	function current_url(bool $returnObject = false)
	{
		$url	= \CodeIgniter\Config\Services::request()->uri;
		
		if (\CodeIgniter\Config\Services::request()->isSecure())
		{
			$scheme = 'https';
		}

		if (isset($scheme))
		{
			$url->setScheme($scheme);
		}

		return $returnObject === true ? $url : (string) $url;
	}
`

**Comment by lonnieezell** [comment]
It should be already from the Request class. Are you not seeing that?

**Comment by byazrail** [comment]
I see,
base_url() https fix. not be use current_url().

see https://blabla.com/foo/bar
current_url() - http://blabla.com/foo/bar

**Comment by lonnieezell** [comment]
What is your baseURL set to in application/Config/App.php?  base_url uses that to generate the URL.
