### ISSUE TITLE
Pager with search queries

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#950]
I'm trying to paginate model results by a GET query:

On the first search the URI is:

```
/search?q=you+alice+to+the+little
```

When clicked to the page 2 in the link generated by the Pager of Model `paginate()`, it becomes:

```
/search?q=you%2Balice%2Bto%2Bthe%2Blittle&page=2
```

Going to the third page, it becomes:

```
/search?q=you%252Balice%252Bto%252Bthe%252Blittle&page=3
```

I was able to manipulate the string to get the data in the database with:

```php
$search = $this->request->getGet('q');
$search = urldecode($search);
$search = str_replace('+', ' ', $search);
var_dump($search);exit;
```

Then all inputs will return the same string: `'you alice to the little'`.

This issue is related to the pagination links, that every time encode the, already encoded, query string.

On page 5 it becomes:

```
/search?q=you%25252Balice%25252Bto%25252Bthe%25252Blittle&page=5
```

On page 6:

```
/search?q=you%2525252Balice%2525252Bto%2525252Bthe%2525252Blittle&page=6
```

I tried to manipulate it with:

```php
$search = str_replace('%2B', ' ', $search);
$search = str_replace('%252B', ' ', $search);
```

But as the page number increases the URI is re-encoded and a new override is needed to keep the original string.

I would open this question in the forum, but I think it is more related to how pagination works at the moment.

Thanks.

**Comment by natanfelles** [comment]
Oh, solved here. Explicitly changing the `$_GET['q']` before call the model paginate solved it:

```php
$search = $this->request->getGet('q');
$search = urldecode($search);
//$search = str_replace('+', ' ', $search);
$_GET['q'] = $search;
```
I'll leave the issue open if you want to analyze more. Thank you.

**Comment by lonnieezell** [comment]
Yes, urlencoding was backed into the URI component to meet [RFC 3986](https://tools.ietf.org/html/rfc3986#page-14). However, you're the second person that mentioned confusion about it so I did a bit more digging around tonight. It appears there are times when at least Apache will already take care of URL-encodeing and decoding behind the scenes, so I'm thinking it might be smart to remove that feature and leave it to developers to encode if needed.
