### ISSUE TITLE
gzuncompress(): data error

### ISSUE THREAD

**Issue by 35598253** [bcit-ci/CodeIgniter4#956]
upload CI4  of webhost(Linux , php 7.2), starting development mode;
test :  https://www.nmrich.com/
Tips gzuncompress (): data error BASEPATH / ThirdParty / Kint / kint.php AT line 177;
 Local server  (Win , php7.2) normal

**Comment by lonnieezell** [comment]
I have never come across this error before. Can you check if your server has gzip enabled? What type of data are you outputting there?

**Comment by 35598253** [comment]
Thanks! 
Gzip ok!
Revert to previous versions OK！
Turn off Debug OK！
I think it should be Debug compatibility problem, but can not locate error point!

**Comment by 35598253** [comment]
Already found and solved problems

**Comment by nicojmb** [comment]
> Already found and solved problems

how have you solved it? in fresh install showme this error with "development" in production works.

![image](https://user-images.githubusercontent.com/5610392/47777441-07289b00-dcf5-11e8-995e-4366d62f289f.png)

**Comment by nicojmb** [comment]
I solve it!!!.
Just upload to to ftp site ./system/ThirdParty/Kint/kint.php in binary mode.
