### ISSUE TITLE
namespace error in centos7

### ISSUE THREAD

**Issue by jinmarcus** [bcit-ci/CodeIgniter4#959]
namespace error in centos7

environment: centos7 + php7

in windows is ok, but in centos7 is wrong

code is
```
<?php namespace App\Controllers\category;

class Product extends Controller
{
	public function index()
	{
		echo 'test';
	}
}
```

url is
```
http://www.xxxx.com/category/product
```

file path is
```
/ci4/application/Controllers/category/Product.php
```

result is 
```
404 - File Not Found
HTTP.pageNotFound
```

@lonnieezell

**Comment by natanfelles** [comment]
Create the file: **application/Controllers/Category/Product.php**

```php
<?php namespace App\Controllers\Category;

use CodeIgniter\Controller;

class Product extends Controller
{
	public function index()
	{
		echo 'test';
	}
}

```

Go: http://www.xxxx.com/category/product

---

Please ask for support in the [forum](https://forum.codeigniter.com/forum-30.html).

**Comment by jinmarcus** [comment]
@natanfelles it's ok, thank you!
