### ISSUE TITLE
About Replacing Core Classes!

### ISSUE THREAD

**Issue by 35598253** [bcit-ci/CodeIgniter4#973]
I want to Replace \CodeIgniter\Router\Router.php Core Classes，How to operate？

Now my work is：
Myrouter.php:

namespace App\Libraries;
class Myrouter implements \CodeIgniter\Router\RouterInterface
{
Copy Router Classes And edit Variable（Actually, I just want to replace some function）

}

Services.php:
 public static function routes($getShared = false)
    {
            if (! $getShared)
            {
                    return new \Rcmf\Libraries\Myrouter();
            }
    
            return self::getSharedInstance('routes');
    }

running error

How can I correct?

**Comment by InsiteFX** [comment]
You would want to extend the Router Class and not use implements that replaces the Class

[Creating Core System Classes](https://bcit-ci.github.io/CodeIgniter4/general/core_classes.html)

**Comment by 35598253** [comment]
I know，edit it,

namespace App\Libraries;
class MyRoute extends \CodeIgniter\Router\Router
{
 public function __construct()
    {
        parent::__construct();
    }

	public function autoRoute(string $uri)
	{
}
}

running error

Declaration of App\Libraries\MyRoute::__construct() must be compatible with CodeIgniter\Router\RouterInterface::__construct(CodeIgniter\Router\RouteCollectionInterface $routes)

**Comment by InsiteFX** [comment]
Your library should be named MY_Router not MY_Route

Also if you still get the error then add this to your __construct()
`__construct(CodeIgniter\Router\RouteCollectionInterface $routes)`

**Comment by 35598253** [comment]
Thanks!
 I edit it
My_Router
class My_Router extends \CodeIgniter\Router\Router
{



    public function __construct(\CodeIgniter\Router\RouteCollectionInterface $routes)
    {
        parent::__construct();
    }

	//--------------------------------------------------------------------

	
	//--------------------------------------------------------------------

	/**
	 * Attempts to match a URI path against Controllers and directories
	 * found in APPPATH/Controllers, to find a matching route.
	 *
	 * @param string $uri
	 */
	public function autoRoute(string $uri)
	{
		$segments = explode('/', $uri);
}

running error
Too few arguments to function App\Libraries\My_Router::__construct(), 0 passed in D:\richcms\App\Config\Services.php on line 27 and exactly 
How can I correct?

**Comment by InsiteFX** [comment]
This is this definition of the Router Class
`public function __construct($routing = NULL)`

Try leaving the __construct() blank and call the parent::__construct()

**Comment by 35598253** [comment]
Sorry, I don't understand what you mean;
class My_Router extends \CodeIgniter\Router\Router
{
	public function __construct($routing = NULL) {
	//	parent::__construct();
	}

}
running error
Call to undefined method Rcmf\Libraries\My_Router::cli()	

Can give me more detailed code？
thanks!

**Comment by InsiteFX** [comment]
Aww, sorry I had the wrong project in it was CI 3 I'll switch and take a look at it now brb.

**Comment by InsiteFX** [comment]
To use one of your own system classes instead of a default one, ensure that the Autoloader can find your class, that your new class extends the appropriate interface, and modify the appropriate Service to load your class in place of the core class.

**Comment by 35598253** [comment]
sorry I still don't understand,
I'm sure Autoloader can find My_Router class,
Services.php:
public static function routes($getShared = false)
{
if (! $getShared)
{
return new \Rcmf\Libraries\Myrouter();
}

        return self::getSharedInstance('routes');
}

 **that your new class extends the appropriate interface**
I modified it.
class My_Router extends \CodeIgniter\Router\Routerinterface
running error
Class App\Libraries\My_Router cannot extend from interface CodeIgniter\Router\RouterInterface

I just want to 
ReplaceCodeIgniter\Router\Router   function autoRoute()

How can I correct?
Can you give me code directly？

**Comment by InsiteFX** [comment]
Then in your Class just name the method as the one in the Router Class it will that overload one.

**Comment by 35598253** [comment]
sorry I still don't run,
1. Autoloader can find My Class
2.  **new class extends the Router**(I want to replace the autoroute() function in Router.php)
3.    autoroute() methods in my class
4.  Service::routes() load new classes

running error
Did I do anything wrong with these steps?

**Comment by jim-parry** [comment]
This is a conversation that should be happening on our forum. We use github for bug tracking and work packages.
