### ISSUE TITLE
route_to function working incorrect

### ISSUE THREAD

**Issue by phambinh217** [bcit-ci/CodeIgniter4#975]
My routes
```
$routes->get('posts/(:any)/(:any)', 'Post::index/$2', ['as' => 'post-with-slug']);
```
When I use
```
route_to('post-with-slug', '2', '3');
```
I want to result is `domain.com/posts/2/3`

But now result is `domain/posts/2/2`

What am I doing wrong, or it is a bug?

**Comment by InsiteFX** [comment]
Try only using one (:any) any matches to the end of the url

**Comment by lonnieezell** [comment]
To expand on what @InsiteFX said, use `(:segment)` now any place you would have used `(:all)` in previous versions. 

That being said - this area is reserved for bug-reports. The [forums](https://forum.codeigniter.com/index.php) are the appropriate place to ask for help.
