### ISSUE TITLE
Documentation - Session Library - session()->start()

### ISSUE THREAD

**Issue by gabpnr** [bcit-ci/CodeIgniter4#982]
In the documentation, the instruction for catch the session library with the helper causes confusions.
It is said : 
$session = session()->start();

but start() does not return the session object, so we can not use the others method directly (like $session->set(...) )

Two suggestions :
- add "return $this;" in the start() method (Session/Session.php)
or
- Change this line in the documentation

**Comment by akrindev** [comment]
```php
session()->start();

session()->set('hi','hello');

echo session('hi');
```
