### ISSUE TITLE
route_to() function not work if  greater than 3 parameters.

### ISSUE THREAD

**Issue by 784238ddda92fee476352f3ccaa6cca2** [bcit-ci/CodeIgniter4#992]
Hi
In file router.php

`$routes->get('test/(:segment)/(:segment)', 'TestController::index/$1/$2', ['as' => 'testRouter']);`

In controller:
echo route_to('testRouter', 1, 2);
or use redirect()->route('testRouter', [1, 2]);

Expected result:
/test/1/2

Actual result:
/test/1/1

Thanks

**Comment by natanfelles** [comment]
The replacement is occurring because of the same pattern:

https://github.com/bcit-ci/CodeIgniter4/blob/74e95d35edf38b6d3244cf862186454a5df67fdb/system/Router/RouteCollection.php#L1132-L1135

**Comment by natanfelles** [comment]
Maybe [preg_replace](https://stackoverflow.com/questions/1252693/using-str-replace-so-that-it-only-acts-on-the-first-match) helps.

**Comment by natanfelles** [comment]
This solves:

**CodeIgniter4/system/Router/RouteCollection.php:1132**

```php
if (preg_match("|{$pattern}|", $params[$index]))
{
	$pos = strpos($from, $pattern);

	if ($pos !== false)
	{
		$from = substr_replace($from, $params[$index], $pos, strlen($pattern));
	}
}
```

**Comment by natanfelles** [comment]
Parameters ordering continues working in Controllers:

```php
$routes->get('test/(:segment)/(:segment)/(:segment)', 'TestController::test/$2/$1/$3', ['as' => 'testRouter']);
```

http://localhost:8080/test/1/2/3

```php
public function test($param1, $param2, $param3)
{
	var_dump($param1);
	var_dump($param2);
	var_dump($param3);
}
```

**Comment by lonnieezell** [comment]
@natanfelles Thanks for digging into this one! Fix being committed currently.
