### ISSUE TITLE
It's blank page and set $baseURL

### ISSUE THREAD

**Issue by BI7PRK** [bcit-ci/CodeIgniter4#999]
After installation, open http://127.0.0.1 Its blank page.

modify ./public/index.php the code:

```PHP
try {  
    $app = require rtrim($paths->systemDirectory,DIRECTORY_SEPARATOR) . '/bootstrap.php';
} catch (Exception $e) {  
    print $e->getMessage();  
    exit();  
}  
```
can see the message:
> You have an empty or invalid base URL. The baseURL value must be set in Config\App.php, or through the .env file.

then set $baseURL in ./config/App.php
> public $baseURL = 'http://127.0.0.1';  //must start with  http/https.

it's well. but how to use both http and https on site?

**Comment by lonnieezell** [comment]
Please ask questions on the [forum](https://forum.codeigniter.com/index.php). The issues are for bug-tracking.

However, [this might be of assistance](https://bcit-ci.github.io/CodeIgniter4/general/controllers.html#forcehttps).
